### ISSUE TITLE
MIT and BSD also allow private use

### ISSUE THREAD

**Issue by paulmillr** [github/choosealicense.com#1]
You may use MIT stuff without distributing it.

**Comment by prabirshrestha** [comment]
apache v2 too.

**Comment by anaisbetts** [comment]
Private use is not distribution, so I don't know that any of these concerns apply with the exception of the AGPL

**Comment by haacked** [comment]
We've tried to list things that are explicitly allowed in the license. But in this case, I think it's an educational benefit to note that every license allows private use with the exception of AGPL.

@paulmillr  or @prabirshrestha would you be interested in submitting a PR?

**Comment by haacked** [comment]
BTW, the files to edit (which you can do in the browser) are:
- Apache https://github.com/github/choosealicense.com/blob/gh-pages/licenses/apache.txt
- MIT https://github.com/github/choosealicense.com/blob/gh-pages/licenses/mit.txt

Just need to add 

```
  - private-use
```

In the permitted section. Ideally do each one in a separate commit and we can discuss in the PR if any others need it. Thanks!

**Comment by jpmckinney** [comment]
I think it's more useful to note those licenses that forbid private use. Permitting private use is a basic assumption people make about public code.

**Comment by haacked** [comment]
@jpmckinney if I understand correctly, you're suggesting remove "private use" from "permitted" and move the entire category (with appropriate change of verbiage) to "forbidden" and then only apply it to AGPL. Right?

If so, would you be interested in submitting a PR for that change?

**Comment by jpmckinney** [comment]
Will do. "Commercial Use" is "Permitted" in all the licenses, so "Private Use" is a bit redundant - unless people are worried that some readers will think commercial use is permitted but not non-commercial use :P

**Comment by jpmckinney** [comment]
See #25

**Comment by haacked** [comment]
> "Commercial Use" is "Permitted" in all the licenses, so "Private Use" is a bit redundant

Yeah, we went back and forth on this a bit. While it is a bit redundant, part of the goal is to educate folks who don't understand licenses all that well. A person that already knows what license to choose can probably safely ignore this site.

The challenge for me is it's hard to know what people do or do not know about OSS licenses. That's kind of why we went with the bit of redundancy to make it clear that you _are_ allowed commercial use as that's often misunderstood.

But again, we love the suggestions for improving things.

**Comment by jpmckinney** [comment]
I'm happy to keep "Commercial Use". For "Private Use" we either need to (1) add it to all applicable licenses (which is all except maybe AGPL), which is what this issue is about, or (2) remove it from those that currently have it. In terms of choosing between the two options, if it's unclear that "Private Use" is permitted by all the licenses unless stated otherwise, then we should go with the first option.

**Comment by mozz30-tech** [comment]
> You may use MIT stuff without distributing it.
>
