### ISSUE TITLE
Sublicensing warning inappropriate for GPLv3

### ISSUE THREAD

**Issue by webmink** [github/choosealicense.com#10]
There's a warning about sublicensing being forbidden for GPLv3 & v2 (and Affero). While this is technically correct, I think a warning is inappropriate as the risk to the license user is minimal.  

Clause 10 explains that, instead of you sublicensing the original work, 
    "Each time you convey a covered work, the recipient automatically receives 
    a license from the original licensors, to run, modify and propagate that work, 
    subject to this License."  
Sublicensing is thus redundant, since every recipient has a license to the original work from the copyright holder, plus a license from you to your modifications.

I suggest just removing the warning.

**Comment by jpmckinney** [comment]
Is there anything incorrect in the statement, re: GPL, "You may not grant a sublicense to modify and distribute this software to third parties not included in the license."? In either case, I think having consistency across license descriptions outweighs being accurate to the last detail.

**Comment by webmink** [comment]
The key here is to avoid causing concern where there is none necessary for the majority of users. As far as I can see (I may be wrong), it's only the GPL family of licenses that have this language, so the "not sublicensable flag" seems to only apply to them. Since the risk to the normal Github user seems minimal, surely consistency should mean dropping the warning and remaining consistent with all the other license analyses?

**Comment by jpmckinney** [comment]
The GPL's "copyleft" clauses are the most significant ways in which it differentiates itself from other licenses, so either the "Forbidden: Licensing" verbiage needs to stay, or someone needs to propose an alternative way of communicating that GPL is copyleft, whereas most other licenses are not.

Consistency is one thing. Making all licenses appear to be identical is another!

**Comment by webmink** [comment]
I do agree that the implications of the use of GPL by a project should be highlighted; I was surprised _not_ to see a warning like "all code re-used from this repository must be licensed identically" included. 

However, that's not the same issue as this one, which is about sublicenseability being redundant for this license.

**Comment by jpmckinney** [comment]
Ok, then what I'm saying is that, in my opinion, this issue will not be closed without it (or another issue) adding _something_ that describes what makes GPL different on the `/licenses/` page.

If we just remove the "Forbidden: Licensing" part from the GPL's description, which is what this issue is about (if I understand correctly), that would make the GPL look identical to a lot of licenses which are very different from it.

**Comment by ghost** [comment]
If I get this discussion right... @jpmckinney uses the term "sublicensing" to mean "license this code under a _different_ license than this one"? While @webmink considers the concept as implied in GPL licenses language, simply to mean like "give a license when you distribute it". Or, do I misunderstand?

If this is the issue... FWIW personally I agree that the site uses unexpectedly the concept of "sublicensing". It's not entirely correct (or useful, IMHO) to say that "forbid licensing under different terms" would apply only for GPL. Because _any_ copyleft forbids licensing under different terms. For their covered code. MPL, LGPL, GPL, all require licensing of their covered code under similar terms. The difference is the scope of copyleft, extent of that covered code. (and for AGPL, way of access to the modified software I suppose)

**Comment by ghost** [comment]
I think the cases for a few copyleft licenses can be simplified like:
- MPL covers under MPL only the files which contain the code itself with or without modifications.
- LGPL covers under LGPL what we commonly understand as fork of a project. (that's likely more than MPL, while one can still use the entire project without modifying it in another software licensed differently).
- GPL covers under GPL any code which uses the the original code, as long as it forms together a work considered a derivative under copyright law or close to.
- for AGPL, same as GPL but it also applies for users with networking access to the modified software.
  (obligatory note please: IANAL. This is just my simplistic understanding.)

Copyleft scope includes both:
- what (I suppose?) the site currently calls "sublicensing"... IMHO the term is confusing, as I think this issue shows. Any copyleft license "forbids licensing under different terms" for their covered code.
- what the site calls "disclose source". Which also is not entirely correct IMHO in the same way: copyleft licenses don't require just "source disclosure" - if it would be under a non-redistribution-non-modification license it wouldn't make much sense in usual cases.

Suggestion: could we classify copyleft licenses after the scope of copyleft, instead? After the extent of the code covered by the requirement to be open source. (or under the same or similar license)

One can almost order them by that... I think it would be much more useful for developers looking to choose a license. I'd say what one cares about is permissive or copyleft, and for copyleft, how much does the copyleft extend. Which code is and will be open source, in modified distributions.
Sorry, this isn't a proposal yet. Only a suggestion for discussion, as I think the current way to classify licenses isn't as useful as it could be... In particular the classification should be simple and easy to understand, if it were to help making an informed choice.
(if the suggestion is misplaced here, I'll open another issue)

**Comment by benbalter** [comment]
Is this issue still relevant?

**Comment by Hawke** [comment]
I certainly found the warning confusing. It could use some clarification about whether 'sublicensing' means that licensees are allowed to re-license with a different license, or whether they're allowed to convey the work to others subject to the same license. (my understanding is that they are, in which case "sublicensing forbidden" is misleading.)

**Comment by webmink** [comment]
I agree with that last comment. The objective of sublicensing is to convey the work to others. The GPL permits this but uses an alternative mechanism. Stating that sublicensing is forbidden communicates that conveying the work is not allowed. Since that's an incorrect impression, it would be better to either reword or (better) remove the statement.

**Comment by xrchz** [comment]
:+1:

**Comment by dudy5** [comment]
The 'Sublicense' in GPL actually means 'relicense', See FSF'FAQ of GPLv3:
http://gplv3.fsf.org/wiki/index.php/FAQ_Update#What_does_.22sublicense.22_mean.3F
