### ISSUE TITLE
Add "License Builder"

### ISSUE THREAD

**Issue by parkr** [github/choosealicense.com#100]
Just want to throw this out in case it is of interest.

[The Creative Commons website has a license builder](http://creativecommons.org/choose/) which offers a neat form-based procedure for picking a variation of the CC license.

Something similar here would be great for discovery and matching needs perfectly. The homepage of ChooseALicense helps with this a tiny bit (top grid) but only pushes MIT, Apache and GPL licenses, which kind of sucks. Only suggesting 4 licenses is a real bias that seems a little misplaced.

**Comment by haacked** [comment]
Thanks for the suggestion.

We considered that, but that's not what this site is about.

In the [about page](http://choosealicense.com/about/) we note:

> This site is not a comprehensive directory of open source licenses. **We think there are too many options, which adds to the confusion.** On the homepage, we break it down into just three licenses. The vast majority of projects will likely be fine choosing from one of these three. Just in case you have specific needs not covered by those three, we also highlight a few other licenses to consider.

We're more interested in license non-proliferation than proliferation. If we have so many licenses that some choose your own adventure is required, then I think we've failed.

**Comment by ghost** [comment]
There are only very few CC licenses. (if we don't count localized versions of course)
The utility of the builder doesn't seem to me about number of licenses, but about clarity of permissions and conditions. And, I think it's awesome too. :smile_cat: 

However, CC licenses were drafted intently as a family, to be truly similar except for the points in the license builder; unfortunately (?) open software licenses are not that way.

The green/red bullet points on choosealicense seem to aim the same thing, to reduce open licenses to a set of clear permissions and conditions... Personally, I look at them as in-progress work. If this reduction will be successful, the license chooser could be implemented as a CC-like license "builder"... I'm not sure. IMHO we can't correctly express open licenses in bullet points, so I guess a "builder" would be more misleading than mere display of some bullets along with the descriptions and full text.

**Comment by afeld** [comment]
Yeah, I definitely see the argument for this, even if we only limit the set to "well-known" licenses.  That's probably how people are using http://choosealicense.com/licenses/ anyway, but doing the filtering in their brains.  Maybe that's a way to think about it: filtering on that page (or a similar one), vs. a full-blown wizard.

**Comment by afeld** [comment]
Dupe of #96.

**Comment by benbalter** [comment]
> Only suggesting 4 licenses is a real bias 

As @Haacked pointed out, we are purposely biased towards reducing choice.

> Maybe that's a way to think about it: filtering on that page (or a similar one), vs. a full-blown wizard.

Faceted search on the `/licenses` page may be helpful to power users, and may be a good addition, but would not target our primary use case.
