### ISSUE TITLE
Consider replacing MIT with ISC

### ISSUE THREAD

**Issue by nickserv** [github/choosealicense.com#1007]
I know the name MIT is more popular, but from what I understand these licenses are legally equivalent, and I think it's easier to use the ISC because it's shorter and more direct.

FWIW npm has also been using it by default, and I also use it for my repositories.

**Comment by mlinksva** [comment]
But MIT is still far more popular even for npm. Of course you should use it but the benefit of saving a few words in the text is far outweighed by much stronger recognition for a general audience.
