### ISSUE TITLE
add NonCommercial license

### ISSUE THREAD

**Issue by 89z** [github/choosealicense.com#1015]
It seems the current list:

https://choosealicense.com/appendix

does not offer a NonCommercial license. Examples:

- https://creativecommons.org/licenses/by-nc/4.0/legalcode.txt
- https://polyformproject.org/licenses/noncommercial

These type licenses are unpopular and have downsides, but regardless, I think at least one should be on the list. People should be able to make an informed choice of what license to use, and omitting this type of license prevents them from doing so.

**Comment by nschonni** [comment]
https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license

**Comment by mlinksva** [comment]
Yeah, as the link @nschonni points to says, they are currently out of scope for the project.

**Comment by 89z** [comment]
> Yeah, as the link @nschonni points to says, they are currently out of scope for the project.

@mlinksva not sure how you were able to reach that conclusion:

> 1. The license must have [an SPDX identifier](https://spdx.org/licenses/). If your license isn't registered with SPDX, please [request that it be added](https://spdx.org/spdx-license-list/request-new-license).

https://spdx.org/licenses/CC-BY-NC-4.0.html

> 2. The license must be listed on one of the following approved lists of licenses:
> * [GNU's list of free licenses](https://www.gnu.org/licenses/license-list.en.html) (*note: the license must be listed in one of the three "free" categories*)

https://www.gnu.org/licenses/license-list.en.html#CC-BY-NC

> 3. The license must be used in at least *1,000* public repositories. This may be documented, for example, with a [GitHub code search](https://github.com/search?q=MIT+filename%3ALICENSE&type=Code).

https://github.com/search?q=filename%3ALICENSE+NonCommercial+&type=Code

**Comment by mlinksva** [comment]
2. Each of those lists preclude NC.

**Comment by 89z** [comment]
previous comment from @mlinksva is correct. For anyone interested, I found another one as well:

https://fair.io

**Comment by wxolp** [comment]
https://github.com/golang/go/issues/54683
