### ISSUE TITLE
Support for Climate Strike License?

### ISSUE THREAD

**Issue by rdehuyss** [github/choosealicense.com#1017]
Hi - thanks for this great initiative.

I would like to relicense my project [JobRunr](https://github.com/jobrunr/jobrunr) to LGPL with the addition of the climate strike addendum. 

What is the climate strike license:
> Climate Strike Software is software that uses the [Climate Strike License](https://github.com/climate-strike/license/blob/master/licenses), a software license that developers can use to prohibit the use of their code by applications or companies that threaten to accelerate climate change through fossil fuel extraction.

The idea would be that companies that are still interested in using JobRunr would pay for using the software. That money would go to charity projects like https://teamtrees.org/.

Is this something you would be willing to support?

**Comment by nschonni** [comment]
https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license

**Comment by mlinksva** [comment]
Out of scope for this project, read the link Nick posted above.

To make the concept more consumable by meta-licensing projects like this though, I'd suggest contributing to fixing https://github.com/climate-strike/license/issues/21
