### ISSUE TITLE
OSL 3.0 should be Same license (library) instead of Same license

### ISSUE THREAD

**Issue by ghost** [github/choosealicense.com#1031]
The problem with Open Software License 3.0 license document is that it does not explain important terminologies, so one has to also refer to[ Lawrence Rosen's website](https://rosenlaw.com/OSL3.0-explained.htm) to fully understand this license.

§ 1(c) in the document says: 
> The licensor allows you to distribute or communicate copies of the Original Work and Derivative Works to the public, with the proviso that copies of Original Work or Derivative Works that You distribute or communicate shall be licensed under this Open Software License.

But what is "Derivative Works"? § 1(b) in the document says:
>  Licensor allows you to translate, adapt, alter, transform, modify, or arrange the Original Work to create Derivative Works.

This is informative, but does not tell us if a larger project that uses the Original Work is considered Derivative Works or not. 
Now we head to Rosen's website. Section "IV. Source Code And Derivative Works" says: 
> Linking an unchanged Original Work with another independently-written work does not, absent more, create a Derivative Work subject to § 1(b); such an act is merely the incorporation of a copy of that Original Work into a collective work, authorized by § 1(a). 

So the terminology "Original Work", "independently-written work" and "collective work" in OSL 3.0 are equivalent to "The Library", "Application" and "Combined Work" in LGPLv3, respectively. Next we have:
> As for independent works (in the copyright sense), or the independent components of collective works, the OSL 3.0 grant of copyright license in § 1 does not affect those works at all or place any source code requirements upon them. That independent source code need not be disclosed. In this respect, OSL 3.0 is more like LGPL than GPL in its effect, although it accomplishes that with far fewer words and far less uncertainty. 

So source code that is copyrighted, written by the licensee and not part of Original Work or Derivative Work is not subjected to Source Disclosure. This is similar to LGPL, not GPL. I suggest changing OSL 3.0 to Same license (library), and if you can, contact Lawrence Rosen beforehand for confirmation.

**Comment by mlinksva** [comment]
`same-license - Modifications must be released under the same license when distributing the software. In some cases a similar or related license may be used` as used here is intentionally broad. `--library` and `--file` are used where the license is question is explicit.
