### ISSUE TITLE
Cannot propose new LICENSE file in PR for repost without write permission despite forking

### ISSUE THREAD

**Issue by brylie** [github/choosealicense.com#1032]
When trying to open a license pull request on projects that I don’t own, I have encountered the following error.

> You’re making changes in a project you don’t have write access to. Submitting a change will write it to a new branch in your fork brylie/Dash-Fractal-Explorer, so you can send a pull request.

At that point, I am unable to propose the new file since the primary repository is still selected instead of my fork, which was automatically created. How can I select my fork instead of the primary repository so I can submit the pull request?

Steps to reproduce

1. choose a repository to which you don’t have wire access
2. copy the repository URL
3. choose a license on choose a license.com
4. paste the repository URL into the input: “Enter a GitHub repository URL”
5. review and submit the license template
6. on the “New File” screen, observe that the “Propose new file” button is deactivated and the primary repository is selected instead of your fork

**Comment by mlinksva** [comment]
Thanks, I'm able to reproduce this. Seems like step 6 is a behavior (presumably a bug) that did not occur at some point in the past. I'll see what I can figure out.

In the meantime you could just go to the target repo, click "add file", name the file LICENSE, paste in the relevant license text -- and the "propose new file" button will be green (also just tested). That's all the steps above _should_ be a UI over.

**Comment by mlinksva** [comment]
This was fixed at some point in last 11 months. Closing now, feel free to reopen if it breaks or is still broken!
