### ISSUE TITLE
Provide more clarity about the virality of GPL, in particular with respect to libraries

### ISSUE THREAD

**Issue by MaddyGuthridge** [github/choosealicense.com#1033]
If someone creates a library that can be used by others in their projects and that library uses a GPL license, any code that links to that library must also be GPL. Although this is briefly mentioned in the description of the GPL licenses, it could be worded a little more clearly, and perhaps link to the equivalent LGPL licenses, which have an exception for linking (which is useful for software libraries).

**Comment by mlinksva** [comment]
Feel free to make a concrete suggestion. The current descriptions which one can see all at once for a range of licenses at https://choosealicense.com/licenses/ aim to be accurate, brief, and neutral, which is challenging. "Viral" for example would not be considered neutral. 😆
