### ISSUE TITLE
Suggestion: add 'Expat' as a nickname for 'MIT' license?

### ISSUE THREAD

**Issue by jayaddison** [github/choosealicense.com#1077]
Would it make sense to add `nickname: Expat` (where `Expat` is _not_ an SPDX identifier) to the MIT License metadata in this repository?

**Comment by jayaddison** [comment]
(in a sense, I think that the `Expat` license _is_ the MIT license, perhaps even less-ambiguously so -- the `nickname` field seems like a way to (begin?) representing that within this project)

**Comment by mlinksva** [comment]
Seems reasonable to me, feel free to open a PR.

**Comment by jayaddison** [comment]
Thanks, will do :+1:

**Comment by jayaddison** [comment]
Hm.  After looking again at some of the templates, the naive quick fix I had in mind would likely be confusing for site visitors (for example: the [description of projects that use a given license](https://github.com/github/choosealicense.com/blob/0ccd6c5d0ce1c0f68e088ec0c936322e43b2fbfb/_includes/using-sentence.html#L13) would mention `Expat` (or, perhaps `MIT (Expat)`), but that wouldn't provide much context about why the nickname exists or how it relates to `MIT`.

This could require a bit more analysis - I probably should've spent more time thinking about it before creating this thread.

Perhaps something more like alternative-names-for, or permitting multiple nicknames, might help.

**Comment by Strata10** [comment]
Good
