### ISSUE TITLE
"More choices" should include the EUPL

### ISSUE THREAD

**Issue by BenWiederhake** [github/choosealicense.com#1088]
Most licenses are US-based. That's okay! The "I want more choices" page should additionally advertise the EU public license ( https://eupl.eu/1.2/en/ ), which was developed specifically with EU law in mind. There's also also some well-known projects which use the EUPL, for example [pi-hole](https://github.com/pi-hole/pi-hole/blob/master/LICENSE).

**Comment by mlinksva** [comment]
EUPL-1.1 and EUPL-1.2 are listed in https://choosealicense.com/appendix/

I'm not totally sure where EUPL-1.2 would fit on the "more choices" page, which is meant to illustrate the range of condition-heavy to unconditional licenses available. As a side note, I like EUPL-1.2's assertion of compatibility with a range of licenses, curious how that works out in practice with its ~network applicability.

Closing as I don't think there's any action now, but feel free to comment.
