### ISSUE TITLE
MIT NO-AI

### ISSUE THREAD

**Issue by tolstenko** [github/choosealicense.com#1109]
Hi all!

I am raising a concern about a new type of license that should protect against the usage of generative AI tools such as GitHub copilot, starcoder and others.

Here goes a starting point: https://ognjen.io/mit-no-ai/ This is a modified MIT Licence that disallows the usage of GEN AI assistant tools.

Here go some nice resources:
- https://www.reddit.com/r/programming/comments/11vr4tf/the_noai_3clause_license/
- https://ognjen.io/mit-no-ai/

Reasoning:
- https://opensource.org/licenses/?ls=artificial+intelligence returns nothing
- https://github.com/github/choosealicense.com/issues?q=artificial+intelligence returns nothing

If you want to know if your code is in the training set of the starcoder model, you can check it here and opt-out https://huggingface.co/spaces/bigcode/in-the-stack 

In the worst scenario, it could be some method similar to the `robots.txt` to limit the crawlers that want to be fair.

What do you think?

**Comment by nschonni** [comment]
https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license

**Comment by mlinksva** [comment]
Out of scope for this project, per the link @nschonni posted.

**Comment by tolstenko** [comment]
Thanks for pointing out the path :)
