### ISSUE TITLE
EUPL 1.2 does not have a same-license requirement

### ISSUE THREAD

**Issue by willfaught** [github/choosealicense.com#1117]
It explicitly lets you convert to a less restrictive license (e.g. in terms of network use), like GPL v2. It allows conversion to half a dozen other licenses that it explicitly lists. It shouldn't have a green dot under the "Same license" column.

**Comment by mlinksva** [comment]
The definition (see the tool tip) of `same-license` is broader, and other licenses also allow use of other licenses under some conditions. Possibly a different keyword would be ideal but I don't think it's necessary to change now.

**Comment by mlinksva** [comment]
Tangent: Also taking opportunity to mention again (though I don't know that I have anywhere with respect to EUPL, but have in distant past with respect to CC-BY-SA-4.0 is compatible licenses and MPL-2.0 and its secondary licenses) -- I'd really enjoy reading about projects that have successfully used these compatibility affordances in the wild.
