### ISSUE TITLE
Quick copy button

### ISSUE THREAD

**Issue by ghost** [github/choosealicense.com#1119]
You should add a copy and paste button to the license pages so users don't have to copy the entire license manually, which can be pretty tedious for long licenses.

**Comment by mlinksva** [comment]
This has existed since choosealicense.com was launched nearly 10 years ago https://github.blog/2013-07-15-choosing-an-open-source-license/#:~:text=copy%20it%20to%20your%20clipboard%20with%20one%20click

**Comment by ghost** [comment]
ohhhhh. I somehow missed it.
