### ISSUE TITLE
Support for translations

### ISSUE THREAD

**Issue by haacked** [github/choosealicense.com#112]
It'd be nice if we could support translations for choosealicense.com. Several PRs have come in that translate the site, but they simply overwrite the English version :scream: 

We need a better approach.

The inelegant solution would be to have folders for each language that each pretty much contain the entire site translated to a language and then provide links on the main index to each.

A more elegant solution is to use Jekyll localization support (assuming there is such a thing) to do it. Or to build something ourselves.

**Comment by haacked** [comment]
@benbalter  is way ahead of me. See #68

**Comment by liks79** [comment]
That's good!
I think so.
Is Jekyll localization support available?
How can I apply it?

Thanks!

**Comment by haacked** [comment]
@liks79 I'm not sure yet. But I think we'll discuss a solution in #68 and let you know!

**Comment by matbrgz** [comment]
No news about this? How about use some gem plugin?
