### ISSUE TITLE
standardize order for required/permitted/restricted buckets

### ISSUE THREAD

**Issue by talniv** [github/choosealicense.com#113]
![screen shot 2013-10-28 at 5 08 55 pm](https://f.cloud.github.com/assets/5177438/1425121/99b9c3ae-402e-11e3-81a8-75b8975bc09d.png)
![screen shot 2013-10-28 at 5 08 14 pm](https://f.cloud.github.com/assets/5177438/1425122/99b9e960-402e-11e3-87b5-19f0ad1d275d.png)
![screen shot 2013-10-28 at 5 08 43 pm](https://f.cloud.github.com/assets/5177438/1425123/99bc1c94-402e-11e3-87f7-d988798e420f.png)

Just examples for cases where we have them in different order. 

Is there a reason for this? I like that these spell out the gist of the license and i think there is real value in the visual clarity that can be found in an ordered list that we are losing when we don't keep the same orde.

**Comment by haacked** [comment]
Seems like sloppiness on our part. Want to propose an order? Should we just do it alphabetically?
