### ISSUE TITLE
replace qtip2

### ISSUE THREAD

**Issue by mlinksva** [github/choosealicense.com#1140]
https://github.com/qTip2/qTip2 not maintained in a long time, and functionality probably no longer requires javascript. Might https://github.com/chinchang/hint.css be a replacement?

Thoughts or PRs welcome.

**Comment by chahmedejaz** [comment]
Hi @mlinksva! I hope you are doing great. I did a spike on the issue and here are my findings:
- We **can** replace `qTips2` with `hint.css`
- However, we **cannot** remove JS from the functionality entirely:
  - We need to conditionally show the error qTip on the sidebar input here:
![image](https://github.com/github/choosealicense.com/assets/59338032/7f28c6ce-310e-4cc4-ae01-960fbab55a64)
- We might need to compromise the design of qTips as hint.css just render text in qTip, whereas we are rendering a **heading** (_Error_) and **text** (_Invalid url_) for the qTips. 

Overall, we can do this. Should I move forward with the issue?

**Comment by mlinksva** [comment]
Thanks @chahmedejaz for doing the research/spike (I now see pure CSS [limitations]( https://github.com/chinchang/hint.css/wiki/Frequently-Asked-Questions))! The heading/message in two colors is used also or license condition tooltips eg on https://choosealicense.com/licenses/. I'd be OK with changing the design to only be one line/one color, perhaps with the current heading, colon, then the current message. So yes, please do move forward with the issue!

**Comment by chahmedejaz** [comment]
Hey @mlinksva, the PR is ready for review. Would love to hear your thoughts on it. Thanks :)

**Comment by mlinksva** [comment]
Fixed by #1141
