### ISSUE TITLE
Adding Artistic-2.0 license 

### ISSUE THREAD

**Issue by LiNk-NY** [github/choosealicense.com#1179]
Could a section describing the `Artistic-2.0` license in https://choosealicense.com/licenses/ be added?
I would like to link to this website to guide our developers. 
We [often](https://code.bioconductor.org/search/search?q=f%3aDESCRIPTION%20License%3a&num=4050) use `Artistic-2.0` and having it listed there would be great. 
Thank you!

**Comment by mlinksva** [comment]
I think your "often" link is supposed to be https://code.bioconductor.org/search/search?q=f%3ADESCRIPTION+License%3A+Artistic-2.0

Anyway, it's on https://choosealicense.com/appendix/ and https://choosealicense.com/licenses/artistic-2.0/
