### ISSUE TITLE
Why doesn't choose a license have restrictive licenses?

### ISSUE THREAD

**Issue by NotLazy** [github/choosealicense.com#1189]
I notice that in the appendix, *every* license, has commercial use, distribution and a few others. Why are there no licenses on here that don't permit commercial use or distribution, etc.

**Comment by nschonni** [comment]
That type of license wouldn't meet the requirement in any of the lists required for 2 https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license

**Comment by mlinksva** [comment]
As Nick cites, non-open licenses are not currently in scope for the project.

**Comment by NotLazy** [comment]
> As Nick cites, non-open licenses are not currently in scope for the project.

I feel like, by name of the project "choosealicense", it should be in scope? I would assume by the name of this project that I would be able to use this website to get help choosing a license, open or not, for my project.
