### ISSUE TITLE
Copy to clipboard doesn't show "Copied" with Firefox

### ISSUE THREAD

**Issue by XhmikosR** [github/choosealicense.com#119]
Chrome works fine, only FF 25+ I tried has this problem.

**Update**

To clarify, @XhmikosR told me that the license text is actually copied just fine, but the button text is not updated to reflect that.

**Comment by XhmikosR** [comment]
Duplicate of https://github.com/github/choosealicense.com/issues/46

**Comment by haacked** [comment]
@XhmikosR Any interest in sending a pull request to fix it?

**Comment by XhmikosR** [comment]
I already had a looked but couldn't pinpoint the cause.

But 1) I'm not very familiar with coffeescript and 2) I believe the JSHint warnings are relevant.

Especially, `'Choosealicense' is already defined.`

**Comment by afeld** [comment]
The JSHint warning, while unfortunate, isn't the cause: https://github.com/jashkenas/coffee-script/issues/1507  I think the issue is https://github.com/zeroclipboard/zeroclipboard/issues/268.

**Comment by XhmikosR** [comment]
OK after some more digging into this, Firefox doesn't support `innerText` for some reason...

If I do

``` js
    Choosealicense.prototype.clipboardComplete = function(client, args) {
      return this.innerHTML = "Copied!";
    };
```

works but the "Copied" text is shown indefinitely in Firefox. In Chrome this doesn't show the "Copied" text at all.

**Comment by haacked** [comment]
Hmm, perhaps something like the following?

``` js
if (this.innerText) return this.innerText = "Copied!";
return this.innerHTML = "Copied";
```

As for Firefox showing it indefinitely, I assume the same change must be made to the place where we make that message go away.

**Comment by XhmikosR** [comment]
It seems we'll need something like that, yes.

**Comment by XhmikosR** [comment]
Since we use jquery there must be a way to do it with it that works in most browsers...

**Comment by afeld** [comment]
`this.innerHTML = ...` can be done w/ `$(this).html(...)` in jQuery.

http://api.jquery.com/html/

**Comment by XhmikosR** [comment]
@afeld: while this works, the "Copied!" text stays indefinitely in FF...

But it seems to work with IE too. So we need to figure out why FF doesn't reset the button text like the other browsers.

**Comment by XhmikosR** [comment]
I think we should follow this workflow to work around this issue:
1. use jquery to get the value of the button text, which should be "Copy license text to clipboard"
2. store the above value and use it in `clipboardMouseout` and get rid of `innerText`
3. use jquery again to change the text in the button

``` js
Choosealicense.prototype.clipboardComplete = function(client, args) {
  return $(this).text("Copied!");
};
```

**Comment by haacked** [comment]
If it works, it sounds good to me. :)

**Comment by XhmikosR** [comment]
It _should_ work, but my JS skills aren't the best so I mentioned it in case someone else can try doing the above... Maybe @afeld :)

**Comment by benbalter** [comment]
Is this still an issue?

**Comment by XhmikosR** [comment]
Yeah.
