### ISSUE TITLE
Home page formatting slightly broken on Chrome on Ubuntu 22.04

### ISSUE THREAD

**Issue by RTnhN** [github/choosealicense.com#1196]
Chrome shows that the "Which of the following best describes your situation" is not between the two curly braces:

![image](https://github.com/github/choosealicense.com/assets/43109787/45e6a306-2093-4709-a53f-3908bdb45a0e)

It looks fine on firefox though:
![image](https://github.com/github/choosealicense.com/assets/43109787/b0a20491-cbeb-4095-8969-098ad00eda2f)

If we change the font size on the h2 element to 1.5rem or 1.6rem, it fixes the spacing issues. Is this something that I could create a PR for? Is this a problem for other people's browsers?

Chrome Fixed
![image](https://github.com/github/choosealicense.com/assets/43109787/d9e3f67a-da9c-4dc6-a0f8-93036b42a93f)

**Comment by mlinksva** [comment]
I don't think changing the font size is a fix; the same problem would just occur at a different resolution, wouldn't it?

It shouldn't occur at all, with the text going to multiline if it doesn't fit, like

![Image](https://github.com/github/choosealicense.com/assets/40415/7d1f4341-023a-4f7b-8a15-a17c42db0861)

Could you say what version of Chrome you're using?

**Comment by RTnhN** [comment]
I needed to reinstall chrome over the past couple days for another reason. With the install, it is now fixed. I don't know what version I was on, but I am on Version 122.0.6261.69 (Official Build) (64-bit).

I think that we can just close this now.
