### ISSUE TITLE
Terms of Use and Privacy Policy

### ISSUE THREAD

**Issue by Zwyx** [github/choosealicense.com#1204]
There are often two aspects of open source applications:
- their source code,
- their website hosting a running version of the app.

Some example:
- PrivateBin ([source](https://github.com/PrivateBin/PrivateBin), [hosted version](https://privatebin.net/))
- Squoosh ([source](https://squoosh.app/), [hosted version](https://github.com/GoogleChromeLabs/squoosh))

For the source code, we have to choose a licence. And that's easy thanks to [choosealicense.com](https://choosealicense.com/) and [opensource.guide](https://opensource.guide/). (Thank you!)

**But for the hosted app, understanding our obligations is much more difficult**! Do we need Terms of Use? Do we need a Privacy Policy?

I wish their would be something as simple as an "MIT license for Terms of Use": something simple, to limit the liability of the developer, basically saying "This app is provided 'as is', I don't guarantee anything."

I asked [two](https://law.stackexchange.com/questions/101279/can-i-use-the-mit-license-as-terms-and-conditions-on-a-personal-project) [questions](https://law.stackexchange.com/questions/101296/what-are-the-risks-if-any-of-not-having-terms-and-conditions-and-a-privacy-pol) on Stack Exchange, but the answers don't satisfy me. It shows there is a lack of simple terms and privacy policies that people could use when they put an open source work online.

- PrivateBin doesn't have terms of use or a privacy policy.
- Squoosh doesn't have terms but has a privacy policy (although very simple: it doesn't mention that IP addresses might be collected by the hosting provider).

The question also applies for documentations of open source libraries:
- react.dev has terms of use and a privacy policy (from Meta, probably much more complex than necessary),
- vuejs.org has none of them.

**Would it be possible to add to `choosealicense.com` or `opensource.guide`, some documentation and templates of simple Terms of Use and Privacy Policies, for open source developers to use when they host their projects?**

**Comment by mlinksva** [comment]
Interesting idea but I think out of scope for this project. I'll leave open for awhile as I'd be curious about pointer to projects that have attempted to do a minimal ToU intended to be used as-is or customized.

There are open source web apps that ship with default terms, but off the top of my head, they are customized for the application, e.g., https://github.com/discourse/discourse/blob/d0d659e7330e1221f57cf6202a8de5c1604556f6/config/locales/server.en.yml#L4583

**Comment by Zwyx** [comment]
Thank you for your reply! I haven't found any such projects, so I created one: https://github.com/Zwyx/minimal-terms-of-use-and-privacy-policy

At the moment, it contains simple Terms of Use and a Privacy Policy, which I think are enough to cover our bases, although I'm not a lawyer.

**If people knowledgeable in this area would accept to contribute, it would be amazing!**

If you know such people, please feel free to point them to this project :slightly_smiling_face:

**Comment by mlinksva** [comment]
Good luck!

I should've but did not recall when replying above that @kemitchell created reusable terms of [service](https://turnstiletos.com/), [privacy](https://doormatprivacy.com/), and [DMCA](https://dmcasimple.com/). https://writing.kemitchell.com/2020/05/17/Turnstile-1e1d might be a good starting explanatory blog post.

**Comment by Zwyx** [comment]
Oh it looks exactly what I was looking for! Thank you! They're a bit more complex as they include parts about account creation and content sharing, so I'll see with Kyle if we can make these optional.

Thanks again!
