### ISSUE TITLE
Is it possible to add my own License?

### ISSUE THREAD

**Issue by livrasand** [github/choosealicense.com#1206]
Do I have my own legally created license for my software? It currently appears in my repositories as "Other", is it possible to add my license so that it can be used by more users? The license is open source, and keeps the code that way, but also protects the author legally, intellectually, and economically.

You can see an example in Spanish here: https://github.com/livrasand/Kingdom-Hall-Attendant/blob/main/LICENSE.md

**Comment by nschonni** [comment]
https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license
