### ISSUE TITLE
Appendix: Legend does not correspond to colours used for same license and copyright notice

### ISSUE THREAD

**Issue by mschoettle** [github/choosealicense.com#1256]
The appendix uses different colour tones for the columns "same license" and "license and copyright notice".

However, in the legend on the bottom the same blue-ish colour tone is used for all items of those categories. It would be good to match what is used in the table.

**Comment by mlinksva** [comment]
I see the same used for both columns:

![Image](https://github.com/user-attachments/assets/71a2a23f-d54d-4acb-8f7f-aee100c0250a)

Could you clarify?

**Comment by mschoettle** [comment]
Thanks for the quick response. I should have added a screenshot in the issue right away.

<img width="692" alt="image" src="https://github.com/user-attachments/assets/6e97a61c-5387-4b19-afb7-cd33b70bf209">

See the different colour tones used in the "same license" column. 

The legend, however, looks as follows:

<img width="228" alt="image" src="https://github.com/user-attachments/assets/0dcbc0d5-884b-4167-beef-e7b0e863a94b">

Another small issue is that the same darker colour tone is used for "same license (file)" and "same license (library)" although that might be intended?

**Comment by mlinksva** [comment]
Yes the muted colours are intended for lighter versions of conditions. They should be used in the key, thanks for noticing this discrepancy!

**Comment by mlinksva** [comment]
Looks like the reason is there's a bit of special handling of conditions with `--` in their name only in the appendix table, should be in the key/legend as well. And probably elsewhere, but a start would be to make this page consistent.

https://github.com/github/choosealicense.com/blob/05070e5536dca04098bb3cc345dee859ec360ddf/appendix.md?plain=1#L45-L52

A pull request to fix would be welcome, or I'll get to it eventually.

**Comment by mschoettle** [comment]
Thanks! I will see if I can create a PR for it.

Would it be ok to also add a third colour (in a separate PR) for "same license" so that each of the three are represented by a different one?

**Comment by mlinksva** [comment]
Great!

Not sure I understand what you have in mind re adding a third colour. My intent is to have all conditions be blue, but lighter versions of conditions be a muted blue. Do you have a different scheme in mind?

**Comment by mschoettle** [comment]
Ah, I see.

The issue I faced when reviewing differences between licenses was that "same license" has three different versions and only two different colours. The difference in "same license (file)" and "same license (library)" is very minimal so that it was difficult to figure out which of the two the darker dot belonged to. That's why I propose to introduce a third muted blue.

Additionally, I think it could be helpful to add the rule label to the tooltip, and the type to the legend in order to not have to rely on colour alone.

**Comment by mlinksva** [comment]
Thanks for those PRs! Fine with me to include the rule label in the tooltip.

I think different shades for each variation would be hard to discern unless you really know what you're looking for.

**Comment by mlinksva** [comment]
After merging I noticed a small issue with each of the two PRs, left a comment and review comment. In case you're inspired to look, please do, otherwise I will eventually.

**Comment by mschoettle** [comment]
> After merging I noticed a small issue with each of the two PRs, left a comment and review comment. In case you're inspired to look, please do, otherwise I will eventually.

Thanks for merging and sorry about that. I'll have a look.

> Thanks for those PRs! Fine with me to include the rule label in the tooltip.
> 
> I think different shades for each variation would be hard to discern unless you really know what you're looking for.

Yes, that's true. Adding the rule label in the tooltip would alleviate this anyway.

Any suggestions on where to add it specifically? I tried the following:

<img width="326" alt="image" src="https://github.com/user-attachments/assets/7e95ac2a-f9b5-48f6-9cf9-935ed26c20aa">

**Comment by mlinksva** [comment]
Seems like a fine place, though two `:`s are ugly. Maybe `Same license (library) condition:` or even elide `condition` if latter isn't easy?

**Comment by mschoettle** [comment]
Great idea! It's actually easy and works with all types based on a quick look.

PR that adds the label and fixes the tooltips is coming.

For the second issue I have to look a bit more.

**Comment by mschoettle** [comment]
Closing this as all PRs are now merged. Thanks for the quick turnaround!
