### ISSUE TITLE
Add pros/cons of license components?

### ISSUE THREAD

**Issue by leahbannon** [github/choosealicense.com#128]
I would find it very helpful if we added a section describing some of the pros/cons of each license component. Or even just illustrative examples (e.g., this would likely require 20-40 extra hours of documentation work because it requires the developers to do x and y... OR ALSO this clause can discourage companies from adopting and building on your code because x). Some burdensome restrictions might seem fairly innocuous to an outsider not familiar with software development.

**Comment by afeld** [comment]
> I would find it very helpful if we added a section describing some of the pros/cons of each license component.

Not quite sure I follow... can you give a more concrete example?

> this clause can discourage companies from adopting and building on your code because x

You don't think the tooltips on the "rules" cover this?  If you have specific thoughts about which could be more clear, we'd love suggestions.

https://github.com/github/choosealicense.com/blob/edbcc1ca6aef0754565dd7717c00e62ed01df8f8/_config.yml#L5-62

**Comment by benbalter** [comment]
Closing for now. @leahbannon feel free to chime in if this is still relevant.
