### ISSUE TITLE
Add links to additional resources

### ISSUE THREAD

**Issue by jballanc** [github/choosealicense.com#13]
Not sure where it would be appropriate on the site to add these, but I think it would be helpful to add links to the Wikipedia pages for the [Bern Convention](http://en.wikipedia.org/wiki/Bern_Convention) (which makes copyright automatic) and [Work For Hire](http://en.wikipedia.org/wiki/Work_for_hire) (the situation where code you write for your job is actually copyrighted to your employer, and not you).

**Comment by jballanc** [comment]
Oh, it might also be good to link to the Open Source Initiatives [large list of OSI approved Open Source licenses](http://opensource.org/licenses/alphabetical) or even their [Open Source license FAQ](http://opensource.org/licenses).

**Comment by jpmckinney** [comment]
@jballanc There is already a link to OSI: http://choosealicense.com/about/

**Comment by jballanc** [comment]
@jpmckinney Ah, thanks! Missed that one...

**Comment by afeld** [comment]
Also http://www.tldrlegal.com/

**Comment by afeld** [comment]
A few more:
- http://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses
- http://www.codinghorror.com/blog/2007/04/pick-a-license-any-license.html
- http://www.oss-watch.ac.uk/apps/licdiff/
