### ISSUE TITLE
Page Display Issue

### ISSUE THREAD

**Issue by wjk** [github/choosealicense.com#133]
I was viewing [the license list](http://choosealicense.com/licenses/) in my Web browser when I found a bug. To reproduce the bug, do the following:
1. Scroll down to the “LGPL” section.
2. Click on “LGPL v3”
3. Click on “LGPL v2.1”
4. Watch as the text below the buttons _vanishes_. See attached screenshot.

![display bug](https://f.cloud.github.com/assets/1915951/1577050/4727fc30-5165-11e3-8b75-d8968a0e8fc0.png)

Nothing short of a page reload will make the text reappear. I’m using Safari 7.0 on OS X 10.9.0.

**Comment by haacked** [comment]
Thanks for the bug report! I've pushed a fix that should show up soon.
