### ISSUE TITLE
Should the "additional disclaimer" of the 2-clause BSD license be included?

### ISSUE THREAD

**Issue by IQAndreas** [github/choosealicense.com#136]
The [FreeBSD license](http://www.freebsd.org/copyright/freebsd-license.html) has an extra bit at the end not included in the site's version:

> The views and conclusions contained in the software and documentation are those of the authors and should not be interpreted as representing official policies, either expressed or implied, of the FreeBSD Project.

[The Wikipedia article](http://en.wikipedia.org/wiki/FreeBSD_License#2-clause_license_.28.22Simplified_BSD_License.22_or_.22FreeBSD_License.22.29) includes the disclaimer, but also brings out that some projects exclude it.

Should the disclaimer be included, or at least mentioned or the site?

**Comment by haacked** [comment]
The version of the license we have is here: http://opensource.org/licenses/BSD-2-Clause

I think the version you have is specific to the Free BSD software. I don't think it's necessary to add this.
