### ISSUE TITLE
move "Patent Grant" from "Permitted" list to "Required" list

### ISSUE THREAD

**Issue by talniv** [github/choosealicense.com#168]
Hope i'm not resurrecting a resolved issue (I looked and couldn't trace one):

If I'm not misreading the licenses, granting rights to their patents is part of what the contributors are required to do under some of the licenses and therefore belongs under the "Required" list and not the "Permitted" list. (Everybody else is then permitted to _use_ and not to _grant_ those patents)

**Comment by haacked** [comment]
@talniv Which ones are incorrect? Feel up to submitting a PR? :smile:

**Comment by benbalter** [comment]
My interpretation of the licenses properties is that it is from the code consumer's perspective, not the code publisher. If you look at [apache](http://choosealicense.com/licenses/apache/) for example, documenting changes and including copyright are actions required to be undertaken by the downstream user. 

If anything, the wording of patent-grant could be changed to be clearer. Perhaps "patent use"?
