### ISSUE TITLE
Refactor source files

### ISSUE THREAD

**Issue by XhmikosR** [github/choosealicense.com#183]
I was wondering if the source files could be refactored a little bit.

Like move the source files in /source/ and css, js, img in source/assets.

Perhaps only make the assets change. What do you think?

**Comment by XhmikosR** [comment]
You can see how things will be here  https://github.com/XhmikosR/choosealicense.com/tree/refactor-src

**Comment by benbalter** [comment]
I believe this was resolved via https://github.com/github/choosealicense.com/pull/190, but please speak up if you believe it's still worth visiting.
