### ISSUE TITLE
Add Google snippets, breadcrumbs, etc.

### ISSUE THREAD

**Issue by haacked** [github/choosealicense.com#187]
Now that we have a sitemap, we should probably optimize our search results.

![webmaster tools - structured data - http___choosealicense com_ - google chrome-518](https://f.cloud.github.com/assets/19977/2006330/04db1d04-8715-11e3-8bd5-786c5e17e679.png)

**Comment by benbalter** [comment]
@Haacked can you be more specific?

**Comment by haacked** [comment]
@benbalter you know. SEO and shit. :trollface: 

This was more a placeholder to think about it. Here's what it looks like today on Google.

![39](https://cloud.githubusercontent.com/assets/19977/3303861/6f574650-f644-11e3-8a04-17734326fc04.png)

Maybe we could have our three main licenses as headings with very brief summaries in these results.

**Comment by benbalter** [comment]
Done via https://github.com/github/choosealicense.com/pull/300 and subsequently https://github.com/benbalter/jekyll-seo-tag.
