### ISSUE TITLE
Feature request: Choose a separate content license

### ISSUE THREAD

**Issue by erlend-sh** [github/choosealicense.com#198]
Related: #175, #97 

GoogleCode lets you choose a separate license for your content. I find it very handy:

![screen shot 2014-05-05 at 13 18 35](https://cloud.githubusercontent.com/assets/583842/2877269/c85ae2f8-d447-11e3-931e-35a2128f5dc8.png)

**Comment by benbalter** [comment]
@erlend-sh this appears to be a feature request for GitHub.com's new repository screen? I'll pass your request along to the appropriate team, but will close here as this is not something that a pull request to `choosealicense.com` could resolve.

**Comment by erlend-sh** [comment]
Thanks.
