### ISSUE TITLE
agpl.txt should be agpl-v3.txt

### ISSUE THREAD

**Issue by alejandrosantana** [github/choosealicense.com#201]
Hi.

AGPL and AGPLv3 are two different licenses.
AGPLv3 is GNU license, AGPL (v1) is not.
Your agpl.txt contains the AGPLv3 license, so it should be specified with a '-v3' (like you did with gpl-v2, gpl-v3).

As stated in http://www.gnu.org/licenses/ :

```
GNU Affero General Public License (AGPL)
GNU AGPLv3 (The Affero General Public License version 1 is not a GNU license, but it was designed to serve a purpose much like the GNU AGPL's.)
```

**Comment by shiftkey** [comment]
Would you mind putting together a pull request to:
- rename the file to `v3`
- add in a new file with the v1 license

It'd be greatly appreciated!

**Comment by alejandrosantana** [comment]
Done.
Hope it's all right, not sure about the headers.

**Comment by benbalter** [comment]
Fixed via https://github.com/github/choosealicense.com/pull/202.
