### ISSUE TITLE
licenses.json being ignored breaks the API endpoint

### ISSUE THREAD

**Issue by ciarand** [github/choosealicense.com#205]
In #47 and #40 (and at least one other - 80-something?) an API endpoint for retrieving licenses (`/licenses.json`) was discussed. As of f6ce6097c6a9c6bff53c0f145939c91b6d9d3633 that page is no longer being built. Is that intentional? Is there an alternative preferred method of retrieving this information?

**Comment by benbalter** [comment]
Eeek! Nope. Great catch. That's not intentional. Are you able to submit a pull request to remove line 73 `licenses.json` from the exclude list?

**Comment by ciarand** [comment]
Yeah, will do
