### ISSUE TITLE
Cooperation with tldrlegal.com ?

### ISSUE THREAD

**Issue by gossi** [github/choosealicense.com#21]
Hey guys,

awesome service you are running there. Just a couple of weeks ago I was pointed here: http://www.tldrlegal.com
which pretty much does the same as you. Maybe you want to cooperate somehow, don't know if you already aware of this other website but I hope this hint helps in any way.

Best of luck and thanks for your work
gossi

**Comment by haacked** [comment]
Hi @gossi thanks for pointing it out the site! 

The way I see it, we're two sides of the same coin. We're focused on answering this question, "I have some source code and want to give it away. Which license do I choose."

Wherease tldrlegal seems to answer the opposite question, "This code has this license, what does it mean?".

I think both are worthwhile and important services.

If you have specific thoughts on what "cooperation" would look like, feel free to submit pull requests to this site with specific changes! I'm not sure who runs that site, but we're open to ideas!
