### ISSUE TITLE
HTTPS site does not work

### ISSUE THREAD

**Issue by QuLogic** [github/choosealicense.com#211]
Attempting to go to https://choosealicense.com fails with an invalid certificate error, because it's only for *github.com. I know the new repo page doesn't link to it, but it would be nice if it worked.

**Comment by parkr** [comment]
AFAIK, HTTPS for custom domains on GitHub Pages is not possible. You should only access this site via HTTP, never HTTPS.

**Comment by QuLogic** [comment]
Ah, I was hoping you could work some magic within GitHub infra. ;)
