### ISSUE TITLE
www.choosealicense.com doesn't resolve

### ISSUE THREAD

**Issue by dbernar1** [github/choosealicense.com#213]
Hi,

Looks like I can't go to www.choosealicense.com.

HTH!

**Comment by benbalter** [comment]
Thanks @dbernar1. Looks like it's missing a CNAME record on the subdomain. I opened an issue with our Ops team to take a closer look.

**Comment by benbalter** [comment]
Quick update: Fixed!

**Comment by dbernar1** [comment]
Thanks

## 

Dan Bernardic
My contact information is at http://gravatar.com/dbernar1
