### ISSUE TITLE
Integrate w/ GitHub, BitBucket, etc...

### ISSUE THREAD

**Issue by darkpixel** [github/choosealicense.com#219]
Have a 'sign in w/ GitHub' button, then troll through the public repos for the user and display any existing licenses along with the option to commit a license to a project.

**Comment by parkr** [comment]
Have you seen addalicense.com?

**Comment by tekkub** [comment]
This site is just a simple static site hosted using Jekyll and GitHub Pages, the things you propose are probably well outside the scope of this site as it is currently.  It's a great idea though, I second the recommendation to give addalicense.com a try.

**Comment by darkpixel** [comment]
I hadn't run in to addalicense.com--thanks.
