### ISSUE TITLE
add boost software license support

### ISSUE THREAD

**Issue by r-lyeh-archived** [github/choosealicense.com#223]
It is basically a BSD/MIT license with no required attribution in binary distributions.
License can be found in http://www.boost.org/LICENSE_1_0.txt

Comparison details here: 
http://en.wikipedia.org/wiki/Comparison_of_free_and_open-source_software_licenses

Quoting boost website:
"This license, which is very similar to the BSD license and the MIT license, should satisfy the Open Source Initiative's Open Source Definition: (i) the license permits free redistribution, (ii) the distributed code includes source code, (iii) the license permits the creation of derivative works, (iv) the license does not discriminate against persons or groups, (v) the license does not discriminate against fields of endeavor, (vi) the rights apply to all to whom the program is redistributed, (vii) the license is not specific to a product, and (viii) the license is technologically neutral (i.e., it does not [require] an explicit gesture of assent in order to establish a contract between licensor and licensee).

This license grants all rights under the owner's copyrights (as well as an implied patent license), disclaims all liability for use of the code (including intellectual property infringement liability), and requires that all subsequent copies of the code [except machine-executable object code], including partial copies and derivative works, include the license."

**Comment by odinthenerd** [comment]
why is this closed and still no boost license? no required attribution is important for embedded system with no display for example. Plus boost is in everything.

**Comment by mlinksva** [comment]
@porkybrain re-opening. Feel free to make a pull request to fix. Thanks!

**Comment by vinniefalco** [comment]
Pressing the New repository button in the GitHub UI still does not list Boost as a choice in the License dropdown.
