### ISSUE TITLE
Automaticall display permitted/forbidden inside a repo

### ISSUE THREAD

**Issue by ThaDafinser** [github/choosealicense.com#226]
Hello,

i like the small overview: http://choosealicense.com/licenses/

Cool would be to display the permitted/forbidden of a license directly inside each github project.
- scan the LICENSE.md
- display it when open the LICENSE or better directly on the Readme page?

**Comment by benbalter** [comment]
@ThaDafinser thanks for the feedback. It sounds like your suggestions is about github.com, not choosealicense.com. I'll pass your idea along to the appropriate GitHubbers, and will close here. If you have any other suggestions, don't hesitate to email support@github.com any time.
