### ISSUE TITLE
More licenses from CTAN

### ISSUE THREAD

**Issue by PanderMusubi** [github/choosealicense.com#228]
Here is a list of more licenses that could be supported. http://ctan.org/upload

**Comment by benbalter** [comment]
@arfon any strong feelings on this?

**Comment by PanderMusubi** [comment]
Mainly Latex Project Public License is the one to add

**Comment by arfon** [comment]
> @arfon any strong feelings on this?

Not really. My understanding is that the [LPPL](http://opensource.org/licenses/LPPL-1.3c) is fairly common in LaTeX land.

**Comment by PanderMusubi** [comment]
If it is common, isn't that a reason to add it?

**Comment by sieversMartin** [comment]
+1 for adding the LPPL (at least the recent version 1.3c). This is a standard license for all LaTeX extensions. More information can be found at: https://latex-project.org/lppl/

**Comment by benbalter** [comment]
Based on [our new license criteria](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license), if someone would be interested in putting together a pull request, we can add LPPL-1.3c (which I believe is what was originally approved.

```
+--------------+------------------------------------+
|                License: lppl-1.3c                 |
+--------------+------------------------------------+
| SPDX ID      | LPPL-1.3c                          |
| SPDX Name    | LaTeX Project Public License v1.3c |
| OSI approved | Yes                                |
| FSF approved | No                                 |
| OD approved  | No                                 |
+--------------+------------------------------------+
| Eligible     | Yes                                |
+--------------+------------------------------------+
```

**Comment by sieversMartin** [comment]
I initiated a pull request. The LPPL 1.3c made it into the project. When will I be able to choose it for Github projects?

**Comment by mlinksva** [comment]
@sieversMartin not soon, if (as I assume) you mean choosing from the drop-down when you add a LICENSE file to a repo. I believe the licenses there correspond to to the licenses displayed (ie hidden:false) at http://choosealicense.com/licenses/

I suspect including every license currently in this project's /_licenses (and the many more that could be added) would be taken require UI work. Just a guess on my part.

I'm closing this issue for now. Changing the display status of LPPL 1.3c within choosealicense.com would be a new issue and GitHub behavior a bit out of scope of this project.
