### ISSUE TITLE
Add the EUPL (European Union Public Licence) to list of licences to choose from.

### ISSUE THREAD

**Issue by Pixelfck** [github/choosealicense.com#229]
It would be most useful, if support for the EUPL was added. There may be some resistance to adding 'yet another licence', but this one is different from most others with regards to its legal status in the EU.

The [European Union Public Licence](https://en.wikipedia.org/wiki/European_Union_Public_Licence) (EUPL) has been created by the [European Commission](https://en.wikipedia.org/wiki/European_Commission) and is, as such, the only license which has written by an international governing body. _It has been written from the ground up for to solve the legal uncertainties_, both real and perceived, which arise from incompatibility between U.S.-law anchored licenses and enforceability under European law.

**Key features of the EUPL:**
- a _GPL compatible_ copyleft licence;
- designed explicitly for compatibility with EU law, legally binding in all EU 28 member states;
- FSF and OSI approved;
- designed to limit licence proliferation: code covered by EUPL can be mixed with specified other licenses;
- official legal translation into 22 languages;
- continuously maintained by the European Commission.

For more information on this license, please refer to: [Wikipedia Article](https://en.wikipedia.org/wiki/European_Union_Public_Licence) and the [excellent write up by OSS Watch](http://oss-watch.ac.uk/resources/eupl).

**Update:**
I just realised that this issue was missing the link to the actual license ([English](https://joinup.ec.europa.eu/system/files/EN/EUPL%20v.1.1%20-%20Licence.pdf) (pdf), [other languages](https://joinup.ec.europa.eu/software/page/eupl/licence-eupl)) and its [official webpage](https://joinup.ec.europa.eu/software/page/eupl).

**Comment by parkr** [comment]
Is the EUPL legally binding outside member countries of the European Union? If I am a German open-source developer using this license, does it protect the code from American actors (for example)? Additionally, how does the European Commission version this license? Is it compatible with GPLv2 or only v3?

Lots of unanswered questions to suss out, though I'm generally :+1: on this.

**Comment by Pixelfck** [comment]
_Disclaimer: I'm not a lawyer, so this is just my best effort explanation for this._

EUPL is designed with EU-membership states in mind. This means that it is compatible with the laws in all membership states. All the little details have been solved and the legal translation makes sure that the license has the same juridical meaning across all national legal systems in EU-member states. So, if a German developer uses this license, there will be no incompatibilities nor unexpected 'side effects' when the licensed software was somehow to come up in a court case in, for example, Spain.

Just as any other licence, EUPL does not claim to be legally compatible with the legal system of any non EU-member state. Yet, because the license includes a specific list of other licenses with which it is compatible (in other words, code licensed under EUPL can be re-licensed as part of a larger project under the listed licences), it _should_ not present a problem in the U.S. because it is compatible with GPL.

The latest version of the license is version 1.1, with version 1.2 in the making. EUPL 1.1 is compatible with GPLv2 and, by means of creative re-licensing (see [OSS Watch #Main Features of the EUPL](http://oss-watch.ac.uk/resources/eupl#main-features-of-the-eupl), third paragraph), it can also be made to be compatible with GPLv3.
EUPL 1.2 will be compatible with GPLv3 'out of the box'.

Hope this explains it a bit.

_(Also: added link to license and official web page in first post)_

**Comment by EmidioStani** [comment]
Is there any news on this ?

**Comment by Pixelfck** [comment]
If I wanted to further this issue, what kind of information would be required?

**Comment by benbalter** [comment]
I don't think EUPL is a good fit for the project for three reasons:
- It's not very widely used. A quick GitHub code search suggests about 15,000 projects use the license (compare that to even AGPL, [one of the least popular licenses on GitHub](https://github.com/blog/1964-license-usage-on-github-com), which the same search returns half a million results. For from scientific, but at least 1% of projects using the license seems like a good floor for notoriety.
- It's really confusing. I'm an attorney, I spend a lot of time working with open source licenses, and I'm having trouble following the value the license provides. Nothing in e.g., the MIT license is US specific. It's going to be really hard to explain the nuances of international license compatibility to the uninitiated, a task I'd argue is beyond our scope.
- It's a niche license. [The goal is not to be comprehensive](https://github.com/github/choosealicense.com#immediate-goals). Yes, the EU represents a large community of developers, but it's still a license targeting a specific community's unique needs (real or perceived, as the wikipedia article notes). It feels to me a lot like the NASA license, made for a specific use case, which choose license should discourage.

**Comment by Pixelfck** [comment]
The list of licences to choose from on Github is based upon what choosealicense.com supports. So, those 15,000 projects made the decision to use EUPL despite it not being offered as a choice.

On of the things the EUPL offers, that none of the other licenses included so far do, is an official legal translation into 22 languages. This is a big difference: If a dispute arises over code licensed as GPL in for example the Netherlands, a legal translation needs to be made (which of course costs money) then the other party can have its own legal translation made and the parties can start to dispute which version is more correct, if the described articles are even valid in Dutch law, which corresponding laws and regulations are applicable, etc.
If the code was licensed as EUPL, this issue does not exist, since the official legal translation has been provided by the the European Commission and the Dutch text has is available. 

The licence is meant to represent those living in the European Union and wanting to license their work with an open source copyleft licence, compatible with for example GPL. If you think the developers from the European Union are a 'niche market' I'm at a loss.

**Comment by PESchmitz** [comment]
GitHub is a very important initiative for the EU community of developers and The ECs' EUPL licence should be considered for multiple reasons:
- At the contrary of the permissive MIT etc., the EUPL is copyleft for protecting the code from proprietary appropriation. However, the EUPL is compatible with other most used copyleft licenses: if you consider the EUPL v1.2 that will be adopted soon, it is compatible with the GPL v2, GPL v3 and AGPL. Knowing that these three GNU licences are not compatible each other, the EUPL compatibility approach presents a real added value. For an attorney, this is documented in the IFOSS Law Review (IFOSSLR)
- As commented by Pixelfck, which is perhaps not an obvious advantage for an English native, the EUPL has a working value in all European languages (22 original versions). No other license has this.
- While considering the European law (and making references to the Court of Justice of the European Union), the EUPL is not a niche license like the NOSA. It is not used by the EC only, but by many other stakeholders. 
- The EUPL has a Checked conformity with European copyright law and terminology, it clarify the applicable law and venue, it is "European case law compatible” regarding the approach of warranty and liability.
  It is difficult for me to understand what could be "confusing" in the EUPL. If you have any specific point, I would be glad to clarify.

**Comment by benbalter** [comment]
I agree with the points raised. To me the question isn't whether EUPL (or any other license) is a _good_ license. That's not our role. The question is will adding it to the site demystify license usage, to make it easier for developers to quickly and easily license their code. At the point that you have to go into copyleft compatability to explain it's value, while a good license, I presently don't see it advancing the site's goals.

**Comment by EmidioStani** [comment]
I do believe that as user/developer, having a license officially translated in 22 languages, I would have more confidence in releasing my software as open source software.

**Comment by paul23-git** [comment]
@benbalter Actually from a legal point of view GPL might be incompatible to any european developper. As it explicitly states no warranty (I know you can't state that generically in the netherlands for software), and it tries to move all ownership. While in the Netherlands, as well as Germany/Belgium there is a difference between the copyright holder, and the "creator" - who has something called "personality rights". These rights allow him to prevent further publication based on ethical problems. And the law states specifically these rights can never be transfered or moved, in no possible way.

http://www.auteursrecht.nl/auteursrecht/22232/ (Dutch)

So that means any non EUPL copyleft license is actually incompatible with most of the European laws.

**Comment by benbalter** [comment]
In light of https://github.com/github/choosealicense.com/issues/273, I'd be glad to review a pull request which adds the EUPL. :smile:. Thanks all for the additional context.

**Comment by benbalter** [comment]
If anyone is still interested in adding the EUPL license, based on [our new license criteria](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license), it is eligible, if someone submits a pull request to add it.

```
+--------------+-----------------------------------+
|                License: eupl-1.1                 |
+--------------+-----------------------------------+
| SPDX ID      | EUPL-1.1                          |
| SPDX Name    | European Union Public License 1.1 |
| OSI approved | Yes                               |
| FSF approved | No                                |
| OD approved  | No                                |
+--------------+-----------------------------------+
| Eligible     | Yes                               |
+--------------+-----------------------------------+
```

**Comment by EmidioStani** [comment]
Hello I just submitted the pull request: https://github.com/github/choosealicense.com/pull/320
