### ISSUE TITLE
Recommend a public domain release in "no license"?

### ISSUE THREAD

**Issue by mindspillage** [github/choosealicense.com#230]
On the front page, someone who just doesn't want to mess with licensing because they don't care might choose "I don't want to choose a license" rather than "I want more choices"--when the closest thing to their desires and intentions might be to release everything into the public domain. To make this easy for people, the "no license" page should probably include at least a mention of or link to the public domain release options instead of just pointing them back toward open source licenses. (Maybe an added sentence at the end of the second paragraph? "If you simply want to release your material into the public domain, you should use a Public Domain Dedication to let reusers know.")

**Comment by artob** [comment]
:+1:

**Comment by benbalter** [comment]
@mindspillage would you like to submit a pull request with the proposed language to get the conversation started (and anchored)?

**Comment by parkr** [comment]
I would definitely :+1: any increase in emphasis on the Public Domain route.

**Comment by mindspillage** [comment]
@benbalter sure--and submitted now.

**Comment by tfoote** [comment]
#231 has been submitted and merged. I think this can be closed now.

**Comment by bhuga** [comment]
Yep! thanks.
