### ISSUE TITLE
Switching tabs in licenses doesn't work without Flash player

### ISSUE THREAD

**Issue by XhmikosR** [github/choosealicense.com#235]

**Comment by bkeepers** [comment]
I am not able to duplicate this. If this is still an issue for you, could you post what OS and browser you are using, and any plugins you have installed.

**Comment by XhmikosR** [comment]
I don't see how this could be magically fixed. And it's not in fact.

IE 10, no Flash Player installed.

**Comment by XhmikosR** [comment]
```
SCRIPT429: Automation server can't create object 
app.js, line 7 character 9
```

...when trying to switch tabs.

**Comment by XhmikosR** [comment]
Note that IE stops parsing JS if it encounters an error. So maybe that could should be in `try/catch` or something.

**Comment by bkeepers** [comment]
Thanks for the info. I open a pull request to address this.
