### ISSUE TITLE
when should licenses be specified in source files?

### ISSUE THREAD

**Issue by afeld** [github/choosealicense.com#243]
I don't know the answer, but would be useful to clarify as part of [an FAQ page](https://github.com/github/choosealicense.com/pull/175#discussion_r9098620).

**Comment by mbland** [comment]
FYI: I've commented on 18F/hub@703376348b0d738710da48ca7d5fcce91bf0b8b3 that I was trying to follow the advice of http://creativecommons.org/weblog/entry/27094 and the [CC Wiki](http://wiki.creativecommons.org/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F) (which appears to be broken now, but wasn't earlier this week).

**Comment by benbalter** [comment]
In short, IANYL, but but my suggestion would be to default to `LICENSE.md`, unless the particular text of the license or sidebar implementation instructions (e.g., GPL) suggest otherwise. 

Even shorter, RTFM and do whatever the license's implementation instructions (top right of each page) suggests (which defaults to `LICENSE.md`)

**Comment by mbland** [comment]
The ["How to apply" instructions](http://choosealicense.com/licenses/cc0/) appear to be silent on the issue of license notices in source file header comments, while the [CC Wiki](http://wiki.creativecommons.org/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F) (which is still, unfortunately, down as I write this) explicitly recommends them. I could probably ignore the CC Wiki advice without consequence, but given we're trying to act in good faith as members of the Open Source community and set the best example possible, it would be nice to understand the reason for the disparity. Does choosealicense.com reflect the current best practice with regard to CC0 on this issue, or does the CC Wiki?

**Comment by benbalter** [comment]
> The "How to apply" instructions appear to be silent on the issue of license notices in source file header comments, 

To clarify, in the case of cc0, it states: 

> How to apply this license
> 
> Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the CC0 into the file.

Which you are correct in reading that the recommendation is to add a file to the repo root, but not each file. 

There's a broader discussion to be had, but adding notices to each file makes sense in formats / times where it's likely that an individual file would be separated from the project. Think a punch card or pamphlet versus a GitHub repo or a book. It wouldn't make sense to put a copyright notice on each page in a book, because the pages are bound together and a copyright notice up front is sufficient.  Today with package managers, Git Repos, Gems, and the like, the chance of a single file being removed (and thus the license being forever lost and untraceable) is remote.

**Comment by afeld** [comment]
> adding notices to each file makes sense in formats / times where it's likely that an individual file would be separated from the project. Think a punch card or pamphlet versus a GitHub repo or a book. It wouldn't make sense to put a copyright notice on each page in a book, because the pages are bound together and a copyright notice up front is sufficient. Today with package managers, Git Repos, Gems, and the like, the chance of a single file being removed (and thus the license being forever lost and untraceable) is remote.

_The wisdom of Balter_ :raised_hands:

>  default to LICENSE.md, unless the particular text of the license or sidebar implementation instructions (e.g., GPL) suggest otherwise.

This is a perfect FAQ answer. Think it's worth adding to the site, if we could find a place for it?

**Comment by benbalter** [comment]
> Think it's worth adding to the site, if we could find a place for it?

To me, the instruction that I'd write would be "read the "how to add this license" on the license and do what it says" which doesn't seem worth the pixels. I'd suspect that 90% of the target audience (those unfamiliar with licensing) wouldn't think "oh should I add it to each file?", especially with explicit instructions to the contrary, but I'm not strongly opinionated if it's a significant point of confusion / in need of clarity.

**Comment by afeld** [comment]
I kinda see the issues as the power-user FAQ anyway :smirk: Thanks!

**Comment by mbland** [comment]
I agree with the punch-card/book analogy, but speaking for myself and not @afeld, I'm seeking resolution regarding the fact that the [CC Wiki](https://wiki.creativecommons.org/CC0_FAQ#May_I_apply_CC0_to_computer_software.3F_If_so.2C_is_there_a_recommended_implementation.3F) (which is live again, yay!) explicitly says this:

> **May I apply CC0 to computer software? If so, is there a recommended implementation?**
> 
> Yes, CC0 is suitable for dedicating your copyright and related rights in computer software to the public domain, to the fullest extent possible under law. Unlike CC licenses, which should not be used for software, CC0 is compatible with many software licenses, including the GPL. However, CC0 has not been approved by the Open Source Initiative and does not license or otherwise affect any patent rights you may have. You may want to consider using an approved OSI license that does so instead of CC0, such as GPL 3.0 or Apache 2.0.
> 
> CC and the Free Software Foundation suggest that if you choose to apply CC0 to software, you include the following notice at the top of each file:

```
<PROGRAM NAME> - <DESCRIPTION>

Written in <YEAR> by <AUTHOR NAME> <AUTHOR E-MAIL ADDRESS>

[other author/contributor lines as appropriate]

To the extent possible under law, the author(s) have dedicated all copyright and related
and neighboring rights to this software to the public domain worldwide. This software is
distributed without any warranty.

You should have received a copy of the CC0 Public Domain Dedication along with this
software. If not, see <http://creativecommons.org/publicdomain/zero/1.0/>.
```

> It is also recommended that you include a file called COPYING (or COPYING.txt) containing the CC0 legalcode as plain text.

Again, I'm happy to cut 'n run with the LICENSE.md model, as it makes perfect sense to me. However, my presumption was that the maintainers of chooseyourlicense.com were sufficiently affiliated with the CC and FSF folks that such a discrepancy wouldn't arise, or would be ironed out between the parties.

**Comment by strugee** [comment]
> To me, the instruction that I'd write would be "read the "how to add this license" on the license and do what it says" which doesn't seem worth the pixels.

Perhaps we could link to these "how to use this license" documents from the licenses list and/or license pages, similar to how we currently link to the raw license source? The FSF, at least, maintains detailed HOWTOs for how to apply each of their licenses.
