### ISSUE TITLE
Principal difference between BSD and MIT licenses is not shown

### ISSUE THREAD

**Issue by annulen** [github/choosealicense.com#257]
IANAL, but common interpretation of MIT license is that it does not require you to redistribute license test of original project when you distribute it in binary form (e.g., as a part of derivative work). On the other hand, BSD licenses include specific clause for this case: 

> Redistributions in binary form must reproduce the above copyright notice,  this list of conditions and the following disclaimer in the documentation  and/or other materials provided with the distribution.

For example, if guys from Microsoft use your library in binary distribution of Windows
- for BSD-licensed library, they have to include full license text, including your copyright
- for MIT-licensed library, they can just include binary code and don't mention that they have used you work. Of couse they have to retain your copyrights and licensing in source code, but most of people won't get access to them :)

LLVM project uses BSD license for LLVM and Clang projects, but they explicitly license runtime components under MIT because of this binary redistribution code:

> http://llvm.org/docs/DeveloperPolicy.html#license
> In addition to the UIUC license, the runtime library components of LLVM (compiler_rt, libc++, and libclc) are also licensed under the MIT License, which does not contain the binary redistribution clause. As a user of these runtime libraries, it means that you can choose to use the code under either license (and thus don’t need the binary redistribution clause), and as a contributor to the code that you agree that any contributions to these libraries be licensed under both licenses. We feel that this is important for runtime libraries, because they are implicitly linked into applications and therefore should not subject those applications to the binary redistribution clause.

Also, IMHO BSD license shoud be mentioned on main page as an alternative to MIT, because for many developers this "attribution" thing is somewhat important.

**Comment by rugk** [comment]
I have researched a bit about this topic and what I found out is that the part for compiled software in the BSD license is unnecessary. This was also the reason why the [ISC license](https://en.wikipedia.org/wiki/ISC_license) was created, which is a modified BSD 2-clause license.

The reason for that is that a revision of the [Berne convention](https://en.wikipedia.org/wiki/Berne_Convention) in 1977 contains a part which expands the protection of the original work to translations too, which accords with the compilation of source code.

This is the [Berne convention, article 2](http://zvon.org/law/r/bern.html#p~2), paragraph 3:

> Translations, adaptations, arrangements of music and other alterations of a literary or artistic work shall be protected as original works without prejudice to the copyright in the original work.

Sources: 
- https://de.wikipedia.org/w/index.php?title=ISC-Lizenz&oldid=132440390 (German; permanent link)
- https://programmers.stackexchange.com/questions/157476/isc-license-advice

**Comment by mlinksva** [comment]
The difference is not so clear. MIT:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

This does not exclude binary distributions. At most, it is unclear whether they are included. It's best practice to include MIT notices with binary distributions in any case, eg as discussed at https://www.quora.com/Does-the-MIT-license-require-attribution-in-a-binary-only-distribution

The difference is that BSD licenses (excluding 0BSD) explicitly require notices with binary distributions.

This is not a big enough difference to call out, let alone on the main page.

Thanks for raising (months ago, I realize) the issue!
