### ISSUE TITLE
Add the PostgreSQL license

### ISSUE THREAD

**Issue by wulczer** [github/choosealicense.com#259]
A lot of Postgres extensions are licensed with the PostgreSQL license, which is similar to the BSD and MIT licenses:

http://www.postgresql.org/about/licence/

http://opensource.org/licenses/postgresql

**Comment by strugee** [comment]
If it's similar to the MIT and BSD licenses, why do we need it? Remember, ChooseALicense is about quality, not quantity.

**Comment by wulczer** [comment]
For example, I mainain a few Postgres extensions, for which the license is "same as PostgreSQL", which means the PostgreSQL license. It's a natural fit for code that's written explicitly for Postgres and might in the future end up in the core distribution.

I guess people could always dual-license, MIT and PostgreSQL.

**Comment by strugee** [comment]
"PostgreSQL extension" seems like a pretty small niche.

I don't mean to sound rude. Honestly. I just don't see this on choosealicense.com.

**Comment by benbalter** [comment]
Two questions come to mind for me:
1. Could I license a PostgreSQL extension under MIT, BSD, or a similar license?
2. Would I ever use this license for something other than a Postgres-related project? Should I?

**Comment by benbalter** [comment]
Based on our [new license criteria](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license), the Postgres license can be added, if anyone is willing to submit a pull request to do so.

```
+--------------+--------------------+
|        License: postgresql        |
+--------------+--------------------+
| SPDX ID      | PostgreSQL         |
| SPDX Name    | PostgreSQL License |
| OSI approved | Yes                |
| FSF approved | No                 |
| OD approved  | No                 |
+--------------+--------------------+
| Eligible     | Yes                |
+--------------+--------------------+
```

**Comment by dlecan** [comment]
See https://github.com/github/choosealicense.com/pull/524
