### ISSUE TITLE
Licenses for documentations

### ISSUE THREAD

**Issue by ghost** [github/choosealicense.com#261]
Developing a framework or a library implicitly implies to deliver a documentation and many well known frameworks like Qt uses that kind of licenses to cover their documentions.

By going from pages to pages on http://choosealicense.com, i've noticed that it only covers software licenses. I think that i'd be be interesting to also cover documentation licenses like GNU FDL.

Here is a resource i've found on the web that gives a list of available documentation licenses: https://dreamsongs.com/IHE/IHE-50.html

**Comment by benbalter** [comment]
Most licenses explicitly include documentation (e.g., MIT says "and associated documentation files", Apache says "generated documentation" and "documentation source"). Choosealicense is about making it easier to license software (which includes documentation). I believe for most use cases having a separate documentation license may be over-engineering the problem and will be confusing for folks new to licensing.

**Comment by ghost** [comment]
Yes, I've noticed that some licenses like your examples are giving protection to the documentation files, but some like the GNU GPL (any revision) doesn't cover documentation files.

I thought that explicitly covering documentation licenses on http://choosealicense.com could be interesting for developers, not folks ones as you said and also explain them the purpose of that kind of licenses.

**Comment by strugee** [comment]
Perhaps we can find a compromise - e.g., we could link to the GNU FDL in the GPL explanation text. Something along the lines of, "unlike many other licenses, the GPL does not cover documentation. Consider licensing your documentation under the GNU FDL, which licenses documentation in a manner similar to how the GPL licenses software."

**Comment by ghost** [comment]
Yep, it sounds fine to me. No need to create new pages dedicated to documentation licenses but the information is given to the developer.

**Comment by mlinksva** [comment]
Addressed with #359
