### ISSUE TITLE
https://www.choosealicense.com is broken

### ISSUE THREAD

**Issue by stuartpb** [github/choosealicense.com#265]
The certificate that gets served when requesting choosealicense.com over HTTPS is for github.com, not choosealicense.com.

**Comment by parkr** [comment]
@stuartpb HTTPS does not work for custom domains over GitHub Pages. Did you expect it to work based on some documentation? If so, please submit a fix for the documentation. Otherwise, expect HTTP-only for CNAME'd GitHub Pages websites.
