### ISSUE TITLE
Please add The MirOS Licence

### ISSUE THREAD

**Issue by mirabilos** [github/choosealicense.com#268]
Hi,

what do I have to do in order to get another OSS licence
included into your repository initialisation licence chooser?
It’s a BSD/MIT-ish licence, and one of your users asked me
just now why it was not selectable.

Scope:      works under Copyright law (code, data, docs, media, …)
Long name:  The MirOS Licence
Short name 1:   MirBSD
Short name 2:   MirOS
Reference URI:  https://www.mirbsd.org/MirOS-Licence.htm

SPDX long:  MirOS Licence
SPDX short: MirOS
(note that the long name and the licence body on the SPDX
site do not match the reference; the body text on the OSI
website is similarily misformatted) I have two plain-text
reference versions (ASCII and UTF-8) as well:
• https://www.mirbsd.org/MirOS-Licence
• https://www.mirbsd.org/MirOS-Licence.asc
Do note that only the first part (C-style comment) is the
actual licence body.

Thanks in advance,
//mirabilos – Leader, The MirOS Project

**Comment by waldyrious** [comment]
That's a nice one, @mirabilos. Out of curiosity, can you explain how it differs from [MIT/Expat](http://choosealicense.com/licenses/mit/), [Simplified BSD](http://choosealicense.com/licenses/bsd-2-clause/) and [ISC](http://choosealicense.com/licenses/isc/), and why those were deemed (if indeed that was the case) inadequate?

**Comment by mirabilos** [comment]
@waldyrious the basic idea was to get the disclaimer worded so that it more closely resembles the other EU licences, in order to not be possibly invalidated due to too broad dis-claims.

Then, of course, there is referring to “work” (extending scope to all there is under copyright law) instead of “software”, as I wish to use this for all my works I publish (graphics and photos too, and I even have written fanfiction and published it under this licence, with an additional disclaimer for that genre of course, but this being the actual licence), and for some, the distinction between code, data, docs and media is very vague, and I like using the same licence consistently for all content.

Then there’s stylistic issues, such as enumerating all the things you can do (e.g. the various ISC licence flavours fail at some of them, “and/or” and/or “with or without fee” missing). I even had a lawyer from the ifrOSS look at it (he said “lgtm” but they focus on copyleft licences so that’s more of a quick look than a full review).

It’s clearly a minority licence, but one I strongly recommend to people alongside MIT (which is my fallback) especially due to it not being limited to software.

I am only submitting it here due to actual user request (i.e. someone approached me in person and said they wanted to select it in a new github repo but couldn’t find it).

Oh, and it has very recently gotten a German translation (in case that matters); the licence itself is in use since 2003, with the text being finalised in 2004, and previously optional advertising clauses being later deprecated and eventually removed.

**Comment by waldyrious** [comment]
Thanks for the very informative answer. If this becomes more prevalent, I'll definitely consider switching to it rather than ISC which is my preference at the moment. For non-software work, I tend to prefer Creative Commons licenses due to their widespread recognition and easy understanding of the terms.

**Comment by mirabilos** [comment]
@waldyrious I understand. It’s no problem – we just have different weights to “use a homogenous licence” vs. “wide-spread” (though I recently looked at CC-BY and found it pretty copyleft-y; plus, in my OSS fields, CC-\* is actually the minority).

But this issue is not about getting everyone to switch to it (though I’d not say no to that either ☺) but to get it listed in the “new repo, which README and licence do you want?” chooser of github. A support person mailed me back asking to open that as issue on this repo.

**Comment by benbalter** [comment]
Based on [our new license criteria](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license), MirOS meets two of the three requirements, in that it has an SPDX identifier and is OSI (and OD) approved, but [a GitHub code search](https://github.com/search?q=miros+filename%3ALICENSE&type=Code) shows fewer than 200 projects using the license, and thus I don't believe it meets the adoption requirements. Please feel free to comment if that changes, or if another search better represents its adoption.

**Comment by mirabilos** [comment]
Ben Balter dixit:

> search](https://github.com/search?q=miros+filename%3ALICENSE&type=Code)

This is a BSD-style licence, i.e. it is reproduced in each individual
file (more generally, work) it applies to; BSDish projects usually do
_not_ carry a separate LICENCE file, so you will have to search for a
string, such as…

```
Provided that these terms and disclaimer and all copyright notices
```

… which is AFAICT unique to The MirOS Licence, in all files, in every
project, to find projects using them.

That being said, I’d be (positively) surprised if we had 200 projects
using it already. But this is a hen/egg problem… if it’s not offered,
nobody will choose it, unless they’re merely importing a project from
someplace else into github. As such I do not think that metric is all
that worth… but YMMV, ofc.

Thanks anyway,
//mirabilos
