### ISSUE TITLE
LGPL's required column contains confusing "library usage"

### ISSUE THREAD

**Issue by strugee** [github/choosealicense.com#270]
The hover-text makes it clear, but just looking at the column, it seems like you're required to use the LGPL'd work as a library.

**Comment by wking** [comment]
Fixed by #343?  Although [there's a still work to do around this](https://github.com/github/choosealicense.com/pull/343#issuecomment-180033612), so we might want to leave this issue open until that is completed.

**Comment by mlinksva** [comment]
This specific issue fixed by #343. Related development in #344.
