### ISSUE TITLE
MIT X11 version forbidden to use trademark

### ISSUE THREAD

**Issue by Swizz** [github/choosealicense.com#271]
As the Apache License, The X11 version have the following clause :

```
Except as contained in this notice, the name of the copyright holders shall not
be used in advertising or otherwise to promote the sale, use or other dealings
in this Software without prior written authorization from the copyright holders.
```

**Comment by benbalter** [comment]
@Swizz540 can you elaborate a bit further on your observation / what you're proposing?

**Comment by Swizz** [comment]
@benbalter Oh so sorry, I am not finished my Issue.

Many people don't know the difference between the X11 and the Expat version of the MIT License.

Like the BSD license, can you add both versions of the MIT to show the "Using Trademark Forbidden" for the X11 version.

**Comment by mlinksva** [comment]
I believe @Swizz you're proposing that we add http://spdx.org/licenses/X11.html

It might marginally qualify to be added, as it is on https://www.gnu.org/licenses/license-list.en.html and 
https://github.com/search?utf8=%E2%9C%93&q=%22shall+not+be+used+in+advertising%22+filename%3ALICENSE&type=Code&ref=searchresults finds > 1k uses, but quick inspection shows many of those uses are variations, which the license text basically screams for by including references to the X Consortium in the body. I suspect if OSI ever considered and approved the license they might be tempted to put it in the non-reusable category, see https://opensource.org/licenses/category which we should probably have rule out for inclusion in this project. (Though we have added LPPL-1.3c in #319 -- I think OSI is wrong about their categorization of that one.)
