### ISSUE TITLE
Distinguish "License and copyright notice" between code and ui/documentation

### ISSUE THREAD

**Issue by tthiery** [github/choosealicense.com#272]
The statement "License and copyright **notice**" has a tooltip "Include a copy of the license and copyright notice with the **code**.". This tooltip targets explicitly the source code. Additional information whether the license need to be mentioned to the end user would be valuable!

**Comment by mlinksva** [comment]
Thanks for reporting this long ago. #469 changes 'code' to 'software' in the tooltip you note. The notice condition of most open source licenses applies to any distribution, not only source code. Probably the distinction you're suggesting calling out is based on the interactive user interface language in GPL-2/3.0. I don't think this should be called out as an additional condition given the granularity and understandability choosealicense.com is going for. GPL-2/3.0 is a little more prescriptive about how to provide notices in some cases, but readers shouldn't think that other licenses don't require similar, and they are often implemented in the same manner, eg see chrome://credits/ (Chrome) or about:license (Firefox).

**Comment by tthiery** [comment]
Thanks for the clarification and your work in general!
