### ISSUE TITLE
Proposal: "Hidden" licenses

### ISSUE THREAD

**Issue by benbalter** [github/choosealicense.com#273]
I'd like to propose that we introduce a new "class" of licenses to choosealicense.com which I'm calling "hidden licenses". Hidden licenses would act just like any other license, except they would not appear on http://choosealicense.com/licenses/.

We get **a lot** of requests to add licenses representing the extremely long tail of license choices out their in the open source community. See https://github.com/github/choosealicense.com/pull/248, https://github.com/github/choosealicense.com/pull/216, https://github.com/github/choosealicense.com/pull/200, https://github.com/github/choosealicense.com/pull/130, https://github.com/github/choosealicense.com/pull/86, https://github.com/github/choosealicense.com/pull/250, https://github.com/github/choosealicense.com/pull/266, https://github.com/github/choosealicense.com/pull/210, https://github.com/github/choosealicense.com/pull/195, https://github.com/github/choosealicense.com/pull/135, https://github.com/github/choosealicense.com/pull/95, https://github.com/github/choosealicense.com/pull/15, and https://github.com/github/choosealicense.com/pull/17 to name a few.

Traditionally, we've been hesitant to add licenses beyond the dozen or so most popular licenses. [The goal of choosealiense.com](https://github.com/github/choosealicense.com#immediate-goals) is not to be comprehensive. Instead, it's designed to _simplify_ the process of choosing a license. That's why the homepage, the primary route, has just three licenses, with blurbs that may not 100% reflect every nuance of the licenses' differences. 

Adding more licenses to the mental decision tree a user makes complicates the process and is antithetical to the site's goals. Decision paralysis is a real thing. see https://github.com/github/choosealicense.com/issues/229#issuecomment-105289767 for an example of this in action.

That said, I think there's a case for a third class of licenses (beyond featured and not-featured) that have received a certain base-level of notoriety such that a typical developer is likely to come across a licensed projects in their day-to-day interactions, but aren't widely used enough to warrant being presented as an option.

There's a few reasons for this:
- If a developer comes across a licensed project they can search for or be linked to the license page on choosealicense.com to better understand what they can and can't do under the license.
- It can provide a softer onramp for new licenses. Rather than spending time in discussions that almost always seem to devolve into the relative merits of a given license (which is not what the decision turns on), licenses with a certain numeric threshold (say 10k projects on GitHub via code search), can be added as a hidden license where the description and attributes can begin to be curated.
- While I don't believe these hidden licenses belong in the license dropdown on GitHub.com (again, the idea is that they shouldn't be presented as options to avoid overwhelming developers), they could be added to the corpous of known licenses as detected via the License API.

Practically, it'd be a matter of adding a `hidden: true` field to the YAML front-matter of a hidden license to exclude it from the license list. It'd still appear in the sitemap, would be indexed by Google, and would be linkable by users from external sites. 

I'd suggest we come up with an objective standard to determine a base level of notoriety (10k projects via GitHub code search being the example above), apply that standard to open pull requests, and then begin accepting new licenses. Thoughts? 

/cc @github/open-source

**Comment by MikeMcQuaid** [comment]
Seems like a good idea to me and well thought through :+1:

**Comment by arfon** [comment]
Sounds good to me. @benbalter - would this mean the license API could also detect (and return) these hidden licenses when present?

**Comment by benbalter** [comment]
> would this mean the license API could also detect (and return) these hidden licenses when present?

Yes sir.

**Comment by arfon** [comment]
> Yes sir.

THEN LET'S DO THIS! :rocket:

**Comment by benbalter** [comment]
Implemented via https://github.com/github/choosealicense.com/pull/274.
