### ISSUE TITLE
Request to add Clear BSD license

### ISSUE THREAD

**Issue by amateurhuman** [github/choosealicense.com#275]
Received a request to add the Clear BSD license to the license picker. Since I have no idea where to start with that, and I assume we'd add it to choosealicense if it's in the picker, I am dropping the issue here. Entirely okay with not including it, just want some thoughts on why we wouldn't.

The [3-clause Clear BSD](http://spdx.org/licenses/BSD-3-Clause-Clear.html) reads:

> Copyright (c) [xxxx]-[xxxx] [Owner Organization] 
> All rights reserved.
> 
> Redistribution and use in source and binary forms, with or without modification, are permitted (subject to the limitations in the disclaimer below) provided that the following conditions are met:
> - Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
> - Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
> - Neither the name of [Owner Organization] nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
> 
> NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

The only differences in the `Clear BSD` from the `BSD 3-clause "New" or "Revised" License` (which we already support) are the additions of the parenthetical in the opening paragraph:

> (subject to the limitations in the disclaimer below)

And the addition of the first sentence in the closing paragraph:

> NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY THIS LICENSE. 

Adding it seems like it would just be confusing to the novice end-user, so I am not certain there's a ton of value in it but I am by no means qualified to make that call.

Thoughts?

**Comment by benbalter** [comment]
It looks like [there are 1,000 projects using the license](https://github.com/search?utf8=%E2%9C%93&q=%22NO+EXPRESS+OR+IMPLIED+LICENSES+TO+ANY+PARTY%27S+PATENT+RIGHTS+ARE+GRANTED+BY+THIS+LICENSE.%22&type=Code&ref=searchresults). 

If this license is an evolved version of the three clause BSD, ideally we'd replace it as the default, but I don't know that it's there yet.

With https://github.com/github/choosealicense.com/issues/273, I'd be glad to add this as a hidden license, which wouldn't appear on the list of recomendations, but would still be listed on the site (and is an onramp to being listed).

**Comment by grantr** [comment]
Just got this request at the Linuxcon booth from a Qualcomm developer (and speaker). He said it was "commonly used by corporations".

**Comment by benbalter** [comment]
Self-assigned, and will attempt to add as a hidden license next free cycle I get, but if anyone would like to submit a pull request in the interim to kick things off, :metal:.
