### ISSUE TITLE
Should choosealicense.com include non-OSI approved licenses?

### ISSUE THREAD

**Issue by benbalter** [github/choosealicense.com#281]
An issue that came up in https://github.com/github/choosealicense.com/pull/278, should choosealicense.com include non-OSI approved licenses? We have a check as part of the CI, that requires the license be OSI-approved, to at least provide a minimum floor for the long-tail of potential licenses. 

A few licenses that this would affect:
- Clear BSD
- WTFPL
- Unlicense
- All CC Licenses

The idea would be that if a license isn't OSI approved, we'd ask the submitter to submit it to OSI first, for review, so that we wouldn't be the one deciding the merits of a given license, again, to give us a minimum floor that fends off the long-tail of potential licenses.

/cc @github/open-source, @github/choosealicense-com

**Comment by artob** [comment]
@benbalter As we've [discussed previously](https://github.com/project-open-data/project-open-data.github.io/pull/135#issuecomment-23608330), the OSI are unlikely to concern themselves with public domain dedications, so both CC0 and the Unlicense are orthogonal to OSI interests. Can't speak for the other licenses as such.

**Comment by benbalter** [comment]
> As we've discussed previously,

Forgot about that discussion. I think you're right, but will leave this open for others to weigh in.

**Comment by bkeepers** [comment]
Will there be any criteria for accepting a license if it's not restricted to OSI-approved license?

**Comment by benbalter** [comment]
Revised things a bit in 8c63910 to formalize the whitelist that previously existed for CC0 and the unlicense. This mirrors linguist's approach, which maintains has a license test and maintains a whitelist of approved licenses. I think having tests fail by default for non-OSI approved licenses, and requiring a discussion about whitelisting the license should be healthy for the project and a good compromise.

> Will there be any criteria for accepting a license if it's not restricted to OSI-approved license?

I'll open an issue to document this better. Traditionally, there's been some notoriety requirement, as defined by usage detected by a simple GitHub code search. I'd say going forward there should be a rebuttable presumption that the license should be OSI approved, which is roughly what we'd been doing by allowing exceptions for unlicense and cc0.
