### ISSUE TITLE
cant run the bootstrap

### ISSUE THREAD

**Issue by oddcoder** [github/choosealicense.com#284]
when I run ./bootstrap I get this error
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /var/lib/gems/1.9.1 directory.

and when I sudo it I get also another error
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.

[!] There was an error parsing `Gemfile`: No such file or directory - .ruby-version. Bundler cannot continue.

 #  from /home/oddcoder/choosealicense.com/Gemfile:2
 #  -------------------------------------------
 #  source "https://rubygems.org"

>  ruby File.read(".ruby-version").strip
>  #  
>  #  -------------------------------------------

**Comment by bkeepers** [comment]
I'm not able to duplicate this. Does this help fix it for you? http://flummox-engineering.blogspot.com.au/2014/05/you-dont-have-write-permissions-for.html
