### ISSUE TITLE
ISC license incorrectly recommends email

### ISSUE THREAD

**Issue by christianbundy** [github/choosealicense.com#285]
Last week I noticed that the ISC license contains the following line, which was added in f89201c7f4e01e5addf2f63302cfc61132ce962d (which was merged in #50):

```
Copyright (c) [year], [fullname] <[email]>
```

The value of the `how` key also contains: "...[email] is optional but recommended.", which I've been unable to substantiate anywhere. Seeing as how an email address is never recommended in any other license (although it's explicitly required by both the OFL 1.1 and the WTFPL), is there any reason not to remove this? I'd be more than happy to put together a pull request.

Copies of the canonical ISC license are available through the [ISC](http://www.isc.org/downloads/software-support-policy/isc-license/) and the [OSI](http://opensource.org/licenses/isc-license.txt).

**Comment by waldyrious** [comment]
Just a quick note: you linked twice to the OSI. You probably wanted the first link to point here: http://www.isc.org/downloads/software-support-policy/isc-license/

**Comment by benbalter** [comment]
What's the downside of including the email?

**Comment by christianbundy** [comment]
@waldyrious thanks, I didn't catch that – my link should be fixed now.

@benbalter I think that email addresses can be a good step toward establishing provenance and non-repudiation of the license, but for the sake of consistency I don't think that the ISC should be singled out to be improved with arbitrary modifications (regardless of whether or not they're beneficial).

If the goal of this project is to provide canonical licenses with canonical usage instructions, I think that's what should be done unilaterally and this issue should remain open until 7cb14ab is merged. If the goal of this project is to provide modified licenses with @juanfra684's recommended usage instructions, I think this issue (and #286) should both be closed.

This only came up because we were diffing licenses in an OSI mailing list, and I was confused as to why this project had a different version of the ISC than the OSI had recorded. Not a huge deal, just a bit confusing.

Thanks for jumping on this so quickly, have a kickass day!

**Comment by juanfra684** [comment]
I don't remember the source of my words. Anyway, I didn't modified the license, that sentence is part of the "how" section.

Feel free to remove "but recommended" because we have not the source with the recommendation. 

I'm against the remove of "<<email address>> is optional" because that format (year/name/email) is widely used by individuals.

**Comment by christianbundy** [comment]
Thanks @juanfra684. Here's a diff of the license text between the OSI's version and your version:

``` diff
- Copyright (c) 4-digit year, Company or Person's Name
+ Copyright (c) [year], [fullname] <[email]>

Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted, provided that the above
copyright notice and this permission notice appear in all copies.

THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
```

> I'm against the remove of "<> is optional" because that format (year/name/email) is widely used by individuals.

This policy should be applied unilaterally or not at all – I don't see any reason why the ISC license in particular is subject to arbitrary modifications, or why optional fields should be added. Please don't take this the wrong way, this isn't a personal attack on you or your contribution to this project, this is an attempt to fix an inconsistency in how the ISC license is being distributed.

**Comment by juanfra684** [comment]
I'm not taking the bug report like a personal attack.

In my opinion, someone should to add the email field to every license in the website. It is optional, more widely used than the canonical form and doesn't break the license. Even the GPL license recommends to include the contact info.

The ISC license derives from the original BSD license, which predates the use of the e-mail as a formal communication method. And probably the lawyers of the University of California didn't wanted to receive legal requests from AT&T in electronic form.

**Comment by waldyrious** [comment]
FWIW, I agree that including the email would be an improvement, but shouldn't be present in a single license as an exception. I think removing the email from the ISC licence is a sensible move, in the interest of consistency and matching other templates in canonical locations.

A separate PR adding an optional email field to all licenses and/or a note in their "how" fields, is a proposal I'd be inclined to support.
