### ISSUE TITLE
Is the "category" property redundant with the "variant" one?

### ISSUE THREAD

**Issue by waldyrious** [github/choosealicense.com#287]
Judging by the descriptions in [_data/meta.yml](../blob/gh-pages/_data/meta.yml), any license with a `category` property automatically qualifies for `variant: true`. That means that there's a redundant property which is maintained manually. I submit that the `variant` property should be removed, and any use of it replaced by whether `category` is set or not.

**Comment by benbalter** [comment]
The variant property is used to delineate between the primary license within a category and its variants (e.g., in the GPL category, v2 is the primary license, and v3 and AGPL are variants). Open to suggestions if there's a better way. Thought about "primary" but thought that would be confusing with "featured".

**Comment by waldyrious** [comment]
Oh. This meaning of variant you describe is actually more in line with what the name suggests. I guess meta.yml needs to be updated accordingly, then. Coupled with #288, this would make the property names more intuitive.

Alternatively, and similarly to #291, we could have a "family-default" property, instead of having two separate properties "primary" and "variant".

**Comment by mlinksva** [comment]
I'm not a huge fan of 'family' or 'variant'. To avoid not 100% correct characterizations I'd go with 'grouping' and 'grouping-default', as the purpose is really to group and control grouping display for choosealicense.com/licenses. But I don't think it's worth fiddling with these property names at this time, so closing. If anyone really wishes to make a pull request along above lines, feel free.
