### ISSUE TITLE
Rename the "Public Domain Dedication" value for the "category" property

### ISSUE THREAD

**Issue by waldyrious** [github/choosealicense.com#289]
The other values are much simpler:

```
~/choosealicense.com/_licenses$ grep -Poh "(?<=category: ).+" * | sort | uniq -c
      3 BSD
      3 GPL
      2 LGPL
      2 Public Domain Dedication
```

Maybe "PD" or simply "Public domain" would fit the remaining entries better.

**Comment by benbalter** [comment]
I'd be fine with "public domain". The "dedication" was added when it was just the unlicense to show that it wasn't really a license, but as a family, think "public domain" is sufficient.

**Comment by waldyrious** [comment]
Cool. I'll send a PR as soon as #293 is wrapped up, unless someone gets to it first :)
