### ISSUE TITLE
Collapse license families on the licenses page.

### ISSUE THREAD

**Issue by haacked** [github/choosealicense.com#29]
The original goal for the [/licenses](http://choosealicense.com/licenses/) list was to group licenses into license families and not list every single one. For example, rather than an entry for BSD 2-clause and BSD 3 clause, we'd just have BSD and in the description we'd offer links to both of them.

However, the list of licenses in the `/licenses` folder populates the dropdown list on github.com. The label shown in the list comes from the `title:` field in the license front matter.

So we need different titles for github.com than we show in the /licenses page.

So I propose we add two new fields:

```
family-title:
hide-from-licenses-list: (true|false)
```

The logic is simple. If `family-title:` is specified, we use that. Otherwise we fallback to `title:`.

If `hide-from-licenses-list` is true, we do not list that license on the `licenses` page. It defaults to false.

In general, I don't like "negative" properties, but this invokes the least amount of change as we only need to hide the redundant licenses. I'm open to doing the extra work and making the property be positive: `show-in-licenses:` if we think that's better.

Example changes:

```
title: BSD 2-clause License
family-title: BSD
```

```
title: BSD 3-clause License
hide-from-licenses: true
```

Thoughts?

**Comment by nacin** [comment]
This makes sense, but what about any differences between individual licenses within a family? While the differences between new BSD and simplified BSD are fairly minor, the differences between GPLv2 and GPLv3 are critical. Some practical examples include: v2 and v3 code is not combinable, only GPLv3 is compatible with Apache 2, Linux (and many other high-profile projects) [is GPLv2](http://en.wikipedia.org/wiki/Linux_kernel#GPL_version_3), and the optional (and default) "or any later version" clause. To solve this for GPL at least, I think the GPL probably needs a `family-description:` that goes into this a little. And in general, maybe start to think about inter-license compatibility for choosealicense.com.

**Comment by haacked** [comment]
Well one thought we've toyed with was adding a GPL disambiguation page. But writing that is beyond what I have the energy for today. :weary: 

If someone were to take that on in an impartial (as impartial as one can be) manner, that'd be ideal. Then we could just link to that. I don't like adding another step before you get to the page, but I kind of think it makes sense in the case of GPL given all these.

**Comment by nacin** [comment]
That sounds like an excellent idea. This also makes me think about GPL versus Affero GPL, which probably needs a big fat red warning label. (The currently available license property rules do not do it justice.)

**Comment by haacked** [comment]
@benbalter: have you had time to think about this? :smiley_cat:

**Comment by benbalter** [comment]
Fixed via https://github.com/github/choosealicense.com/issues/111.
