### ISSUE TITLE
relationship between "tab-slug" and "redirect_from" properties, and the filename is unclear / inconsistent.

### ISSUE THREAD

**Issue by waldyrious** [github/choosealicense.com#290]
They should be harmonized / clarified, and possibly merged (i.e. using the filename instead of the tab-slug property, or renaming the files according to the tab-slug, or something else along those lines).

Here's a table of the current values, to allow a better overview:

| filename | tab-slug | redirect_from | category |
| --- | --- | --- | --- |
| agpl-3.0 | agpl-v3 | agpl | gpl |
| apache-2.0 |  | apache |  |
| artistic-2.0 |  | artistic |  |
| bsd-2-clause | bsd | bsd | bsd |
| bsd-3-clause | bsd-3 |  | bsd |
| cc0-1.0 | cc0 | cc0 | pd* |
| epl-1.0 |  | eclipse |  |
| gpl-2.0 | gpl-v2 | gpl-v2 | gpl |
| gpl-3.0 | gpl-v3 | gpl-v3 | gpl |
| isc | isc |  | bsd |
| lgpl-2.1 | lgpl-v2_1 | lgpl-v2.1 | lgpl |
| lgpl-3.0 | lgpl-v3 | lgpl-v3 | lgpl |
| mpl-2.0 |  | mozilla |  |
| ofl-1.1 |  | ofl |  |
| unlicense | unlicense |  | pd* |

\* - shortened from "Public Domain Dedication" to make the table shorter. See #289 for a proposal to change this.

---

Looking at the "name" and nickname properties, one can also notice a trend:

Additionally, it seems that where the nickname is the same as the tab-slug or redirect_from, it is not included, the exception being the Apache license. So either the nickname should be removed in that case, or added to all licenses regardless of coinciding with the tab-slug/redirect_from version.

| nickname | title |
| --- | --- |
| GNU Affero GPL v3.0 | GNU Affero General Public License v3.0 |
| Apache | Apache License 2.0 |
|  | Artistic License 2.0 |
| Simplified BSD | BSD 2-clause "Simplified" License |
| New BSD | BSD 3-clause "New" or "Revised" License |
| CC0 1.0 Universal | Creative Commons Zero v1.0 Universal |
|  | Eclipse Public License 1.0 |
| GNU GPL v2.0 | GNU General Public License v2.0 |
| GNU GPL v3.0 | GNU General Public License v3.0 |
|  | ISC License |
| GNU LGPL v2.1 | GNU Lesser General Public License v2.1 |
| GNU LGPL v3.0 | GNU Lesser General Public License v3.0 |
|  | MIT License |
|  | Mozilla Public License 2.0 |
|  | No License |
|  | SIL Open Font License 1.1 |
|  | Open Software License 3.0 |
|  | The Unlicense |
|  | "Do What The F*ck You Want To Public License" |

**Comment by benbalter** [comment]
To clarify what the different fields do:
- Filename - The SPDX ID
- Redirect from - Any previous names the license has had (generally pre-SPDX compliance) to prevent breaking old URLs
- Category - means of grouping similar licenses (e.g., GPL, BSD)
- Tab slug - For the UI for the grouping, we need a URL-friendly means of describing / linking to the license. Jekyll doesn't easily expose the filename/spdx id, so we need to expose our own.
- Nickname - shorter, human-readable version of the license name so that it better fits in the UI / matches expectations

**Comment by waldyrious** [comment]
Thanks for the clarifications. I guess I would then suggest merging `redirect_from` into `tab-slug`, calling it simply `slug`, and automatically redirecting from the `slug` string for all licenses. This would preserve all old links except "lgpl-v2.1", which honestly sounds like a reasonable compromise given the simplification gains.

By the way, I'm not sure whether this would cause problems where the actual permalink equals the current `tab-slug` value, e.g. "isc", "unlicense". But it doesn't sound like something that would be hard to address.

**Comment by benbalter** [comment]
> Thanks for the clarifications. I guess I would then suggest merging redirect_from into tab-slug, calling it simply slug, and automatically redirecting from the slug string for all licenses. 

I think this would confuse things more than it would solve them. The slug, is technically the filename (what's seen in the URL). The redirect_from field is a dummy page that Jekyll creates to redirect users from the old URL to the new URL. Further, not all posts with tab-slugs have redirects and vise versa. What are you trying to solve for here?

**Comment by waldyrious** [comment]
> The slug, is technically the filename (what's seen in the URL)

True, and the fact that these would automatically redirect actually makes that association work, even if they aren't the canonical url. It's a pity that html IDs can't contain `.`, otherwise we could harmonize all three :)

In fact, we still can, if we swap things and make the current canonical urls into redirects. To prevent having to define the correspondence manually for each license, we'd need an unambiguous mapping between the slug and the current filename, which requires including the v in the canonical slug, but not the period. We could then make automatic redirects with (1) the v removed, (2) the period added, and (3) doing both. All current URLs would still work, and we'd only have a single "slug" property defined per license, which would be the same as the filename, and serve as its tag-slug if necessary.

I'm not sure if I'm explaining this well, but I can make another table showcasing how this would look like. It would be a simpler and more consistent model, with less special cases.

> not all posts with tab-slugs have redirects and vise versa. What are you trying to solve for here? 

Exactly, the metadata model is more complex than necessary IMO, and this makes understanding/manipulating the properties in the licenses harder. For instance, when a new license is added, or if someone is using this data elsewhere. The increased number of properties and the very fact that they are only present for some licenses (as you point out) are avoidable.

**Comment by bkeepers** [comment]
> It's a pity that html IDs can't contain `.`, otherwise we could harmonize all three :)

You could use the [`replace` liquid filter](https://github.com/Shopify/liquid/wiki/Liquid-for-Designers):

> `replace` - replace each occurrence e.g. `{{ 'foofoo' | replace:'foo','bar' }} #=> 'barbar'`

**Comment by mlinksva** [comment]
I don't see need for nickname going away, and redirects are needed to not break links. tag-slug is gone and the documentation is a bit clearer. Is there anything else that can be done to address the lack of clarity you noted, @waldyrious? If you think so, please re-open and explain. Thanks!

**Comment by waldyrious** [comment]
I'll have to recreate a table like the one on top, to see if there's any redundancy or opportunities to complete (and hopefully automate) partial patterns. I will reopen if I manage to do so.
