### ISSUE TITLE
Merge "featured" and "hidden" into a single "visibility" property

### ISSUE THREAD

**Issue by waldyrious** [github/choosealicense.com#291]
Instead of (optional) `featured` and `hidden` properties, which are mutually exclusive, what about using a single `visibility` property, with the values "featured", "hidden", and "normal"?

That would reduce the number of properties, and prevent the (unlikely, but technically possible) eventuality of a license having both "featured" and "hidden" set to true (they can be both present if at least one of them is set to false, so a test could be added to ensure that, but why not embedding this directly into the data structure itself if we can, thus making things simpler/cleaner?)

**Comment by bkeepers** [comment]
Sounds reasonable to me. I'm going to close this for now since it's not really causing any issues, but we will gladly look at a pull request that does this.

**Comment by waldyrious** [comment]
@bkeepers I suppose that's a sign that github may need to start supporting extra functionality for issues? ;) I.e. marking as feature request vs. bug, and closing vs. resolving, etc.

I'll look into submitting a PR soon. Was just waiting for feedback from you guys, really.
