### ISSUE TITLE
Switch to clipboard.js from ZeroClipboard.js

### ISSUE THREAD

**Issue by OmgImAlexis** [github/choosealicense.com#297]
Since zeroclipboard requires flash [clipboard.js](https://zenorocha.github.io/clipboard.js/) should be used so people without flash can still use the `copy to clipboard feature`. clipboard.js also takes advantage of the new html5 clipboard APIs. I believe this is what github.com uses now.

**Comment by benbalter** [comment]
Makes sense. @OmgImAlexis any interest in submitting a pull request?

**Comment by OmgImAlexis** [comment]
@benbalter sure, just wanted to make sure it was wanted before I did all the work. :+1:

**Comment by zenorocha** [comment]
+1

**Comment by zenorocha** [comment]
Any news on this?

**Comment by OmgImAlexis** [comment]
Doing this today, had to reinstall OSX so I'm just getting everything setup again.
