### ISSUE TITLE
List of OSI-approved OSS licenses

### ISSUE THREAD

**Issue by andypiper** [github/choosealicense.com#3]
The OSI maintains a list of approved OSS licenses here:

http://opensource.org/licenses/alphabetical

It would be good to see these added to the options, although perhaps with a smaller subset suggested by default.

(there's also the WTFPL but that may not be suitably "family friendly"?)

**Comment by haacked** [comment]
Thanks for the suggestion. According to our [about page](http://choosealicense.com/about/)

> Not comprehensive
> 
> This site is not a comprehensive directory of open source licenses. If you’re looking for a comprehensive list, we recommend the Open Source Initiative website.

We already link to opensource.org. Perhaps we should have that link point to the URL you provided. If so, feel free to submit a pull request. You can even do it in the browser by going here: https://github.com/github/choosealicense.com/blob/gh-pages/about.md and click Edit.
