### ISSUE TITLE
Send License as a Pull Request

### ISSUE THREAD

**Issue by benjamine** [github/choosealicense.com#30]
To make it even more straitghforward, It would be cool to have button to make this site send a Pull Request to a specific public github repo adding the license as a file, and/or optionally as a new section on the README.md

**Comment by aatxe** [comment]
It's already natively integrated into GitHub on the create a repository page. Anything else would likely be unnecessary.

**Comment by cobyism** [comment]
Yeah, we also make the license chooser visible if you go to create a new file called `LICENSE` or `COPYING` (with or without any file extension, and it’s case insensitive).

![2013-07-16 at 9 56 am](https://f.cloud.github.com/assets/296432/803575/1436cbda-edf6-11e2-80b5-4307585a09af.png)

This, combined with the auto-forking behaviour (with subsequent quick-pull-request being sent) when you go to create a new file on a repository you don’t have access to should make it possible to send a PR to add a license file a very quick and painless activity. Anything more closely tied to this site I feel would start to get unnecessarily complicated.

Thanks for the suggestion though! :smile:

**Comment by benjamine** [comment]
nice, I didn't knew of that feature, thanks!
