### ISSUE TITLE
Can I build a website with similar CSS?

### ISSUE THREAD

**Issue by IonicaBizau** [github/choosealicense.com#309]
First of all, thanks for the nice stuff that is here! :sparkles: 

I'm building a site that provides a nice API for listing and understanding software licenses, and I want to make sure I can take some CSS from `choosealicense.com` (especially the home page: the big title and the blue `{ description }`).

Since it's open-source, probably it's fine, but I want to be 100% sure I'm not doing it wrong. 

I will add also some thanks in my project as well. :smile:

**Comment by bkeepers** [comment]
Hi @IonicaBizau! Check out the [license info here](https://github.com/github/choosealicense.com#license); the content for this website is CC-BY-3.0, and the underlying source code, including CSS, is MIT.

> I'm building a site that provides a nice API for listing and understanding software licenses…

I'm just curious, what kind of software licenses?

Good luck!

**Comment by IonicaBizau** [comment]
> and the underlying source code, including CSS, is MIT.

Should be OK, then. Thanks!! :cake: 

> I'm just curious, what kind of software licenses?

@bkeepers Mainly open-source licenses, but anybody will be able to add new licenses (via the GitHub workflow). I will share a link when my app is ready, but if you have superpowers, you can check out my private repos and you will find it. :grin:

**Comment by benbalter** [comment]
> I'm building a site that provides a nice API for listing and understanding software licenses...but anybody will be able to add new licenses (via the GitHub workflow)

@IonicaBizau have you seen https://developer.github.com/v3/licenses/ (which is powered by the licenses in this site)?

**Comment by IonicaBizau** [comment]
@bkeepers Yes, I saw that. I built a site to display licences and optionally fill the copyright data using querystring parameters and optionally show available paragraph-by-paragraph explanations, maintained by the community.

Example:

> http://showalicense.com/?year=2013&fullname=Alice#license-mit
> 
> It fills the year data and fullname in the MIT license output.

I open-sourced all the things: http://showalicense.com/
You can check out the code at https://github.com/IonicaBizau/showalicense.com :sparkles: 

Thanks! :cake:
