### ISSUE TITLE
Should the copyright notice on the artistic license refer to the license itself or the project it licenses?

### ISSUE THREAD

**Issue by benbalter** [github/choosealicense.com#310]
In https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/artistic-2.0.txt#L29, the 2nd line of the license, replaces [the standard](https://opensource.org/licenses/Artistic-2.0):

> Copyright (c) 2000-2006, The Perl Foundation.

with:

>  Copyright (c) [year] [fullname]

(Which gets mail-merged when programmatically added to a project)

In every other license I know of, a copyright notice on the first or second line is intended to refer to the project as a whole, not the license. When copyright notices for the license itself are included, e.g., https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/afl-3.0.txt#L69, it's explicit that it's for the license, not the project.

@mlinksva Do you happen to know? If not, do you know someone from the perl foundation which we can ask?

**Comment by mlinksva** [comment]
I'm fairly certain that notice refers to the license document itself. The GPL family has likewise.

_Edit:_ Certain. On opensource.org licenses that are templates with copyright notice for licensed code to be filled in have some (inconsistent but fairly clear) notation of such. Many instances of the full Perl Foundation copyright notice for the license itself -- https://github.com/search?utf8=%E2%9C%93&q=%22Copyright+%28c%29+2000-2006%2C+The+Perl+Foundation.%22&type=Code&ref=searchresults -- Perl modules typically have copyright notice for the code itself in a README and usually also in the module's docstrings (POD) -- http://www.perlfoundation.org/cpan_licensing_guidelines

**Comment by benbalter** [comment]
Looking at the text of the GPLs, I trust @mlinksva and am fine reverting it back to the original text, unless there's any objection (but likely wont get to a PR until next week at the earliest, as it's a Holiday here in the :us:).
