### ISSUE TITLE
Document how to propose that a new license be added

### ISSUE THREAD

**Issue by benbalter** [github/choosealicense.com#315]
And how to evaluate if it should be:
- How to do a GitHub code search
- The site's philosophy
- Objective criteria for notoriety / differentiation (?)
- How to do it practically

**Comment by mlinksva** [comment]
On objective criteria point, could take others' decisions, e.g., must have an [SPDX identifier](http://spdx.org/licenses/) _and_ appear on at least one approved free/open license list out of https://opensource.org/licenses/alphabetical http://www.gnu.org/licenses/license-list.en.html (the free ones) http://opendefinition.org/licenses/ (non-software).

All licenses (except of course "no license") we currently include would satisfy that rule.

A couple of proposed ones wouldn't. #314 doesn't have an SPDX id but that would be a fairly easy hoop for someone who cares about the license to see through. #313 don't have SPDX ids nor are they in any approved list. Maybe the open hardware community would be motivated to vet licenses and maintain one on a more formal basis than the FAQ entry in http://www.oshwa.org/sharing-best-practices/

**Comment by benbalter** [comment]
Fixed by https://github.com/github/choosealicense.com/pull/316.
