### ISSUE TITLE
Feedback from John Sullivan talk on license choosers

### ISSUE THREAD

**Issue by bkeepers** [github/choosealicense.com#335]
John Sullivan from FSF gave a great talk at FOSDEM on license choosers. He had some helpful observations and recommendations for choosealicense.com that I've attempted to summarize here:
- Make the agenda explicit. Any attempt to simplify and summarize options will have implicit biases, so at least name them.
- MIT
  - Being the first one listed puts it in a (potentially) privileged position
  - The heading of being "Simple & Permissive" could be seen as more appealing
  - "short and to the point" is not normative
  - 2 examples listed instead of 3
- Apache:
  - description is not as compelling as MIT
  - "I’m concerned about patents” is not a distinguishing feature from GPL, creating a false dichotomy
  - description builds on MIT
  - Patent text is unclear
- GPL
  - fix name: _GNU_ GPL
  - none of the examples are GPL v3
  - “further restricts” is slanted phrase
  - “hardware that forbids software alterations” is not entirely correct
  - Recommended change: “It lets people do anything they want with your code as long as, if they give your code or something based on it to others, they give those people the same 

Anyone else that saw the talk: please correct or add to these points.

**Comment by bkeepers** [comment]
> Make the agenda explicit. Any attempt to simplify and summarize options will have implicit biases, so at least name them.

The [README](https://github.com/github/choosealicense.com#immediate-goals) lists the immediate goals, but it may be worth further clarifying. In a comment at the end of the session, I described our agenda as (in this order):
1. Get project maintainers to choose a license (which means simplifying as much as necessary)
2. Reflect consensus of community and license authors as accurately as possible

**Comment by mlinksva** [comment]
Seems like reasonable feedback. I can begin to implement, or rather continue to implement, once #336 which addresses the lack of GPLv3 examples, is merged.

As I've [mentioned elsewhere](https://github.com/github/choosealicense.com/issues/331#issuecomment-176884853), I'd rather not have GPLv2 at all on the home page. That would solve needing to try to differentiate between v2 and v3 on the home page, which is hard to get correct and way too much detail for 99%. Wonder if John mentioned any preference there?

**Comment by mlinksva** [comment]
[Abstract](https://fosdem.org/2016/schedule/event/license_pickers/), [video](http://video.fosdem.org/2016/ud2218a/pick-a-peck-of-license-pickers.mp4)

I'm mildly surprised http://home.ccil.org/~cowan/floss/ wasn't mentioned. It's the best.

At about 48 minutes someone claims to be surveying developers of projects that have _changed_ their projects' licenses. Would love to know who this is or better a link to their publications.

**Comment by mlinksva** [comment]
John Sullivan seems to like the changes so far https://twitter.com/johns_FSF/status/709408622258864130 though there's still quite a bit more to do.

**Comment by mlinksva** [comment]
> At about 48 minutes someone claims to be surveying developers of projects that have _changed_ their projects' licenses. Would love to know who this is or better a link to their publications.

Probably http://www.cs.wm.edu/~denys/pubs/ICSME'15-LicensingSurvey-CRC.pdf which mined 12 million public projects listed via the GitHub API, from which 381,161 Java projects were identified, of these 16,221 projects were randomly selected. The commit histories of selected projects (1,731,828 commits spanning 4,665,611 files) were used "to identify the commits where licenses were added or changed" finding 1,833 projects with delayed initial license addition or licensing change. From those projects, 2,398 developers with valid e-mail addresses for non-Android (which "have always been licensed under the Apache license") were invited to a survey about their "involvement in licensing-related decisions"; 138 responded (5.75%, below 10% "often achieved in survey studies"), 76 indicated involvement in determining project licensing and 52 completed the entire 7 question survey.  There's a table of survey results on page 7.

Very brief mention (bolded):

> A  feature  provided  by  the  forge  to  support  domain  sug-
> gested  licensing  could  benefit  practitioners.  Since  developers
> indicated that licensing is difficult, a more informative feature
> could  help  practitioners  determine  the  appropriate  licensing.
> For instance, the current licensing support feature provided by
> GitHub feature is not particularly informative for developers.
> Basically,  it  provides  a  link  to  **choosealicense.com**,  but  does
> not provide further guidance to the developer. Also, it does not
> cover issues related to compatibilities at all. Moreover, appli-
> cations within the same domain may be utilizing some of the
> same dependencies or require similar grants for redistribution
> and reuse. To better support developers, a forge could include
> a  domain  analysis  feature  to  detect  similar  applications  [22]
> and  suggest  to  the  developer/maintainer  the  license  used  by
> similar systems (if no other criteria has been considered, such
> as community or dependencies).
