### ISSUE TITLE
add FOSS exception to GPL

### ISSUE THREAD

**Issue by Waquo** [github/choosealicense.com#34]
I believe that adding a FOSS exception to the GPL by default is a good idea, and should be added to the featured license.

This is a good example for such an exception. http://www.digirulesolutions.com/drupal/foss

See also these instructions by the FSF on the topic: http://www.gnu.org/licenses/gpl-faq.html#GPLIncompatibleLibs

Is there any good reason to use a vanilla GPL v2 without making it compatible with at least the Apache License 2.0, one of the other features licenses?

PS:
While a FOSS exception like the one used by drupal does change the scope and effect of the copyleft of the GPL (thanks gerv), a minimal exception to the GPL v2 could at least ensure compatibility with the Apache License 2. As I understand, the "patent termination and indemnification provisions" in the Apache License 2 that, while present in the GPL v3, are not present in the GPL v2 and the only reasons the GPL v2 is not compatible with the Apache License 2, while the GPL v3 is compatible.
http://www.apache.org/licenses/GPL-compatibility.html
Could this not be remedied with a minimal exception to the GPL v2 stating that if part of the derived work covered is licensed under the Apache License 2, the patent and indemnification provisions are ok and not considered forbidden restrictions?
Other than the hassle of writing such a restriction and getting the legalese right, is there any reason not to do this? It would be really nice if two of the featured licenses on choosealicense.com were not incompatible with each other, wouldn't it?

**Comment by gerv** [comment]
The FOSS exception may be suitable for some people, but it significantly changes the effect, and the scope of the copyleft, of the GPL. It effectively makes it a lot more like the LGPL.

**Comment by Waquo** [comment]
Added PS. See above.

**Comment by gerv** [comment]
A small Apache-2.0 compatibility exception for GPL 2.0 would be a much more limited change and, if good legalese could be found, might be an excellent idea. But perhaps that's a different 'issue' to be filed :-)

**Comment by ghost** [comment]
FWIW, +1 on the original idea, and very happy if it was considered.

I believe it would be more useful than strict GPL, in practice I think it's what a number of open source developers intend when using GPL.
OTOH, to be fair, I've also seen that it's prone to potential long discussions, and complicated, at least for me. I could never figure out if the "complication" is only my (IANAL) perception, or a simple impression tributary to external biases, or there are really good reasons why GPL itself seems complicated on this point.

**Comment by haacked** [comment]
As [indicated here](https://github.com/github/choosealicense.com/pull/69#issuecomment-21641265):

> And note that the "theoretical" incompatibility is a statement/belief of the FSF. The Apache Software Foundation does not believe they are incompatible.

I'd rather not start adding exceptions to established licenses to resolve disputes from different organizations for the following reasons:
1. It creates what is in effect a new license. If you have a GPL, you know it's OSI certified. But is GPL with an exception also OSI certified? Maybe. Maybe not.
2. It leads to license proliferation. When you have a well-known license, people are in agreement about what it means. Having to also wade through exceptions seems to make things more confusing. It's also not clear that the result
3. We want to present established licenses in their original form. If someone understands licensing well enough to want an exception, they can choose to consult a legal professional and modify the license as they see fit.

I don't think we should be in the business of dictating what exemptions "belong" to a license.

**Comment by gerv** [comment]
"It creates what is in effect a new license. If you have a GPL, you know it's OSI certified. But is GPL with an exception also OSI certified? Maybe. Maybe not."

Giving additional permissions on top of an OSI-compatible licence can never make it OSI-incompatible.

"It leads to license proliferation. When you have a well-known license, people are in agreement about what it means. Having to also wade through exceptions seems to make things more confusing. It's also not clear that the result"

Exception is perhaps the wrong word. What is requested here is an additional permission. Some people (e.g. the ASF) may think the additional permission is not necessary because the licence already gives that permission. That's fine. They can just ignore the additional permission.

So something like:

"For the avoidance of doubt, it is expressly permitted to incorporate code from this project into software licensed under the GNU General Public License 2.0 or later, or the GNU Lesser General Public License 2.1 or later."

How can that add additional confusion? (The final text may need to be more specific, but it would basically say the above.)

**Comment by haacked** [comment]
So where do I put this text? In the license? If you choose the GPL and want to add this additional permission, you are free to do it. I don't think we should make this the default. We're not in the business of tweaking licenses.

**Comment by gerv** [comment]
AIUI, the license chooser helpfully checks in a copy of the license text into your repo. Isn't that right?

If so, you just append it to the bottom of the license file. Once it's been drafted appropriately, of course. I'm sure the FSF has some language; this is hardly an uncommon problem.

You talk of "tweaking" licenses, but this is not changing the GPL - it is an additional permission on top. This is a pretty common thing to do - there already exists a GPL "extra permission" text for fonts, and one for linking with OpenSSL, one for GCC, and I'm sure there are more. Two of the below are specifically authored by the FSF:

Fonts: http://www.gnu.org/licenses/gpl-faq.html#FontException
OpenSSL: http://lists.debian.org/debian-legal/2004/05/msg00595.html
GCC Runtime Libraries: http://www.gnu.org/licenses/gpl-faq.html#LibGCCException

**Comment by haacked** [comment]
> AIUI, the license chooser helpfully checks in a copy of the license text into your repo. Isn't that right?

Yep. But why would we make any exception the default? If you were to ask the FSF what the default should be when someone chooses GPL v2 or GPL v3, what would they say?

I don't have a problem with people adding exceptions to their license. I just don't think we should make that the default.

**Comment by gerv** [comment]
What would the FSF say? Good question. I suspect they'd say "don't recommend GPLv2 at all; everyone should be using GPLv3". If you are going to go against the FSF on that point, and give GPLv2 as an option, then you shouldn't have an issue with using GPLv2+additional_permission as your default version of the GPLv2 :-)

We could ask them, if you like...

(The change I am suggesting is not required for GPLv3, which everyone agrees is Apache-v2 compatible.)

**Comment by haacked** [comment]
> The change I am suggesting is not required for GPLv3, which everyone agrees is Apache-v2 compatible.

Ah! Ok, I did not realize this, but upon a more careful reading, I should have.

@benbalter, @talniv, or @hoolio any thoughts on this?

**Comment by gerv** [comment]
I should clarify something; my draft text above is written as if it were an addition to the Apache License 2.0, which is bogus. We need "the inverse". Let me restate my proposal, to add clarity. I am proposing the language such as the following is appended to the bottom of the COPYING file which is checked in whenever anyone chooses the GPLv2 as their license. This text is based on the boilerplate "exceptions" in the GPL FAQ:

"In addition, the copyright holders give you any additional permission you may need to combine code licensed under the Apache License 2.0 with this software. Opinions differ as to whether additional permission is necessary for this activity; the aim of this clause is to remove any doubt.

Note that people who make modified versions of this software are not obligated to explicitly grant this additional permission for their modified versions; it is their choice whether to do so. The GNU General Public License gives permission to release a modified version without this additional permission; this additional permission also makes it possible to release a modified version which carries forward this additional permission."

**Comment by ghost** [comment]
> "In addition, the copyright holders give you any additional permission you may need to combine code licensed under the Apache License 2.0 with this software. Opinions differ as to whether additional permission is necessary for this activity; the aim of this clause is to remove any doubt.
> 
> Note that people who make modified versions of this software are not obligated to explicitly grant this additional permission for their modified versions; it is their choice whether to do so. The GNU General Public License gives permission to release a modified version without this additional permission; this additional permission also makes it possible to release a modified version which carries forward this additional permission."

In practical terms, I believe this proposal is the most significant (pragmatically) improvement and it saves meaningless potential headaches for projects. Thank you for drafting it!

It probably should be done along with a little additional note on GPLv2 page though, if it's done. For example, an addition/footnote to the description on GPLv2 page: "If you choose this license, note that an additional permission is included in the license text, for combining with code licensed with Apache License 2.0. This may not be necessary, but it is included for clarity. If you wish to remove that permission, check the last lines of the license text once applied to your repository and remove them."

What I mean is, strictly speaking the license applied by the chooser is not the bare GPLv2 text, so we should notify the user of that (even if they should check for themselves, and even if the license may be interpreted to already allow it anyway).

**Comment by davelab6** [comment]
+1 to @gerv 's additional permission for GPLv2
