### ISSUE TITLE
Add Unlicense

### ISSUE THREAD

**Issue by zookatron** [github/choosealicense.com#36]
Please consider adding the [Unlicense](http://unlicense.org/) to the list. A [significant amount of people use this license](https://github.com/search?q=This+is+free+and+unencumbered+software+released+into+the+public+domain&type=Code) and I personally prefer it since I find it even more "simple and permissive" than the MIT license. I'd be happy make a pull request for this if it is likely to be accepted.

**Comment by artob** [comment]
:+1:

Another estimate of people using the Unlicense on GitHub, showing new projects being created on an everyday basis: https://github.com/search?q=unlicense&type=Code&s=indexed

**Comment by artob** [comment]
This is good to close now since #38 was merged and added the Unlicense.
