### ISSUE TITLE
Test for markdown in fields that will cause it to be rendered unparsed

### ISSUE THREAD

**Issue by mlinksva** [github/choosealicense.com#367]
https://github.com/github/choosealicense.com/commit/a4f990fe54640d495ee6752f43eb472121200d79 an example of fixing. Previous state should not have passed tests.

**Comment by benbalter** [comment]
Alternatively, we could run the fields through the `markdownify` filter. Depends on if you want markdown, HTML, or only plain text in the metadata fields.
