### ISSUE TITLE
Update choosealicense's license to CC 4.0

### ISSUE THREAD

**Issue by wolftune** [github/choosealicense.com#370]
It's updated enough to tell everyone else to use 4.0, how about updating the site's content itself to use 4.0?

**Comment by mlinksva** [comment]
I plan to do this, but need to clarify the content and source licensing of the project overall first. I'll leave this open til then and reference in upcoming PR.

**Comment by ghost** [comment]
Is this still planned?

**Comment by mlinksva** [comment]
In the fullness of time, when it's worth bugging past contributors. It's not as simple as updating the license, as explained at https://github.com/spdx/spdx-spec/issues/3#issuecomment-397374675 (in response to the same request in another project...). Not worth keeping this issue open.
