### ISSUE TITLE
Add PDM

### ISSUE THREAD

**Issue by MattTheNub** [github/choosealicense.com#375]
Since there is CC0 and The Unlicense, The [CC Public Domain Mark](https://creativecommons.org/about/pdm) should also be included.

**Comment by mlinksva** [comment]
Thanks for the suggestion! It seems logical, but ... the CC PDM doesn't qualify, per https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license
- No SPDX ID

It probably meets the 'approved' criterion though it is an odd case, as well as the use criterion https://github.com/search?utf8=%E2%9C%93&q=%22http%3A%2F%2Fcreativecommons.org%2Fpublicdomain%2Fmark%2F1.0%2F%22&type=Code&ref=searchresults (23k results, not sure how many repos but surely >1k).

But it's rarely the right choice for a work in revision control. I haven't inspected a sample of them, but I'd bet many are confused applications. PDM is only for works not subject to copyright or similar restrictions at all. It isn't a license. CC0-1.0 or Unlicense are better choices for anything that will have new contributions. I would be unexcited about adding the CC Public Domain Mark to choosealicense.com even if it did have a SPDX ID.
