### ISSUE TITLE
Add list of projects using the ISC license [WIP/RFC]

### ISSUE THREAD

**Issue by waldyrious** [github/choosealicense.com#377]
I'm not creating a PR yet because I'm still collecting projects to figure out which 3 examples would be a good representative sample. Here's what I've got so far:
- [redisent](https://github.com/jdp/redisent/blob/master/LICENSE) ("a no-nonsense Redis client for PHP")
- [bundy](https://github.com/bundy-dns/bundy/blob/master/COPYING) ("an integrated authoritative DNS and DHCP server")
- [geojson.io](https://github.com/mapbox/geojson.io/blob/gh-pages/LICENSE) ("a fast, simple editor for map data")
- [node-glob](https://github.com/isaacs/node-glob/blob/master/LICENSE) ("glob functionality for node.js")
- [node-semver](https://github.com/npm/node-semver/blob/master/LICENSE) ("the semver parser for node")
- [phantomjs-node](https://github.com/amir20/phantomjs-node/blob/master/LICENSE.md) ("PhantomJS integration module for NodeJS")
- [documentationjs](https://github.com/documentationjs/documentation/blob/master/LICENSE) ("beautiful, flexible, powerful js docs")
- [iD](https://github.com/openstreetmap/iD/blob/master/LICENSE) ("the easy-to-use OpenStreetMap editor in JavaScript")

Some additional notes/TODO:
- [x] ~~It appears that several of @mapbox's repositories are released under the ISC license, but there are a lot of them so I need to sift through them to find the best representative sample.~~
  - geojson.io seems to be the most popular under the ISC license, added above. Other candidates are [geojson-vt](https://github.com/mapbox/geojson-vt), [docbox](https://github.com/mapbox/docbox) and [earcut](https://github.com/mapbox/earcut).
- [ ] I would expect (naturally) @isc-projects's repos to also use this license, but the situation isn't exactly clear (see [here](https://github.com/isc-projects/kea/blob/master/COPYING) vs [here](https://github.com/search?l=&q=isc+license+repo%3Aisc-projects%2Fkea&ref=advsearch&type=Code&utf8=%E2%9C%93)). Any clues how to interpret this?
- [x] ~~The Node.js package init tool defaults to ISC, so there are bound to be popular packages using the ISC license. I need to find a way to filter the npm repository by license and find the most popular ones.~~
  - I found two ways to filter npm packages by license: https://libraries.io/licenses/ISC and http://npmsearch.com/?q=license:isc. I've added the most popular ones above (and removed some of the more obscure ones there, to reduce noise). 
- [ ] OpenBSD [recommends it for all new code](http://cvsweb.openbsd.org/cgi-bin/cvsweb/src/share/misc/license.template?rev=1.1&content-type=text/x-cvsweb-markup), but I'm not sure the project can as a whole be described as falling under it. Thoughts?
  - There seems to be an up-to-date mirror of the project's source code at [netzbasis/openbsd-src](https://github.com/netzbasis/openbsd-src). It could be interesting to scan these source files or grep them somehow to find the primary licences used. licensee [doesn't check the contents of source files](https://github.com/benbalter/licensee#what-about-checking-every-single-file-for-a-copyright-header); maybe [fossology](https://www.fossology.org/get-started/basic-workflow) could work?
- [x] ~~[NetBSD](https://github.com/IIJ-NetBSD/netbsd-src) appears to have some components licensed under ISC, need to confirm.~~
  - [Doesn't seem to be the case](https://github.com/IIJ-NetBSD/netbsd-src/search?utf8=%E2%9C%93&q=isc+filename%3Alicense&type=Code)

Any additional pointers?

**Comment by mlinksva** [comment]
3 programs that are well known, at least among *nix developers/admins:
- https://github.com/tmux/tmux/blob/master/COPYING ... but they didn't modify the template and fill in <author>
- https://www.sudo.ws/repos/sudo/file/tip/doc/LICENSE
- https://source.isc.org/cgi-bin/gitweb.cgi?p=bind9.git;a=blob;f=COPYRIGHT;hb=HEAD

Found with a [wikidata query](https://query.wikidata.org/#SELECT%20%3Fproject%20%3FprojectLabel%0AWHERE%0A{%0A%09%3Fproject%20wdt%3AP275%20wd%3AQ386474%20.%20%0A%09SERVICE%20wikibase%3Alabel%20{%0A%09%09bd%3AserviceParam%20wikibase%3Alanguage%20%22en%2Cfr%2Cde%2Che%2Cel%2Cfi%2Cno%2Cja%2C%22%20.%0A%09%09%3Fproject%20rdfs%3Alabel%20%3FprojectLabel%20.%0A%09}%0A}%0A).

**Comment by waldyrious** [comment]
Nice, thanks for the additional data and for the Wikidata query example. I hope the interface for those gets more intuitive sometime soon :) I have some questions regarding those:
- The tmux situation seems to be similar to ISC's kea as pointed above (especially given the disclaimer "THIS IS FOR INFORMATION ONLY, CODE IS UNDER THE LICENCE AT THE TOP OF ITS FILE." in the LICENSE file). Are we able to somehow use that file to define the license for the project, or do we need to exhaustively check every source file and confirm that they're all under ISC? And what if most are, but there are a few exceptions?
- The sudo LICENSE file is also more complex than would be desirable for an example, IMO. Do you think otherwise? Also, it uses the old wording of the ISC License which isn't approved by the FSF ("and distribute" rather than "and/or distribute"). Couldn't that be a potential problem?
- bind9 has the same multi-license issue that could make it a non-ideal example. It's not a deal-breaker, but should we weigh (perceived?) popularity over clarity, given that we have other options available?

I've updated my comment above with more info. Some items are tasks I can perform myself, others are questions I'd need help answering.

By the way, @benbalter, is there any way to use Licensee and the Github API to automatically find the most popular repos in github licensed under the ISC license? That would be the ideal way to kickstart this and the other licenses that currently lack examples.

**Comment by waldyrious** [comment]
I've created [a category on the English Wikipedia](https://en.wikipedia.org/wiki/Category:Software_using_the_ISC_license) based on the Wikidata query, and also added [OpenStreetMap's iD](https://github.com/openstreetmap/iD) to the list above.

**Comment by benbalter** [comment]
>  is there any way to use Licensee and the Github API to automatically find the most popular repos in github licensed under the ISC license?

No, that's not currently possible via the API.

**Comment by mlinksva** [comment]
@waldyrious you're right, the ideal example uses are straightforward and none of the three I pointed out are. (BTW, the license notice in each file/one for a repo is something some people feel strongly about one way or the other; I don't.)

I think the ISC projects and OpenBSD are also not straightforward.

Thanks for adding the ISC category on English Wikipedia. Also for all your work on Wikipedia!

**Comment by waldyrious** [comment]
Thank you both for the comments. At this point I've reached the limit of what info I can collect or what suggestions I can make. I'll need help addressing the two checkboxes that are still open. Can you guys comment on those?

Afterwards we should agree on a list of tools to present as examples. I'm not strongly opposed to complex licenses; I think we're going to have to find a balance between popularity/recognizability and license file clarity/conciseness. Ideally we'd have both, but the most recognizable projects (I'd say sudo, tmux and OpenBSD) are also the more complexly-licensed... The only one that's both quite popular and clearly licenced as ISC is the iD editor, so that should probably be included in the final list.

**Comment by waldyrious** [comment]
A possible option is mentioning ISC being the [default license for new Node.js projects](https://github.com/npm/npm/commit/2f608fa), rather than picking a single node.js package. But that would deviate from the format we've been using for the examples (name+link only)...

**Comment by mlinksva** [comment]
I think default for Node.js projects and for OpenBSD both face the same problem -- deviation from concrete LICENSE file example.

Given the existing candidates and tradeoffs you've explained, I'd probably go with documentationjs,  node-semver, and OpenStreetMap iD ... all straightforward and somewhat popular, and a somewhat good mix of projects.

**Comment by waldyrious** [comment]
Agreed, sounds like a good compromise to me, although I'm somewhat bummed about tmux and sudo. Anyway, shall I make a PR?

**Comment by mlinksva** [comment]
Yes, please do make a PR.

**Comment by waldyrious** [comment]
I'll use this issue to continue listing projects using this license, until a better database is available. (I could add entries to Wikidata, but I suspect entries without a Wikipedia article are kind of a grey area, depending on the popularity of the project.)
- [Vis](https://github.com/martanne/vis/blob/master/LICENSE)
  ("a vim like text editor")
- [node-heapdump](https://github.com/bnoordhuis/node-heapdump/blob/master/LICENSE)
  ("Make a dump of the V8 heap for later inspection.")
- [jxcore-cordova](https://github.com/jxcore/jxcore-cordova/blob/master/LICENSE)
  (JXcore / Node.JS plugin for Apache Cordova / PhoneGap)
- [openshift-cartridge-nodejs](https://github.com/icflorescu/openshift-cartridge-nodejs/blob/master/LICENSE)
  ("Custom cartridge for OpenShift providing the lastest version of Node.js.")
- [node-openzwave](https://github.com/jperkin/node-openzwave/blob/master/LICENSE.md)
  ("node.js interface to libopenzwave")

**Comment by mlinksva** [comment]
@waldyrious you're more than welcome to use this issue, though I think Wikidata is the right place longer term. There should be a WikiProject FLOSS (or similar) there, but it seems there isn't yet.

Also useful, https://directory.fsf.org/wiki/Main_Page

The Vis LICENSE file is pretty interesting -- very clear and helpful on noting files using and terms of code taken from other projects -- but unfortunately not in a format programs can easily parse. Thanks for noting here!

**Comment by waldyrious** [comment]
I've worked a bit on (English) Wikipedia's [category structure](https://en.wikipedia.org/wiki/Category:Free_software_by_license) to have a complete list of categories for each of the licenses covered by choosealicense. Eventually I'll propose adding an automatic link to the category corresponding to each license. Right now I'm [only missing the MS-RL and Unlicense](https://docs.google.com/spreadsheets/d/1K4nlfbHasBLy0Nio5v5mu6-CHcdUq4cOsiq1KGcRH8U/edit#gid=1159831844), as well as the non-code licenses (not sure how to name the categories). Any suggestions welcome!

As for Wikidata, I agree, although I'm torn on the inability of using it as a comprehensive directory (even for personal pet projects). Besides, the [query interface](https://query.wikidata.org/#SELECT%20%3Fproject%20%3FprojectLabel%0AWHERE%0A%7B%0A%09%3Fproject%20wdt%3AP275%20wd%3AQ386474%20.%20%0A%09SERVICE%20wikibase%3Alabel%20%7B%0A%09%09bd%3AserviceParam%20wikibase%3Alanguage%20%22en%2Cfr%2Cde%2Che%2Cel%2Cfi%2Cno%2Cja%2C%22%20.%0A%09%09%3Fproject%20rdfs%3Alabel%20%3FprojectLabel%20.%0A%09%7D%0A%7D%0A) is very poor for presentation at the moment. [Reasonator](https://tools.wmflabs.org/reasonator/?&q=386474) is an interesting alternative, but I wish we could link directly to the "related items" section.

Ideally, some sort of semantic filtering of publicly available codebases (like ~~[openhub](http://code.openhub.net/) or~~ [searchcode](https://searchcode.com)) would be available, but I haven't found anything comprehensive that allows easy filtering by license yet. Maybe [Libraries.io could be it](https://libraries.io/licenses/ISC) -- I need to investigate further.

**Comment by waldyrious** [comment]
Btw, the FSF directory is an awesome resource! Too bad they don't expose clean [query URLs...](https://directory.fsf.org/wiki/Special:RunQuery/Query_license?query=true&Query+license[License][58]=ISC&Query+license[License][is_list]=1&sf_free_text=&wpRunQuery=Run+query)

For future reference, I'll dump below the current results that are categorized as exclusively ISC-licensed:

| Project link | Description | License file |
|--------------|-------------|--------------|
| :octocat: [9mount](http://sqweek.net/code/9mount/) | Tools for mounting 9p filesystems on the Linux kernel | [COPYING](https://github.com/minad/9mount/blob/master/COPYING) |
| 🔗 [BIND](https://www.isc.org/software/bind/) | BIND, the most widely used DNS software on the Internet | [COPYRIGHT](https://source.isc.org/cgi-bin/gitweb.cgi?p=bind9.git;a=blob;f=COPYRIGHT;hb=HEAD) |
| :octocat: [Configgy](http://www.lag.net/configgy/) | Simple config and logging setup for scala. | deadlink, apparently now Apache: [LICENSE](https://github.com/robey/configgy/blob/master/LICENSE) |
| :octocat: [Cowlib](https://github.com/extend/cowlib) | Erlang library for manipulating web protocols | [LICENSE](https://github.com/ninenines/cowlib/blob/master/LICENSE) |
| 🔗 [Crda](http://wireless.kernel.org/en/developers/Regulatory/#CRDA) | wireless Central Regulatory Domain Agent | [LICENSE](https://github.com/mcgrof/crda/blob/master/LICENSE) |
| 🔗 [Distro-info](https://packages.qa.debian.org/d/distro-info.html) | provides information about the distributions' releases | [copyright](http://anonscm.debian.org/cgit/collab-maint/distro-info.git/tree/debian/copyright) |
| :octocat: [FontTools](https://github.com/behdad/fonttools) | tools to manipulate font files. | [LICENSE](https://github.com/behdad/fonttools/blob/master/LICENSE) |
| :octocat: [Hitimes](http://github.com/copiousfreetime/hitimes) | fast, high resolution timer for recording performance metrics | [LICENSE](https://github.com/copiousfreetime/hitimes/blob/master/LICENSE) |
| 🔗 [Iw](http://wireless.kernel.org/en/users/Documentation/iw) | tool for configuring Linux wireless devices | [COPYING](http://git.kernel.org/cgit/linux/kernel/git/jberg/iw.git/tree/COPYING) |
| 🔗 [Libkibi](https://launchpad.net/libkibi) | library for byte prefixes | [COPYING](http://bazaar.launchpad.net/~libkibi-dev/libkibi/trunk/view/head:/COPYING) |
| 🔗 [Libpuzzle](http://libpuzzle.pureftpd.org/project/libpuzzle) | quick similar image finder - shared library | [COPYING](https://github.com/jedisct1/libpuzzle/blob/master/COPYING) |
| 🔗 [MudPy](http://mudpy.org/) | a MUD engine implemented in Python. | [LICENSE](http://mudpy.org/res/src/mudpy/doc/LICENSE) |
| :octocat: [Ocaml-ipaddr](https://github.com/mirage/ocaml-ipaddr) | library for manipulation of IP (and MAC) address representations (runtime) | [LICENSE](https://github.com/mirage/ocaml-ipaddr/blob/master/LICENSE) |
| 🔗 [OpenClonk](http://openclonk.org) | A 2D adventure game with mining, building and fighting | [COPYING](https://git.openclonk.org/openclonk.git/blob/HEAD:/COPYING) |
| 🔗 [Openpgp-asciiarmor](http://hackage.haskell.org/package/openpgp-asciiarmor) | OpenPGP (RFC4880) ASCII Armor codec; documentation | [LICENSE](https://anonscm.debian.org/cgit/users/clint/openpgp-asciiarmor.git/tree/LICENSE) |
| :octocat: [Ranch](https://github.com/extend/ranch) | socket acceptor pool for TCP protocols in Erlang | [LICENSE](https://github.com/ninenines/ranch/blob/master/LICENSE) |
| :octocat: [Read-package-json](https://github.com/isaacs/read-package-json) | Read package.json for npm module for Node.js | [LICENSE](https://github.com/npm/read-package-json/blob/master/LICENSE) |
| 🔗 [Red Matrix](http://redmatrix.me) | a webapp platform providing a complete decentralised publishing, sharing, and communications system. | [LICENSE](https://github.com/redmatrix/redmatrix/blob/master/LICENSE) |
| 🔗 [Requestbuilder](https://pypi.python.org/pypi/requestbuilder) | command line-driven HTTP request builder | [COPYING](https://github.com/boto/requestbuilder/blob/master/COPYING) |
| :octocat: [Rinku](http://github.com/vmg/rinku) | autolinker for Ruby | [COPYING](https://github.com/vmg/rinku/blob/master/COPYING) |
| 🔗 [Schelte Bron](http://chiselapp.com/user/schelte/repository/fsdialog/home) | file selection dialog for Ttk | [license.txt](http://chiselapp.com/user/schelte/repository/fsdialog/artifact/2fcb163358738d2b) |
| 🔗 [Symmetrica](http://www.algorithm.uni-bayreuth.de/en/research/SYMMETRICA) | Symmetrica Combinatoric C Library | [COPYRIGHT&nbsp;STATEMENT](http://www.algorithm.uni-bayreuth.de/en/research/SYMMETRICA/copyright_engl.html) |
| 🔗 [Tmux](http://tmux.sourceforge.net/) | Terminal multiplexer | [COPYING](https://github.com/tmux/tmux/blob/master/COPYING) |
| 🔗 [Ttyload](http://www.daveltd.com/src/util/ttyload) | console based color-coded graphs of CPU load average | [LICENSE](https://github.com/lindes/ttyload/blob/master/LICENSE) |
| :octocat: [Vcversioner](https://github.com/habnabit/vcversioner) | Use version control tags to discover version numbers | [COPYING](https://github.com/habnabit/vcversioner/blob/master/COPYING) |
| 🔗 [Wireless-regdb](http://wireless.kernel.org/en/developers/Regulatory/#The_regulatory_database) | wireless regulatory database | [LICENSE](https://git.kernel.org/cgit/linux/kernel/git/sforshee/wireless-regdb.git/tree/LICENSE) |

**Comment by mlinksva** [comment]
For software in Debian, there's also https://codesearch.debian.net/perpackage-results/License%3A%20ISC%20path%3Adebian%2Fcopyright/2/page_0 but something more comprehensive is needed. http://upsilon.cc/~zack/talks/2016/2016-01-31-fosdem-compliance.pdf has one interesting vision.

**Comment by bconry** [comment]
With regard to 

> I would expect (naturally) @isc-projects's repos to also use this license, but the situation isn't exactly clear (see [here](https://github.com/isc-projects/kea/blob/master/COPYING) vs [here](https://github.com/search?l=&q=isc+license+repo%3Aisc-projects%2Fkea&ref=advsearch&type=Code&utf8=%E2%9C%93)). Any clues how to interpret this?

I do have some clues.  :)

While most ISC projects are licensed using the ISC License, Kea is licensed using the MPL 2.0.  Just to keep things confusing, there are other exceptions as well.

Regarding the list of @isc-projects repos:
[kea](https://github.com/isc-projects/kea) - MPL 2.0
[kea-contrib](https://github.com/isc-projects/kea-contrib) - MPL 2.0
[forge](https://github.com/isc-projects/forge) - ISC License
[bind9-stats](https://github.com/isc-projects/bind9-stats) - Perl 5
[isc-dnssec-guide](https://github.com/isc-projects/isc-dnssec-guide) - ISC License
[mini-kea](https://github.com/isc-projects/mini-kea) - ISC License

**Comment by waldyrious** [comment]
Thanks @bconry! I hope to be able to add those to a proper central repository sometime soon.

@mlinksva could this be an idea for another project by github? i.e. what's-the-license? :) Ideally something merging the properties of a wiki and a database -- probably built on top of [Wikibase](https://www.mediawiki.org/wiki/Wikibase)?

**Comment by mlinksva** [comment]
Yes, thanks @bconry. bind9-stats is curious -- the README says same license as Perl 5 (Artistic or GPL), but LICENSE contains the text of BSD-2-clause.

@waldyrious :) I concluded a recent talk saying that there should be more sharing of licensing evaluations. BTW I wanted to use the Node.js ISC default you mention above as an example in https://github.com/github/choosealicense.com/pull/394 but couldn't find any documentation other than that commit.

**Comment by waldyrious** [comment]
@mlinksva besides that commit, I used [this link](https://github.com/npm/npm/blob/master/doc/misc/npm-config.md#init-license) as a reference on [Wikipedia](https://en.wikipedia.org/wiki/ISC_license) -- I don't know it that helps.

**Comment by mlinksva** [comment]
Thanks, that link is better, but ideally would have some explanation to serve as a good example of community license preference.

Tangentially, a new specialized interface for Wikidata is somewhat helpful, though its features really need to be in the default interface: http://tools.wmflabs.org/sqid/#/view?id=P275 (license property)

**Comment by waldyrious** [comment]
@bconry how should [kea's COPYING file](https://github.com/isc-projects/kea/blob/master/COPYING) be changed to reflect the MPL 2.0 license that you mentioned above?

**Comment by waldyrious** [comment]
@bconry also, does bind9-stats use the [Artistic License 1.0](https://en.wikipedia.org/wiki/Artistic_License#Artistic_License_1.0)? That's the one used by Perl 5, according to the actual text of the license, even though v2.0 seems to be preferred according to the article I linked ("The OSI recommends that all developers and projects licensing their products with the Artistic License adopt Artistic License 2.0.").

**Comment by bconry** [comment]
@waldyrious regarding bind9-stats...
First, since the reference is to Perl version 5.12.4 it is definitely referencing the Artistic License 1.0 with the option to use the license from any later version of Perl 5.  I just checked Perl 5.25.2 and it's still using the Artistic License 1.0.
Second, I have just spoken with Michael Richardson and the inclusion of LICENSE appears to have been accidental.  His intent was to use the same licensing terms as Perl 5.

**Comment by bconry** [comment]
@waldyrious regarding [kea's COPYING file](https://github.com/isc-projects/kea/blob/master/COPYING), doesn't it already specify the MPL 2.0 (at least for those things not covered by other licenses)?

**Comment by waldyrious** [comment]
Thanks for the clarifications @bconry. There are slight differences in the text of the Artistic Licence 1.0 from https://opensource.org/licenses/artistic-license-1.0, https://opensource.org/licenses/Artistic-Perl-1.0 and http://dev.perl.org/licenses/artistic.html (the latter matches [the version on the git repository](http://perl5.git.perl.org/perl.git/blob/HEAD:/Artistic)). Can you confirm which version should be used for bind9-stats?

As for kea, yes the COPYING file does mention the MPL but I thought it was a requirement to have the full text of the license present. If not, that's fine by me as it is :)

**Comment by bconry** [comment]
@waldyrious I have confirmed that, aside from whitespace, there are no differences between the 'Artistic' file in the perl-5.12.4.tar.gz ( http://www.cpan.org/src/5.0/perl-5.12.4.tar.gz ) and the version found at the current git HEAD ( http://perl5.git.perl.org/perl.git/blob_plain/HEAD:/Artistic ).

**Comment by waldyrious** [comment]
@bconry yes, that's correct; as I said, the version in http://dev.perl.org/licenses/artistic.html does match the version on the git repository. The actual differences in content lie between that version and the two Artistic License 1.0 pages hosted by the Open Source Initiative, i.e. https://opensource.org/licenses/artistic-license-1.0 and https://opensource.org/licenses/Artistic-Perl-1.0. If these two are the ones officially recognized as FOSS licenses by the OSI, it might not be a good idea to use the different wording present in the Perl source code. Of course, this could just be an issue of missing synchronization. Got any clues?

In any case, I've just sent this message to OSI:

> It appears that neither the text of https://opensource.org/licenses/artistic-license-1.0 nor https://opensource.org/licenses/Artistic-Perl-1.0 match the text of the license in the Perl5 repository: http://perl5.git.perl.org/perl.git/blob/HEAD:/Artistic. Is this just a matter of lacking synchronization, or has the OSI not approved the current text of the license? (note that in all 3 cases above we're talking about the 1.0 version of the license).

**Comment by waldyrious** [comment]
@bconry I believe I might have figured out what's happened. It turns out there ate not two, but three variants of the Artistic License 1.0. SPDX calls these "[Artistic License 1.0](http://spdx.org/licenses/Artistic-1.0.html)", "[Artistic License 1.0 w/ clause 8](http://spdx.org/licenses/Artistic-1.0-cl8.html)" and "[Artistic License 1.0 (Perl)](http://spdx.org/licenses/Artistic-1.0-Perl.html)". Here's how they match up with the texts from OSI:

1) OSI's "[Artistic License 1.0 (Artistic-1.0)](https://opensource.org/licenses/artistic-license-1.0)" indeed does match SPDX's  "[Artistic License 1.0](http://spdx.org/licenses/Artistic-1.0.html)"

2) OSI's "[Artistic License (Perl) 1.0](https://opensource.org/licenses/Artistic-Perl-1.0)" actually corresponds to SPDX's "Artistic License 1.0 w/ clause 8" (i.e. the same as the original, with an extra clause added, which corresponds to how OSI describes it:

> This version of the Artistic License 1.0 contains a clause introduced for licensing an implementation of the Perl programming language. (...) Without this clause present, it is called simply the Artistic License 1.0 (abbreviated as Artistic-1.0).

3) SPDX's "[Artistic License 1.0 (Perl)](http://spdx.org/licenses/Artistic-1.0-Perl.html)" is **not present in the OSI website, despite the title of the license in 2) above**. This license indeed does match the contents of the [file in the Perl repository](http://perl5.git.perl.org/perl.git/blob/HEAD:/Artistic), the text [displayed in the Perl website](http://dev.perl.org/licenses/artistic.html), and the 'Artistic' file in [v5.12.4](http://www.cpan.org/src/5.0/perl-5.12.4.tar.gz), as you pointed out.

So, is it safe to assume that bind9-stats uses the license SPDX calls "[Artistic License 1.0 (Perl)](http://spdx.org/licenses/Artistic-1.0-Perl.html)"?

**Comment by waldyrious** [comment]
@bconry could you confirm that bind9-stats is intended to be released under the license SPDX calls "Artistic License 1.0 (Perl)" as described in my last comment above? I'd like to submit a PR updating the [LICENSE file](https://github.com/isc-projects/bind9-stats/blob/master/LICENSE) accordingly.

**Comment by bconry** [comment]
@waldyrious I'm getting @vrisk to help me look at this.  It appears that the copyright might be misattributed, which needs to be cleared up before licensing can be settled.
