### ISSUE TITLE
Rule about military use

### ISSUE THREAD

**Issue by MaPePeR** [github/choosealicense.com#39]
When choosing a licence you should know, that with the wrong license your software/project might be used to harm people or at least might help organisations that harm people.

**Comment by cobyism** [comment]
Are you able to give some more specific examples of what you believe should be changed on the site?

**Comment by MaPePeR** [comment]
I think a "rule-dot" for "Military use" should be added, that then is categorized into `Permitted` and `Forbidden`.
Just like "Commercial Use" but with more guns.

**Comment by cobyism** [comment]
Are there any specific licenses in our list where military use is expressly permitted or forbidden though? I feel like it’s important to keep the comparison dots focused on what each license explicitly requires, permits, or excludes.

**Comment by MaPePeR** [comment]
I think there are no expressly formulated rules for or against military use, but not having this expressly forbidden or permitted has an effect of what the license _actually_ permits/forbids. 
"No licence" does not mention anything expressly, nevertheless it has rules assigned with it.

See http://archive09.linux.com/articles/56426 or http://earthethics.org.in/products/peaceful-open-source-license

**Comment by WhyNotHugo** [comment]
There are currently no licenses that forbid military use, or gun manufacturing, forest cutting, and plety of other unethical activities. There's no point indicating that no license forbids it, since none of the present licenses forbid ANY of those things.

**Comment by haacked** [comment]
In fact, a license that did forbid any use would not be considered an open source license per the [open source definition](http://opensource.org/osd-annotated)

It's clear in points 5, 6, and 9.

> 1. No Discrimination Against Persons or Groups
> 2. No Discrimination Against Fields of Endeavor
> 3. License Must Not Restrict Other Software
