### ISSUE TITLE
Add limitations: suitable-for-code | suitable-for-creative options

### ISSUE THREAD

**Issue by ShaneCurcuru** [github/choosealicense.com#404]
While non-software.md addresses the question of how different licenses are meant (or not meant) for code vs. docs/other things, it's not yet captured as structured data in the license files.

The simplest proposal is adding limitations: suitable-for-code, suitable-for-creative

suitable-for-code means it's recognized as applicable for software code or other places where you'd find patents and other "IP" stuff.  If that flag is _not_ present, then add a note to the page stating so.  While that's an additional UI flag to add, I believe it's an important one, because some licenses specifically say they should not be used for code.  Someone with a code repo probably should not choose CC-BY-SA-4.0, for example.

suitable-for-creative means it's useable for creative things like documentation, images, and the like.  That might be harder to get agreement on for all licenses, but even having enough of a limitation tag that gets people thinking about this would be valuable.

Speaking of which, why don't you include GNU FPL?  While it's not a mainstream code choice, it is an important documentation choice, and with the number of people using their gh-pages as a blog or public slide deck, it should be an important choice to give people.
https://www.gnu.org/licenses/fdl-1.3.en.html

Thanks for considering the idea!

**Comment by mlinksva** [comment]
This would not be appropriate for `limitations:`, which list things licenses explicitly don't grant.

A new `categories:` field might work, but I'm pretty skeptical of separating code from 'creative', especially using the latter word. Most 'software' licenses are just fine for 'creative' works. Something capturing 'not-recommended-for-software' might be more acceptable, but patent exclusions can be bad for other fields too, such as hardware designs.

As for the GNU FDL, nobody has submitted it. It probably qualifies per our [criteria](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license). I think it's a bad choice for documentation or anything else. Use GPLv3 if you want a source-requiring copyleft license. But feel free to create a PR to add it to `_licenses`.

**Comment by mlinksva** [comment]
Closing as I don't see anything actionable right now but feel free to re-open or open new issues or pull requests.
