### ISSUE TITLE
Appendix indicators should have hover help text

### ISSUE THREAD

**Issue by benbalter** [github/choosealicense.com#407]
Like when you hover over the icons elsewhere:

![screen shot 2016-05-10 at 1 30 43 pm](https://cloud.githubusercontent.com/assets/282759/15156090/694f5dd8-16b3-11e6-8a21-70077b63b301.png)

**Comment by mlinksva** [comment]
Pointer on where to look to begin implementation from https://github.com/github/choosealicense.com/pull/406#issuecomment-218225779

> Note that I've not made the license property tooltips you can see eg in /licenses or on individual license pages work (hover over eg "commercial use" on one of those pages). The CSS and Javascript (relevant files are `assets/css/application.scss` and `assets/js/app.coffee`) for those tooltips currently require a specific structure with bullets, but probably could be made more flexible. An alternative that might even be more useful would be a legend.
