### ISSUE TITLE
Difference between GPLv3 and LGPLv3 not modeled

### ISSUE THREAD

**Issue by mlinksva** [github/choosealicense.com#410]
"The table shows no difference between GPLv3 and LGPLv3?" - https://twitter.com/weigandtLabs/status/730676399678324736

It's true, we don't make any attempt to model the different scopes of derivative works that license conditions apply to. I don't know of any attempt to model these differences (pointers wanted). I've seen many times where the differences are important, people categorize licenses, often as "strong" or "weak" copyleft, but that's different from modeling the differences.

I'd planned to bring this up eventually as a use case for potentially adding some kind of qualifiers to our currently boolean (present or not) permissions, conditions, and limitations described in `_data/rules.yml`. But I'll take above question as opportunity to sketch out solutions to modeling the differences between GPLv3 and LGPLv3, and a bit more.

(1) qualified closed source derivatives permission

We could have a `closed-derivatives` permission, which [lax] permissive licenses (eg MIT) would have without qualification, and would be completely absent from strong copyleft (eg GPLv_) licenses. Qualifications could be something like `larger-works` (eg LGPLv_), `other-modules` (EPL-1.0), and `other-files` (MPL-2.0).

To minimize changes, the "qualifications" would actually be new fields described in `_data/rules.yml` with some naming convention, e.g., `closed-derivatives:larger-works`. Display code would recognize those different fields as qualifications and render in same place unqualified field would be rendered, probably accompanied by a yellow or yellow-green circle instead of green.

I think this could be useful to users: whether closed (alternatively, proprietary) derivatives are permitted is something people want to know, whether their aim is to prevent or allow closed derivatives, and a key difference among licenses, and choosealicense.com doesn't directly state this key difference. One has to ponder the implications of `same-license` to really get it.

Calling out whether proprietary derivatives are [dis]allowed mentioned in the talk referenced at https://github.com/github/choosealicense.com/issues/335#issuecomment-191952315 and license decisions being motivated by this question documented in paper referenced at https://github.com/github/choosealicense.com/issues/335#issuecomment-210152954

Just to state the obvious:
- `closed-derivatives` would be permission to distribute such; making such permitted by all open licenses; description could state that
- could directly qualify `modifications`; this would be somewhat confusing due to the point directly above, and might needlessly anger copyleft advocates (copyleft licenses would get a yellow bullet for that field).

(2) qualified same license condition

The existing `same-license` condition could be qualified. Probably strong copyleft and permissive licenses would see no change, but weak copyleft licenses would be qualified similarly to above, with "only" replacing "other", with the blue bullets getting lighter.

Relative to (1) this would be a smaller change and would make the model a bit more precise but not make the key difference among licenses mentioned above any more explicit.

(3) categories

Categorize to capture interesting features, but don't try to model those features. Display categories wherever license info is displayed, along with permission/condition/limitation fields. As mentioned above, this is an approach others have taken (e.g., "strong copyleft", "weak copyleft"). Categories could have [additional uses](https://github.com/github/choosealicense.com/issues/404#issuecomment-217277778).

Categories could even be used by display code to change the rendering of modeled fields -- achieving same display impact as (2).

(4) descriptions

No change. Don't attempt to model or display graphically differences  more subtle than those we already model and display. Mention those differences where possible in textual descriptions. #396 attempts to make sure those differences are described accurately in text, but needs work to be readable.

I don't plan to work on any of 1-3 soon but would enjoy feedback, other ideas, even speculative pull requests.

**Comment by waldyrious** [comment]
Unless such qualifiers happen often enough across the included/eligible licenses, I am not sure defining specific fields for them is a good architectural choice. I like how Wikipedia does with comparison tables, where they use "yes", "no" and "partial" cells, with references (footnotes) to explain what the "partial" refers to. This is also the approach used by caniuse.com, IIRC. If I'm reading you correctly, it would correspond to option (4).

This would be more scalable than specific fields, since additional nuances could be added in the future (and even to "yes"/"no" columns). However, it wouldn't be machine-readable, which is a pity. I am not familiar with SPDX except at a very superficial level -- I wonder if we could leverage that to depict the differences in a machine-readable way, and whether we'd have a way to keep that representation synced with the footnotes somehow.

**Comment by mlinksva** [comment]
(4) above just means any subtle differences need to be described in the description field and couldn't be rendered in any table (well, descriptions could be parsed...), ie no change.

If I were designing this fresh (call it option 5) it'd be machine-readable and allow for non-boolean fields. Each of permissions/conditions/limitations would be a dictionary rather than an list. (And I'd probably make even the boolean ones mandatory for all licenses - have to specify true or false, rather than absence meaning false - to make it harder to make mistakes of omission when describing a new license.)

(1-3) above are different ways of allowing for non-boolean values in a non-general fashion.

I didn't specify (5) above because I first wanted to explore how differences between LGPLv_ and GPLv_ and perhaps others should be displayed (or not) to choosealicense.com users, but I realize as I'm typing this that I dwelled on implementation anyway. Feedback on display requirement or lack thereof (and/or argument that machine-readable expression of these differences should be a requirement) as well as implementation wanted.
