### ISSUE TITLE
BSD missing

### ISSUE THREAD

**Issue by orome** [github/choosealicense.com#427]
Was BSD removed for some reason? I don't see it on either of the pages listing license options.

**Comment by parkr** [comment]
Hey, did you see https://github.com/github/choosealicense.com/issues/413? I think it provides an adequate answer but write back if not!

**Comment by orome** [comment]
@parkr: The reasoning in #413 makes no sense. The title of the site notwithstanding, I expect it is being used as a reference as well a license selection, so _any widely used license should be prominently listed_. Moreover, for anyone like me who used the site to choose the BSD when it was listed, its more than a bit of "cognitive overhead" to come bask to the site and find its no longer a choice. 

(Not to mention the fact that MIT and BSD are different enough that they should be listed as choices too.)

**Comment by mlinksva** [comment]
I understand your complaint. I hate it when information moves around or disappears from sites. I usually deal with it through the likes of https://www.google.com/#q=site%3Achoosealicense.com+bsd and http://web.archive.org/web/*/choosealicense.com/licenses but this is overhead.

But the main purpose of the site is what the title says, not to serve as a reference. The set of licenses featured on the home page or /licenses will change if better options arise or our understanding of the existing choices and developer choices changes. That means some licenses that were listed on those pages won't be at some point in the future.

I've added http://choosealicense.com/appendix to serve as an internal reference, but you're much better off with one of the sites listed at http://choosealicense.com/about/#additional-resources if you want a list of all widely used licenses.

I'm glad that you have used the site previously to choose BSD-3-Clause (I'm guessing from looking at one of your repos). Keep using it, it's a fine license.

But we disagree concerning "the fact that MIT and BSD are different enough..."  Each of the licenses listed on http://choosealicense.com/licenses/ produces a significantly different arrangement of rights (or privileges or rents if you prefer pejorative terms)  such that each step up or down the list is infeasible for some users, for business or moral reasons, and in a private licensing context, would require substantial $ between parties to transfer said rights. Such a gulf between MIT, BSD-2/3-Clause, and ISC does not exist. There's no reason for someone choosing a license to figure out the minor differences among them, or just choose one based on which has a better sounding name (aside: I sometimes wonder whether MIT's popularity stems from its unambiguous and very high prestige name; BSD doesn't quite so strongly signal UC Berkeley, and that university is slightly lower prestige than MIT). So we only list MIT prominently.

**Comment by orome** [comment]
That makes sense, given the purpose of the site. But I didn't see a path from the main page to the appendix (or any path to BSD-3 at all for that matter). Some kind of link from the main page would not only address that, but also expand the utility of the site. I understand the desire to keep things narrowly focused on "choosing"; but a simple "reference" or "comprehensive list" link to the appendix would make the site a reverence as well, without compromising or diluting its primary purpose, and would provide a home for licenses that people have chosen using the site in the past, but that cannot now be easy recovered.

**Comment by mlinksva** [comment]
There is a path, but it's long and non-obvious... / -> /licenses -> /about (link at bottom of /licenses) -> /appendix

Not sure it's the right thing to do, but I made a PR that attempts to improve your use case as you say "without compromising for diluting its primary purpose", see #428 and further feedback most welcome.
