### ISSUE TITLE
Following SPDX standard for license names / IDs

### ISSUE THREAD

**Issue by camillem** [github/choosealicense.com#43]
Hi,
In order to avoid ambiguity and facilitate interactions with other projects, it would be nice to use the de facto standard for license names and IDs as defined by the SPDX project. see https://spdx.org/licenses/
Cheers, 
Camille

**Comment by haacked** [comment]
Interesting idea! Mind submitting a pull request so we can see exactly what it would entail and discuss the specific change?

**Comment by jlovejoy** [comment]
I concur!  OSI and Debian have already adopted the SPDX short identifiers and we (the SPDX Legal Team) are in the process of trying to sync with other community lists as well.  For the sake of efficiency and clarity, the more people/projects using the same list and references, the better.  SPDX also has  .txt files and a canonical url for each license (generated from the .txt file) - I don't know if that would help here, but I wanted to mention it as I know how difficult it is to maintain such files and if there's a way to collapse that effort, it might be worth looking into.

IANAD, but from a high-level view, I think the main changes would come in the form of replacing the short names on this page: http://choosealicense.com/licenses/ and the corresponding individual license pages with the SPDX short identifiers and then doing the same in the drop-down menu that appears when one creates a new project.

Cheers,
Jilayne
SPDX Legal Team co-lead

**Comment by camillem** [comment]
@Haacked Glad you like the idea :-) I won't have much internet access over the week-end but I should be able to send you a PR on monday.

**Comment by haacked** [comment]
@camillem great! I look forward to checking it out.

**Comment by camillem** [comment]
@Haacked Done. (see https://github.com/github/choosealicense.com/pull/63 )
