### ISSUE TITLE
Hard to find this repo from site

### ISSUE THREAD

**Issue by mlinksva** [github/choosealicense.com#431]
It's mentioned on /about but something in footer might be appropriate.

Maybe change add "and you" to " Curated with <3 by GitHub, Inc." and link to the repo? Our add a "Source" link next to "About"?

A GitHub logo is often used to link to a project repo, but that means bringing in octicons files into the project, not sure if worthwhile.

**Comment by mlinksva** [comment]
As suggested by @saraford, thanks!

**Comment by waldyrious** [comment]
I rather like the "and you" approach!

**Comment by mlinksva** [comment]
Another (perhaps complementary) approach is a link to edit the page being displayed. Maybe that would generate lots of spurious pull requests for this site, but maybe worth trying anyway. How-to: http://ben.balter.com/2015/09/13/github-pages-edit-button/

**Comment by waldyrious** [comment]
> Another (perhaps complementary) approach is a link to edit the page being displayed. 

Even better :D Sort of an "edit this page" link, like Wikipedia ;)

**Comment by mlinksva** [comment]
Fixed by #432

**Comment by mlinksva** [comment]
& above improve this page option is a new issue: #433
