### ISSUE TITLE
Improve this page link

### ISSUE THREAD

**Issue by mlinksva** [github/choosealicense.com#433]
As noted in https://github.com/github/choosealicense.com/issues/431#issuecomment-225465094

> Another (perhaps complementary) approach is a link to edit the page being displayed. Maybe that would generate lots of spurious pull requests for this site, but maybe worth trying anyway. How-to: http://ben.balter.com/2015/09/13/github-pages-edit-button/

Opening a new issue to track as suggested by @saraford in https://github.com/github/choosealicense.com/pull/432#issue-160012085

**Comment by rishacha** [comment]
Is this still open? Can I take this up?

**Comment by mlinksva** [comment]
@rishacha yes.

**Comment by rishacha** [comment]
Shall I add it to the sidebar ?
