### ISSUE TITLE
Identify which licenses are viral so it is clearer

### ISSUE THREAD

**Issue by walchko** [github/choosealicense.com#437]
I like your review of licenses, but it isn't clear to me looking at either the text or the bullets on the [license page](http://choosealicense.com/licenses/) which ones are viral. It should be clearer that if you choose AGPL or GPL, they require source code release for all code which uses/touches your code. This could limit sharing, because people, groups, or companies may not what to be forced to share source code they build on top of your code. This would educate people who want maximum sharing to move to a more permissive license (i.e., MIT, Apache, etc). Maybe include another bullet to the right for viral:
- viral -> anyone who uses your code **must** open source their code too, even if they just interact with it over the network (AGPL) or link to your library (GPL)
- non-viral -> if you link to a library, you don't need to share (LGPL) unless you modify the library 

Now you may think you already do this, but looking at the licenses, I see little to no difference between GPL and LGPL unless I really study it (or already know the difference) ... LGPL is not viral like GPL.

**Comment by mlinksva** [comment]
"Viral" is taken by copyleft fans as a pejorative description. Using the term would not help the site's aim to be a "non-judgemental".

You're right though, the difference between [A]GPL and LGPL is not adequately modeled. There's an issue for that: https://github.com/github/choosealicense.com/issues/410

The difference is noted in the description of each license (search for "larger work").

I appreciate your close inspection of the site and feedback. Thank you! I'm not going to add a "viral" condition, but feel free to suggest other approaches in #410.

**Comment by walchko** [comment]
sorry, never took "viral" as pejorative but descriptive.

I guess I am too simple, because "larger work" doesn't really mean anything to me ... it is vague and not clearly defined. New people may not understand the nuances between these. Maybe define what "larger work" means? At the end of the day I know:
- AGPL - touch AGPL code via network, all source code released
- GPL - link to a GPL library, all source released
- LGPL - modify library, only that library code is released

Again, "viral" is a good description and not a judgment. I can't think of a better word ...
Have a nice day!

**Comment by mlinksva** [comment]
FWIW you can read about longstanding debate over the term in https://en.wikipedia.org/wiki/Viral_license ... personally I think it's too bad copyleft advocates haven't embraced the term as aspirational.

I also welcome pull requests for improved descriptions and entries for a potential glossary https://github.com/github/choosealicense.com/issues/238

**Comment by maeichris** [comment]
In my experience, this aspect of GPL/AGPL is the most significant clause that might lead a business to avoid choosing to use a piece of open source software.  Thus, the goal of this site is not really fulfilled if the main reason a large group of people would avoid using a piece of open source software is not indicated here.

Basically, GPLv3 section 5c indicates the mere use of a GPL component makes the using software a derivative, and requires the using software to be re-licensed as GPL.  While this is seen as a virtue to open software purists, this is wholly unacceptable to many commercial businesses as well as open source developers that don't want their license changed.  The distinction is critically important to many people, and the costs of not knowing about or understanding that distinction are very high.

If "viral" is an unacceptable term, then how about "appropriative", "absorbing", or "annexing"?  Other words seem more accurate ("take over", "usurp", "commandeer", "expropriate", "hijack", "consume"), but would probably be less acceptable.

The alternative is to go with "viral".  It is accurate.  Put it in the hands of the GPL advocates to come up with an alternative that is both accurate and acceptable to commercial interests.

**Comment by ranolfi** [comment]
> viral -> anyone who uses your code must open source their code too, **_even if they just interact with it over the network_** (AGPL) or link to your library (GPL)

> AGPL - **_touch AGPL code via network, all source code released_**

Note that these assertions are false and based on a poor understanding of the AGPL.

The AGPL has one single additional clause to the GPL, and that is: If you don't release your software but make it available over a network, this is considered a form of distribution and thus you're required to release it as open source. That doesn't mean that anyone who is **_consuming_** your program over the network is subject to the same requirement at all.

> non-viral -> _**if you link to a library, you don't need to share (LGPL) unless you modify the library**_

This is also based on a misunderstanding of the LGPL. It is only true if you're talking about **dynamic linking**. If you statically link to a library, the LGPL won't do.
