### ISSUE TITLE
Replace the 2-clause BSD license with the ISC license

### ISSUE THREAD

**Issue by WhyNotHugo** [github/choosealicense.com#44]
The ISC license is a functionally equivalent and the prefered form of the 2-clause BSD license. [[1](http://en.wikipedia.org/wiki/ISC_license)][[2](http://www.openbsd.org/policy.html)]
There's no point recomending the 2-clause BSD license at this points, even projects initially written under the 2-clause BSD license are now suggesting new code use the ISC license.

**Comment by haacked** [comment]
Let's continue the discussion in #50

**Comment by benbalter** [comment]
Fixed via https://github.com/github/choosealicense.com/pull/50.
