### ISSUE TITLE
Website requires propietary software

### ISSUE THREAD

**Issue by WhyNotHugo** [github/choosealicense.com#45]
In it's infinite irony, this website seems to constantly prompt me to install flash. (ie: visit http://choosealicense.com/licenses/mit/, and a "plugin missing" bar will appear on firefox).

**Comment by haacked** [comment]
I don't see the irony. Proprietary is a valid life choice as is open source. :wink:

Unfortunately, there's no way to make "copy to clipboard" work across the majority of browsers without using Flash. However, someone opened issue #26 to address that so hopefully we can get that fixed.

If you have time to test that PR or review it, that'd be a great help! Thanks!

**Comment by WhyNotHugo** [comment]
While propietary is a valid life cycle, it's ironical that a website helping developers to choose Open Source Software license actually relies on propietary software to work correctly.

There's the HTML5 clipboard API, which at least two major browsers implement.

**Comment by haacked** [comment]
Maybe I didn't communicate this well, but the goal of the site is to inform developers about their choices when choosing a license. We don't think developers should just give up their rights to their code willy nilly, hence we include "no license" as an option.

But yes, the site does focus primarily on open source.

> There's the HTML5 clipboard API, which at least two major browsers implement.

That's great! Perhaps you'd be willing to submit a PR so we can use that for browsers that support it and fallback to the existing flash mechanism for browsers that do not.

**Comment by tekkub** [comment]
The ZeroClipboard folks (which is what we're using here, of course) have been looking into this stuff recently.  You can see what they've discovered in [their issue](https://github.com/zeroclipboard/ZeroClipboard/issues/171)

**Comment by WhyNotHugo** [comment]
Still an issue 20 months later. Hovering the mouse over the button puts some an object tag in front of it (flash, I think, though I've no way to be sure), making the browser cover the button in a dark gray overlay and the button unclickable:

![2015-03-14-090207_1920x1080_scrot](https://cloud.githubusercontent.com/assets/730811/6651629/a8f847ba-ca29-11e4-9eb5-94c4ab79e2a0.png)

Stuff like this is most likely to drive people _away_ from choosealicense.com, rather than motivate them to pick a licence and share their software.
