### ISSUE TITLE
Suggestion: add a diagram of the spectrum to the /licenses page

### ISSUE THREAD

**Issue by waldyrious** [github/choosealicense.com#457]
[This image](https://commons.wikimedia.org/wiki/File:Software-license-classification-mark-webbink.svg), used in the Wikipedia article "[Free software license](https://en.wikipedia.org/wiki/Free_software_license)", would be a good choice IMO, or something along those lines. This would make it more evident what the page aims to provide.

![](https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Software-license-classification-mark-webbink.svg/600px-Software-license-classification-mark-webbink.svg.png)

**Comment by mlinksva** [comment]
It'd need some design work but I think an image like that would work better on a (not yet existing) page for people wanting more background eg a glossary discussed in #238. I don't think this is immediately actionable so closing but feel free to continue discussion. Thanks for the suggestion!
