### ISSUE TITLE
Promotes the SIL OFL which is non-free

### ISSUE THREAD

**Issue by luke-jr** [github/choosealicense.com#460]
The OFL doesn't allow sale of the font by itself, so it doesn't meet the free software definition and shouldn't be promoted. The MIT and GPL licenses are popular among fonts.

**Comment by mlinksva** [comment]
It meets our [criteria](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license). Note https://www.gnu.org/licenses/license-list.en.html#Fonts

> The Open Font License (including its original release, version 1.0) is a free copyleft license for fonts. Its only unusual requirement is that when selling the font, you must redistribute it bundled with some software, rather than alone. Since a simple Hello World program will satisfy the requirement, it is harmless. Neither we nor SIL recommend the use of this license for anything other than fonts.

It is also listed on https://opensource.org/licenses/category

Convince FSF and OSI that it is non-free/open and maybe we can remove it here.

Closing, but please say if I missed something.

**Comment by mlinksva** [comment]
I see in https://github.com/googlei18n/noto-fonts/issues/758 that you know all that and disagree.

I agree with davelab6, that ship has sailed. He's been working on free fonts for over a decade. If there was a non-theoretical problem with SIL OFL I'm sure he'd be the first to say.
