### ISSUE TITLE
Antivirus blocks some website pages

### ISSUE THREAD

**Issue by tajmone** [github/choosealicense.com#461]
While navigating choosealicense.com I was surprised to discover that my antivirus (VIPRE) blocked the GPL 2.0 webpage:

http://choosealicense.com/licenses/gpl-2.0/

It reporeted

> BLOCKED WEBSITE
> Visiting this site might harm your computer!
> To protect you, VIPRE has blocked this potentially harmful content.

So far, only this page was blocked. Is there something different about it? Was the website hacked?

Just thought I let you know.

**Comment by mlinksva** [comment]
@tajmone thanks for reporting this. There doesn't seem to be a problem with the material in the repo or being served. A colleague has reported a false positive to the vendor you mentioned.
