### ISSUE TITLE
How to specify EUPL in new project

### ISSUE THREAD

**Issue by miqmago** [github/choosealicense.com#479]
I want to start a new project and I would like to choose EUPL license but in the dropdown "Add a license" there is no possibility to do it, even though the license is listed in https://choosealicense.com/appendix/.

How can I specify EUPL when I create a new github repo?

**Comment by mlinksva** [comment]
Copy the license text from https://choosealicense.com/licenses/eupl-1.1/ (you can use the "copy license text to clipboard" button, or select and copy the text manually) into a file called `LICENSE` after creating the repo.

**Comment by miqmago** [comment]
Thanks, that's what I did, but I wanted to know if there is the possibility to choose it from the github interface dropdown.

If I understand, the way you say means that 6 steps have to be done:
1. choose a repo with no license (or with any other license),
2. create a file called LICENSE (or open the file),
3. in a new window, open the link (that I have to remember where it is, maybe more steps needed here)
4. copy the text from a link,
5. paste the clipboard into LICENSE file,
6. commit the changes.

I was asking if this can be reduced to 1 step:
1. choose EUPL license

**Comment by mlinksva** [comment]
No there isn't currently the possibility to choose EUPL-1.1 from the drop down. I'll pass along your request.

**Comment by miqmago** [comment]
Thanks, this is worst than I thought, as if I select a license in the dropdown, the selected license will appear in the repo first page, linked to the selected license and I haven't found the way to change it.

**Comment by mlinksva** [comment]
If you've selected a different license, edit the `LICENSE` file: replace the license text there with the license text of the EUPL-1.1.

**Comment by miqmago** [comment]
Oh! great, thanks! I thought that it was already changed but in fact it was not...
