### ISSUE TITLE
Proposed modified workflow: make permissive/copyleft and patents orthogonal

### ISSUE THREAD

**Issue by gerv** [github/choosealicense.com#48]
There's no point producing a patch for this without some agreement, hence an issue rather than a pull request :-)

The initial 3-way choice, while having the desirability of 1-click licensing choice, means that anyone concerned about patents will end up with Apache 2.0, whereas the GPLv3 also has patent language (and, the FSF would say, GPLv2 has an implied patent licence). In fact, the GPLv3's patent language is significantly stronger than that of the Apache licence, because redistribution means a licence is granted; you don't have to modify, and the patented code doesn't have to be part of your modification. So the patent protection for developers and users is a lot larger.

The best solution would be to say (as we do at Mozilla) that patent language is a necessary requirement for a modern open source licence, and in 2013 no-one should recommend a licence without it. That would simplify the choice down to Apache 2.0 or GPLv3+.

However, if that's a step too far for Github, could we instead have the following workflow?
1. A: "I want it simple and permissive" vs. B: "I want others to share their improvements"
2. A: "I'm not worried about patents" vs. B: "I want to try and avoid patent lawsuits"

A. A. would be MIT (or 2-clause BSD, or ISC, or whatever)
A. B. would be Apache 2.0
B. A. would be GPLv2+
B. B. would be GPLv3+

Gerv

**Comment by ghost** [comment]
FWIW, +1 to both options proposed, any would be better than the current status IMHO. The homepage intends to cover 99% cases (according to goals) and it's implying that if you care about patents, you have AL 2.0.
Entirely agree that permissive/copyleft and patents are orthogonal concerns, and the homepage doesn't fit that.

A 3rd option: (or 2.5 :smile:)
- homepage with two choices, "I want it simple and permissive" vs "I want others to share their improvements".
- first choice paragraph presents MIT or AL 2.0, and states that AL 2.0 is also permissive but it contains patent language.
- second choice paragraph presents GPL v2+ or v3+, and adds explicit patent protection for v3 short presentation.

(equivalent with 2nd, but a smaller step)

**Comment by haacked** [comment]
What if we simply added a clause to the GPL description that it also includes patent language?

**Comment by gerv** [comment]
That would be _slightly_ better, but it would still preserve the idea that you have to choose between "I care about patents" and "I care about sharing improvements", whereas the two concerns are orthogonal.

I still maintain it is no longer good practice in 2013 for anyone to recommend that new OSS projects use a licence without an explicit patent clause. Github should lead from the front here, and recommend Apache 2 as their permissive licence, and GPLv3 as their copyleft licence. That would simplify the chooser, and remove the "I care about patents" question entirely - because _everyone_ should care about patents.

**Comment by benbalter** [comment]
@gerv still interested in seeing this forward?

**Comment by gerv** [comment]
I'm very busy, as can be seen from the delay in commenting here (I was travelling last week), but yes, I'm still interested in taking this forward. How can we do that?

(I don't seem to have power to reopen this ticket.)

**Comment by gerv** [comment]
benbalter: So where do we go from here? This change would be fairly significant - cutting down the opening options from 3 to 2 - Apache for permissive and GPLv3 for copyleft. Who would need to sign off on that?
