### ISSUE TITLE
LICENSE not match

### ISSUE THREAD

**Issue by willin** [github/choosealicense.com#481]
https://github.com/js-cool/leader.js.cool/blob/master/LICENSE 

what i use in the project is `Attribution-NonCommercial-ShareAlike 4.0 International`

but project page shows: ***CC-BY-SA-4.0***

<img width="356" alt="wx20170216-002830 2x" src="https://cloud.githubusercontent.com/assets/1890238/22983963/dca07750-f3de-11e6-9d95-63c190ff8455.png">

**Comment by mlinksva** [comment]
@willin license detection on GitHub is handled by [licensee](https://github.com/benbalter/licensee/) please add your report to https://github.com/benbalter/licensee/issues/116. Thanks!
