### ISSUE TITLE
HTTP Strict Transport Security

### ISSUE THREAD

**Issue by strugee** [github/choosealicense.com#483]
Please deploy HTTP Strict Transport Security to choosealicense.com, preferably with a long lifetime and with a submission to the preload list. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

Cheers!

**Comment by mlinksva** [comment]
Thanks for the suggestion @strugee. I've passed it along to the team in charge of infrastructure for GitHub-maintained GitHub Pages sites. Closing this issue as there's nothing that can be done to fix it in the repository itself. I'll drop a note here if I hear it has been implemented.

**Comment by strugee** [comment]
:thumbsup: thanks!

**Comment by mlinksva** [comment]
@strugee HSTS is now deployed for choosealicense.com with 1 year lifetime thanks to @parkr and others.
```
$ curl -I https://choosealicense.com/no-license/
HTTP/1.1 200 OK
Server: GitHub.com
Content-Type: text/html; charset=utf-8
Strict-Transport-Security: max-age=31557600
...
```
