### ISSUE TITLE
Add StopNerds Public License

### ISSUE THREAD

**Issue by hook321** [github/choosealicense.com#485]
[http://stopnerds.org/license/](http://stopnerds.org/license/)

**Comment by mlinksva** [comment]
@hook54321a thanks for the suggestion, but it doesn't look like this license meets our [criteria](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license) (SPDX ID, on one or more of OSI, FSF, Open Definition approved lists, >1000 repos).
