### ISSUE TITLE
AL2 description

### ISSUE THREAD

**Issue by apotheon** [github/choosealicense.com#493]
The description of the Apache License 2.0 on the index of the choosealicense.com website reads:

> The Apache License 2.0 is a permissive license similar to the MIT License, but also provides an express grant of patent rights from contributors to users.

This is inaccurate, in that it is markedly different from the MIT License.  It contains several restrictions the MIT License lacks, including a NOTICE file restriction and a requirement for bookkeeping related to changes made to the source code, and it has significant license compatibility problems (including incompatibility with many GNU licenses) where the MIT License has (nearly?) no license compatibility problems.

This misleading description should be altered to reflect the fact it is about as much like the Mozilla Public License, or the Q Public License, as it is like the MIT License.

**Comment by mlinksva** [comment]
Apologies, I never acknowledged this here, though looks like I did reference it in #429. What constitutes "similar" or "markedly different" is debatable, but I'd like to eliminate the home page description you're mentioning by removing Apache-2.0 from the home page.

If you want to suggest an alteration in the meantime, feel free to suggest here or make a PR.

**Comment by apotheon** [comment]
Ideally, I'd like a more fully permissive license with a patent clause to be included at whatever level you raise patent concerns, such as the [COIL](http://copyfree.org/content/standard/licenses/coil/license.txt), but I don't think anything that fits those requirements also meets the qualifications for inclusion in the choosealicense.com list.

I have a lot of commentary I could add to the discussion on #429, but my more reasonable side realizes it would probably be mostly noise to drown out the signal, so I'll just say here that I think it's an improvement, with potential for tightening up language around the "I feel" stuff mentioned in discussion there and the lightbulb icon.  I'd prefer you don't get too distracted by bikeshedding before updating the site.  Maybe it's time to ask whether there's anything so critical to change that further discussion can't be put off until after deploying this update.

In any case, I think that once your revised homepage goes live it solves the AL2 description problem.  Thanks for your attention to this.
