### ISSUE TITLE
Can no longer choose CC0 on GitHub.

### ISSUE THREAD

**Issue by MicahZoltu** [github/choosealicense.com#496]
My understanding is that GitHub populates its list of licenses on new repositories from here.  I used to be able to select CC0 as a license, but it appears that I no longer can.  I [found this issue](https://github.com/github/choosealicense.com/issues/413), which appears to be related, but it ended by being locked with a comment pointing at this statement:
> I don't believe it's going to be to difficult to modify the behaviour of the license picker so that you can type BSD (or whatever other license you like from this list) and have that populate the repository. We'll take a look at doing this 🔜 but it's likely going to be another week or two before we can get to this.

That was 7 months ago.  What is the status of this?

If CC0 being missing from GitHub is a different problem, why isn't it showing up anymore?

On a related topic, I searched through the history of this repo and I can't figure out why Unlicense was chosen in favor of CC0 for the "Public Domain" recommendation option.  I'm not looking to start another licensing debate here, I just want to understand the reasoning better (even if that reasoning was just, "we flipped a coin").  Without any context, it looks like some maintainer just did a couple opinionated ninja commits that removed CC0 from everything but the hidden list without any discussion.  My understanding is that CC0 is considered to be more robust across a wider array of jurisdictions while attempting to achieve the same results.  It is also recommended by FSF for [GPL compatibility](https://www.gnu.org/licenses/license-list.en.html#CC0).

**Comment by mlinksva** [comment]
@MicahZoltu https://github.com/github/choosealicense.com/pull/386#issuecomment-207579290

As to the new repo license drop-down on github.com, I'll pass your feedback along. Enhancement of that UI is something we're discussing, but I can't make any promises.

I'm going to close as there's nothing immediately actionable in this repo, but feel free to comment further.

**Comment by jcayzac** [comment]
Any news on this? @mlinksva

**Comment by mlinksva** [comment]
Update -- though there's no UI to choose CC0-1.0 from, you can load the license up in the chooser with the following (replace `<user>` and `<repo>` with yours):

```
https://github.com/<user>/<repo>/community/license/new?branch=master&template=cc0-1.0
```

**Comment by rajesh-nayak-cms** [comment]
@mlinksva  Did anyone try this workaround described above? It did not work for me.

**Comment by mlinksva** [comment]
@rajesh-nayak-cms I've tried it personally. If you send details on what you're seeing to https://github.com/contact you should get help, or confirmation that you've found a bug that I haven't been able to trigger. :smile:

**Comment by rajesh-nayak-cms** [comment]
Please see attached.
![selection](https://user-images.githubusercontent.com/34520390/34878557-8b981b30-f778-11e7-964f-d472699fdec1.jpeg)

**Comment by mlinksva** [comment]
@rajesh-nayak-cms the workaround mentioned at https://github.com/github/choosealicense.com/issues/496#issuecomment-341561904 is for an existing repository. I don't believe there's a similar workaround for the new repo form. But you can create a new repo without a license and then use the workaround to add CC0-1.0.

**Comment by rajesh-nayak-cms** [comment]
Can you please elaborate "load the license up in the chooser "?  Not seeing it.

**Comment by mlinksva** [comment]
@rajesh-nayak-cms go to https://github.com/rajesh-nayak-cms/test/community/license/new?branch=master&template=cc0-1.0 (I filled in values for your username and a repo I see you have called `test`).

You should see CC-1.0 on the page, ready for you to review and submit.

**Comment by rajesh-nayak-cms** [comment]
Worked! Thanks for your support

**Comment by answerquest** [comment]
I found this thread while searching similarly like @rajesh-nayak-cms . I'll use the workaround for now, but I support @MicahZoltu 's point. When I click the info icon, I get the <choosealicense.com> site and it's not even explaining any of the other licenses mentioned in the dropdown. 

When I click on the link under "My project isn't software", [this page](https://choosealicense.com/non-software/) tells about licenses that don't even exist on the dropdown menu! And it doesn't even say that I can choose Unlicense.. I cannot find any explanation for that anywhere. If you're not going to explain it then how do you expect me to choose it? And this link that @mlinksva shared which can be a workaround isn't even shared anywhere on that site. 

Folks, you have a search-as-you-type box here. There's no need to be picky or politically correct here. Providing a choice does NOT equate to blind endorsement. You can put disclaimers below. Just put all the damn licenses there, and give links to original sites of all of them on choosealicense.com and get on with life.

#FreeTheLicenses

**Comment by liuchong** [comment]
> @rajesh-nayak-cms I've tried it personally. If you send details on what you're seeing to https://github.com/contact you should get help, or confirmation that you've found a bug that I haven't been able to trigger.

Thanks @mlinksva

**Comment by mfernandes61** [comment]
Try this 'clunky' work-around. If you create a license.txt or license.md you will have a 
license button appear.
Click on it and click on one of the 'wrong' licences. Examine URL for page.
Edit end of URL to have the template=cc0-1.0 as mentioned above. Hit enter
and the CC licence appears...
