### ISSUE TITLE
Add Vim License

### ISSUE THREAD

**Issue by othree** [github/choosealicense.com#498]
Vim uses a special GNU GPL [compatible][1] license called: [Vim License][2].
There are many Vim scripts [use][3] [the][4] [same][5] license.
I think it will be great if you can provide (and detect in GitHub).

[1]:https://github.com/vim/vim/blob/master/runtime/doc/uganda.txt#L115-117
[2]:https://github.com/vim/vim/blob/master/runtime/doc/uganda.txt#L24-L105

[3]:https://github.com/tpope/vim-pathogen#license
[4]:https://github.com/mileszs/ack.vim/blob/master/LICENSE
[5]:https://github.com/kien/ctrlp.vim/blob/master/doc/ctrlp.txt#L1262

**Comment by mlinksva** [comment]
@othree, thanks for the suggestion.

Deployment of this license seems highly variable, with lots of text added before and after in examples I've seen -- these wouldn't be detected. Can you verify that it meets our [criteria](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license) for cataloging a license here, and point out some examples that use only the [license text](https://spdx.org/licenses/Vim.html#licenseText) in a `LICENSE` file such that they could be detected?

If so feel free to make a pull request to add the license.

**Comment by othree** [comment]
Hi

Sorry I almost forgot about this issue.
I have checked the criteria, yes Vim fits:
* SPDX Identifier: Vim
* GNU's free licenses <https://www.gnu.org/licenses/license-list.en.html#Vim>
* More than 1000 results 
    * <https://github.com/search?utf8=%E2%9C%93&q=%22vim+license%22++filename%3ALICENSE&type=Code>
    * <https://github.com/search?utf8=%E2%9C%93&q=%22same+as+vim%22&type=Code>

I think its not possible to support all examples I provided.
But we can start it from LICENSE file.
Maybe we can also detects [simple type][s]?

[s]:https://github.com/dracorp/aur-packages/blob/e2c03dcccd14209f1d2190e66dd040be7488b27c/vim/vim-cecutil/LICENSE

**Comment by mlinksva** [comment]
@othree thanks for that info. On the "simple type" no, that wouldn't be detected; licensee only matches full copies of licenses (and optionally license IDs in package files, but not brief statements in a `LICENSE` file in any case).

I suspect we should add producing 3 solid (not trivial or totally unknown projects) and straightforward (using just the license text, that could be detected) examples to the required criteria. If there's no evidence that a license is used in a regular enough way that it could be detected then there's less value to adding it here, and I wouldn't even be confident that the use we'd be promoting here would be aligned with whatever the idiosyncratic way the license is used in the wild.

Do you know of 3 such examples for the Vim License? No rush, I'm happy to leave this open until you or someone else interested has time to investigate further.

**Comment by mlinksva** [comment]
Closing this since it's over a year old. There doesn't seem to be much demand for adding the Vim License. Feel free to comment, or just make a PR to add the Vim License if you feel it can meet our criteria. Thanks!
