### ISSUE TITLE
Page should warn about GPLv2 and GPLv3 incompatibilities

### ISSUE THREAD

**Issue by mitsuhiko** [github/choosealicense.com#5]
There is currently no indication on the page that GPLv2 and GPLv3 are not compatible.  This is especially problematic because the only two versions of the license linked are GPLv2 only and GPLv3 but not "GPLv2 or a later version".

**Comment by steko** [comment]
Yeah, in general putting both licenses under the same heading is misleading, clicking on the graphic you get one or the other without any explicit indication of what you are choosing.

**Comment by jyknight** [comment]
Yes, it is _very_ poor to recommend that people who don't know what they're doing license-wise to use GPLv2-ONLY at this point.

If you don't already know about licensing, the sane default for a copyleft license should be GPLv2-or-later, not GPLv2-only.

**Comment by ncoghlan** [comment]
Perhaps the front page could be simplified to explicitly recommend "GPLv2 or later" as it's copyleft option? It's the least likely to cause problems, as the "or later" clause handles both APL and GPLv3 compatibility, and the "GPLv2" base avoids many of the issues associated specifically with GPLv3.

**Comment by ncoghlan** [comment]
Further elaborating on the rationale for promoting "GPLv2 or later" as the default for strong copyleft:
- Can be combined with Apache Software License software (downstream user chooses to accept GPLv3 for the Apache License compatibility, with additional permissions to relax the GPLv3 back to the standards of GPLv2)
- Can be combined with GPLv2 only software (downstream user chooses to accept GPLv2)
- Can be combined with "GPLv3 only" and "GPLv3 or later" software (downstream user chooses to accept GPLv3)

If you want strong copyleft without inadvertent license conflicts, "GPLv2 or later" is currently the best way to go.

**Comment by ghost** [comment]
Currently, the site allows to add a file LICENSE with the license text. That says nothing about headers which may or not contain "or later". How should "or later" be implemented? A text addition to the note on the respective license page helps?

**Comment by benbalter** [comment]
We could create an entire site dedicated to GPL compatibility. `chooseagpllicense.com`? The best approach would likely be to link out to a GPL compatibility matrix from the GPL licenses' notes, either as a page within this site or externally. Anyone interested in taking a stab at a PR?
