### ISSUE TITLE
Newlines between each sentence in markdown source

### ISSUE THREAD

**Issue by dhimmel** [github/choosealicense.com#505]
Currently, the markdown sources for this repo do not use any newlines within paragraphs. This makes diffing unwieldy: any change affects at least an entire paragraph. Conflicts become more difficult to resolve.

When using Git to track prose, I've found the best solution is to have a single sentence per line. In the past, word wrapping was the preferred solution, but there is a high upkeep burden to word-wrapping and it requires every editor to enforce the same max line length.

If the maintainers are interested, I'm happy to submit a PR to add newlines between sentences. The rendered markdown will not change.

**Comment by mlinksva** [comment]
I'm not a fan of one sentence per line. It makes for a jarring editing experience. `--word-diff` is what I do instead. Happy to get over it if one sentence per line takes over the world, but I haven't seen much of it so far.

**Comment by dhimmel** [comment]
`--word-diff` works well for viewing changes, but it doesn't address the underlying issue: git is still a newline-based version control system. If two individuals change separate sentences in the same paragraph without newlines, there will be a conflict that must be manually resolved.

> Happy to get over it if one sentence per line takes over the world

This certainly won't be the case anytime soon. I adopted the practice after seeing [this tweet](https://twitter.com/jakevdp/status/796817091684769792), but it's still a rather nascent practice.

So no worries if you close or defer on this issue. Just wanted to make sure you were aware.

**Comment by waldyrious** [comment]
> It makes for a jarring editing experience.

@mlinksva could you elaborate a bit on that? I'm not sure I see what you mean.

> I adopted the practice after seeing this tweet

@dhimmel I suspect you haven't read http://rhodesmill.org/brandon/2012/one-sentence-per-line/ yet -- I'm guessing you'll like it :)

**Comment by mlinksva** [comment]
Paragraphs look like verse in the editor and maintaining newlines after each sentence is another thing to keep in mind while editing.

Merge conflicts are rare in this project. I can see the discipline being a net win for a project with lots of prose and a high level of churn.

**Comment by waldyrious** [comment]
@mlinksva I see what you mean. Indeed, ideally one would want to introduce newlines after every clause (e.g. breaking in commas, semicolons, parenthesis, dashes, etc.), which I agree may require actual discipline and some more thinking about the structure of sentences -- which isn't necessarily a bad thing!

But even breaking only entire sentences using periods as delimiters (which is considerably easier IMO) would greatly help reduce the whole-paragraph-changed effect. Note that this effect is not problematic for conflicts alone -- even if we only consider the small gains in review (which requires less effort to identify the before/after differences in either individual words or entire sentences), those small gains would accumulate over time.

Does breaking only on entire sentences sound like a sensible middle-ground? I think it might provide a reasonable balance of effort/benefit, especially if @dhimmel is willing to put in the bulk work to implement the convention.

**Comment by mlinksva** [comment]
I'd rather not here until and unless this becomes a more widely adopted practice, preferably with strong evidence for its benefits. I don't see it used in other and more heavily prose-based projects using git. Advocates should create a site or repo documenting the benefits gained by projects (complemented by lab experiments, even better, way too few of those on syntax and similar topics that people hold strong opinions on anyway) that have adopted the practice. Right now it just rubs me the wrong way, prioritizing a quirk of tooling over source text that looks and is worked with in an editor as I expect it to be. If latter weren't a widely held preference, I doubt markdown would've "won". Now if large benefits can be documented, I'm all for changing the world, including this tiny corner of it.
