### ISSUE TITLE
Unlicense examples include a project that is now MIT licensed

### ISSUE THREAD

**Issue by johnjago** [github/choosealicense.com#515]
https://choosealicense.com/licenses/unlicense/

stacktrace.js is listed under "Who's using this license?", but it has since been [relicensed](https://github.com/stacktracejs/stacktrace.js/commit/a9e4d53d7f3388f8f7e6d1ddae048293bf5afab3) and should no longer be listed.

Perhaps we could replace it with [Kakoune](https://github.com/mawww/kakoune), a text editor based on Vim. It is released under the Unlicense, and the project seems to be active.

**Comment by mlinksva** [comment]
@johnjago thanks for pointing that out. Kakoune is already the third example! :smile:

Any other ideas?

If you'd like to make a pull request to fix, the file to edit is https://github.com/github/choosealicense.com/blob/gh-pages/_licenses/unlicense.txt
