### ISSUE TITLE
Plase add Beerware license

### ISSUE THREAD

**Issue by ghost** [github/choosealicense.com#52]
Wow great work. I bookmark the page. One license I miss is the beerware license described on wikipedia.

http://en.wikipedia.org/wiki/Beerware

**Comment by haacked** [comment]
While a cheeky license that makes me smile because I love :beer: I don't think it's appropriate for choosealicense.com. It's not recognized by the OSI as an open source license and has no disclaimer of liability. You're better off choosing MIT.
