### ISSUE TITLE
Documentation section of Non-Software Licenses has no links.

### ISSUE THREAD

**Issue by adamvoss** [github/choosealicense.com#521]
https://choosealicense.com/non-software/#documentation

It states "Any open source software license or open Creative Commons license", however it offers no assistance in finding those.  Technically a couple of Creative Commons licenses were mentioned in the previous section (data/media), but only by short name (ex. CC-BY-4.0) so uninformed users likely won't even know they are Creative Commons licenses.  The result is that it is more effective to google "Creative Commons" at that point if you want to find licenses because there is no quick way to the [Appendix](https://choosealicense.com/appendix/) which is the only place to get the information.

I think either more links or license details would be the solution, but I am not sure what the best implementation would be.

**Comment by mlinksva** [comment]
Thanks for the close read @adamvoss. Let me know if #522 helps.
