### ISSUE TITLE
Add Common Public Attribution License

### ISSUE THREAD

**Issue by wisn** [github/choosealicense.com#525]
I found that someone wants to add an attribution in the end-user program. I mean, the developer wants to add an attribution like "Powered by [insert name here]" in the user website (since the software is a web framework).

After read some license, I think [CPAL](https://spdx.org/licenses/CPAL-1.0.html) suitable. How about this?

**Comment by mlinksva** [comment]
That's the point of CPAL. It's pretty controversial and never got much traction. See a 2016 overview of the history of "open source badgeware" at https://lists.opensource.org/pipermail/license-review/2016-June/002851.html

Closing this as I don't think you're proposing adding CPAL to this repo/site, but if you want to follow up on that see [our criteria](https://github.com/github/choosealicense.com/blob/04f260afb29790c08e8403b8ad004267a8fa89e6/CONTRIBUTING.md#adding-a-license) for the info needed.
