### ISSUE TITLE
Compare between 2 or 3 Licenses

### ISSUE THREAD

**Issue by maverick74** [github/choosealicense.com#528]
In the appendix we have almost all licenses for compare, but it would be good if the user could be able to compare just 2 or 3 licenses chosen by him side by side.

Having the characteristics of just 2 or 3 will make them more easy to compare :)

**Comment by mlinksva** [comment]
I can see how this would be useful, but have no clever ideas for a nice UI for selecting licenses to compare. If someone wants to contribute ideas or prototype, perhaps as a dedicated page, would be fun.

I don't have any plan to work on this and will probably close after a week to give some visibility for other comments or someone who wants to take it on.

**Comment by maverick74** [comment]
here's an idea :)

![compare](https://user-images.githubusercontent.com/14912461/28078968-8bb5a552-665e-11e7-9b67-163d6c15710b.png)

**Comment by mlinksva** [comment]
Reasonable idea, but I don't foresee implementing. Maybe someone would be interested in adding the ability to hide/unhide licenses from the appendix table would be one way to get a similar feature without an entirely new UI. Closing, but feel free to comment, or open a new issue, or a PR...
