### ISSUE TITLE
Combine 2 or 3 Licenses

### ISSUE THREAD

**Issue by maverick74** [github/choosealicense.com#529]
What if someone has a software that is composed by other softwares that happen to have different licenses? Or if one wants to simply combine 2 or 3 licenses?

It would be good to be able to combine 2 or 3 licenses and see with what one ends up (the permissions, restrictions, etc)

tldrlegal.com License Summary page is a great way to present the Can/Cannot/Must conditions

**Comment by mlinksva** [comment]
Thanks @maverick74. You've hinted at very different situations, each of which is potentially complex. "Combining" licenses is almost never the right way to think about either of them, nor variations.

For using code from other projects, which may be under different licenses, there's already #242

Dual or other multi-licensing is an advanced topic that someone choosing a license for a project doesn't need to know about, but conceivably could be mentioned in a FAQ #381 

I'm going to close this issue as I don't think there's anything new or actionable, but feel free to discuss further if I'm missing something.

**Comment by maverick74** [comment]
Doesn't combining licenses always result in the sum of the attributes of all the licenses involved? 

If so, using most of the system as for compare (that i just uploaded in #528 ), could give the user an idea of the "resulting license" from the licenses combined

**Comment by mlinksva** [comment]
It depends what you mean by "combining licenses". I wouldn't think in those terms at all.

Some projects are offered under disjunctive dual (or greater) licenses, eg for a long time Firefox was [available under](http://website-archive.mozilla.org/www.mozilla.org/mpl/MPL/boilerplate-1.1/mpl-tri-license-txt) MPL-1.1/GPL-2.0/LGPL-2.1 -- the /s are really ORs, not ANDs.

Some projects incorporate code under different licenses, in which case each license has to be complied with for code each covers. I guess that's what you're thinking of. Exactly what that means in practice depends on the details of the licenses and how the code is being used. Especially if licenses with a same license (copyleft) condition are being used, compatibility (see #513) among the licenses may be a blocker.

So I wouldn't mind seeing something like #528 as an easy way to compare licenses, but I wouldn't want anyone to have the impression that if they see some licenses, they should just sum their properties to get a meaningful result.
