### ISSUE TITLE
TLDR - Terms and Conditions

### ISSUE THREAD

**Issue by ganesshkumar** [github/choosealicense.com#531]
I would like to apology first as this is not a issue related to choosealicense. However, I have a problem which the developers and users of choosealicense will be interested in. 

My problem is as `Terms and Conditions` page on websites and applications get complicated, we need some open source solution to make common users to understand them. Something like choosealicense but for Terms and Conditions.
* [Here is my abstract proposal of the problem](https://gist.github.com/ganesshkumar/53c9ca6d3d2be6ff294f0d983b17a259).  

I would like your inputs(review, problems you see with this, is there any IRC or mailing list which can be helpful on this) on this. I am open to any pointers to move forward. 

Agains, sorry for posting it here but this is the best starting point I know of.

**Comment by mlinksva** [comment]
Hi @ganesshkumar good idea. It sounds a lot like https://github.com/tosdr/ -- you might want to collaborate with them.

Closing this as there's nothing to do in this repo, but feel free to continue discussing, and good luck!
