### ISSUE TITLE
Add Eclipse Public License version 2.0 (epl-2.0)

### ISSUE THREAD

**Issue by jmini** [github/choosealicense.com#536]
The Eclipse fundation has published a new version of the Eclipse Public License (epl).

Press release:
https://www.eclipse.org/org/press-release/20170829eplv2.php

Text:
https://www.eclipse.org/org/documents/epl-2.0/index.php

The list in choosealicense.com (and on GitHub) should be updated.

**Comment by mlinksva** [comment]
@jimini if you (or anyone else) is interested in making a pull request to add EPL-2.0, see instructions at https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license

**Comment by jmini** [comment]
Thank you for your clarification, there is work to do and I propose to use this issue to track the record.

For point 3:
> A GitHub code search must reveal at least 1,000 public repositories using the license

I am not sure how I manage to sort out version 1.0 instead of version 2.0 in the search.
Version 2.0 was published last month, but it should now be preferred to 1.0.
And EPL in general has 128k results on GitHub.

**Comment by jmini** [comment]
Point 2:
> The license must be listed on one of the following approved lists of licenses: 

See: https://opensource.org/licenses/alphabetical

**Comment by jmini** [comment]
Point 1:
> The license must have an SPDX identifier.

Discussion is on going:
https://lists.spdx.org/pipermail/spdx-legal/2017-August/002134.html

**Comment by mlinksva** [comment]
> I am not sure how I manage to sort out version 1.0 instead of version 2.0 in the search.

There's probably some short string that's unique to 2.0. I'd expect something like https://github.com/search?utf8=%E2%9C%93&q=filename%3ALICENSE+%22separate+file+or+files+made%22&type= should work but that's only turning up 1 result, which can't be right (note without "made", it finds 21k results, which is about right -- that string is in MPL-2.0). Anyway, given problems of verifying exactly and this is successor of a fairly popular license, we can probably skip the strict 1k repos test, if we can find 3 solid example uses and a SPDX ID is minted.

**Comment by jmini** [comment]
Point 4:
> Identification of 3 notable projects

The first two that comes to mind are:

JUnit 5 (Java testing Framework)
https://github.com/junit-team/junit5

OpenJ9 (IBM open-source donation of the J9 JVM)
https://github.com/eclipse/openj9

I guess a lot of EPL-1.0 projects are in the process of migrating (especially those on the Eclipse Release train). So I will update this list when I see that these projects have migrated.

**Comment by mlinksva** [comment]
https://github.com/eclipse/openj9/blob/master/LICENSE is not a good example for these purposes -- the (excellent) project is dual licensed and lots of info besides the EPL-2.0 text is included in that file -- so it doesn't add to "straightforward LICENSE files which serve as examples newcomers can follow and that could be detected by licensee if it knew about the license"

I'm sure there will be other straightforward examples as projects migrate, thanks for documenting!

**Comment by jmini** [comment]
Official License document available:

* [HTML](https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.html)
* [TXT](https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.txt)

**Comment by lukateras** [comment]
At this moment I could only find one major project that would be properly identified by Licensee:
https://github.com/eclipse/smarthome/blob/master/LICENSE

**Comment by jmini** [comment]
This is probably true, but not providing the possibility to create a new repository with EPL v2 will not help the adoption.
In my humble opinion EPL v1 should be removed from the possibilities (for new repos).

**Comment by mlinksva** [comment]
#554 is a WIP PR which would eventually lead to EPL-2.0 showing up in place of EPL-1.0. Needs more examples (please continue to drop those here, or on the PR) and SPDX to publish a record for EPL-2.0.

**Comment by jmini** [comment]
For completeness, this issue is also tracked in the Eclipse Foundation Bugzilla: [Bug 522547](https://bugs.eclipse.org/bugs/show_bug.cgi?id=522547) (the Bugzilla record is basically a placeholder/pointer, the discussion should continue here)

The complete list of tasks regarding the EPL-2.0 Rollout can be seen by analyzing the [dependency tree of Bug 519789](https://bugs.eclipse.org/bugs/showdependencytree.cgi?id=519789).

---

> The license must have an SPDX identifier.

Regarding the SPDX identifier, there is also some activity on this GitHub issue: https://github.com/spdx/license-list/issues/16

---

Regarding the adoption, important projects will update to EPL v2 soon. @mmilinkov has [announced](https://mmilinkov.wordpress.com/2017/11/21/ee4j-progress-nine-new-projects-proposed-at-the-eclipse-foundation/) that nine projects coming from JavaEE will move to the Eclipse Foundation (as part of the EE4J top-level project). Their project proposal mention that they will use `EPL-2.0`.

cc @waynebeaton

**Comment by wking** [comment]
On Sat, Nov 25, 2017 at 08:16:07AM +0000, Jérémie Bresson wrote:
> > The license must have an SPDX identifier.
>
> Regarding the SPDX identifier, there is also some activity on this
> GitHub issue: https://github.com/spdx/license-list/issues/16

I think ‘EPL-2.0’ has officially been accepted for the next SPDX
License List release based on [1].  I'm not sure what the timeframe
for that release is.

[1]: https://lists.spdx.org/pipermail/spdx-legal/2017-October/002246.html

**Comment by jmini** [comment]
>  Regarding the SPDX identifier, there is also some activity on this

The correct PR for integration of `EPL-2.0` in the spdx list ist: https://github.com/spdx/license-list-XML/pull/499 (See also [Bug 527842](https://bugs.eclipse.org/bugs/show_bug.cgi?id=527842) at the Eclipse Foundation).

**Comment by lukateras** [comment]
Amazing! Thank you a lot.

**Comment by darkmorpher** [comment]
Update? You can now choose it via UI on GitHub but it's not listed on the list at https://choosealicense.com/licenses

While it is posted on https://choosealicense.com/licenses/epl-2.0 , you have to know the link with no other mention of it on choosealicense

**Comment by benbalter** [comment]
@darkmorpher EPL 2.0 was added via #554. The site has three tiers of licenses, those that are on the home page, those that are on `/licenses` and those that are in [the appendix](https://choosealicense.com/appendix/). EPL 2.0 is in the last category.

Per [the project goals](https://github.com/github/choosealicense.com#goals), we try not to overwhelm viewers with a long laundry list of licenses, but if you'd like to propose EPL 2.0 be added to the `/licenses` list, please feel free to open a new issue or pull request and the community can discuss the proposal there. Thanks! :smile:

**Edit**: Typo

**Comment by mmilinkov** [comment]
Ben, the EUPL and EPL are completely different licenses.

**Comment by benbalter** [comment]
👋😄 Hello @mmilinkov! Apologies for the typo. Updated my comment to reflect EPL, not EUPL.
