### ISSUE TITLE
BSD License "All rights reserved" - Why does this work?

### ISSUE THREAD

**Issue by SicroAtGit** [github/choosealicense.com#556]
I think there are a lot of people here who are well versed in copyright and licensing, so I would like to ask the following question:

Why can the clause "All rights reserved" be used in the open source license "BSD"? The open source license gives other people rights to the work. Therefore, "All rights reserved" can no longer be used, in my opinion. I don't understand. Can somebody explain this to me, please?

**Comment by benbalter** [comment]
See https://ben.balter.com/2017/11/28/everything-an-open-source-maintainer-might-need-to-know-about-open-source-licensing/#copyright-versus-the-right-to-use.

**Comment by SicroAtGit** [comment]
The "All Rights Reserved" has therefore nothing to do with the rights granted by the open source license to other people.

After I searched Wikipedia for "All rights reserved", I read that the rights reservation notice was necessary earlier: https://en.wikipedia.org/wiki/All_rights_reserved#Obsolescence
Therefore, I assume that the BSD license text only contains the rights reservation notice because the license text was written before the notice became unnecessary.

I hope I have understood now. Thank you! I will read through the whole page that your link refers to later on.
