### ISSUE TITLE
FSF approved from the mock-FSF API at wking/fsf-api?

### ISSUE THREAD

**Issue by wking** [github/choosealicense.com#561]
Looking over the code near #560, I noticed that we're [scraping the FSF HTML][1] to determine FSF approval.  SPDX recently decided to display “FSF Free/Libre?” on [their license list][2], and after [some discussion][3], I talked them into mocking up [an FSF API][4] (although spdx/tools [currently vendors the detailed list][5]).  Ideally the FSF would be maintaining the API (or any API), but until someone can talk them into that I think we can save work by collaborating on the mock API.  If that sounds interesting, I'm happy to work up a PR to convert `fsf_approved_licenses` to use the mock API the same way `spdx_list` is using the SPDX API.  I'm also happy to transfer ownership of the mock API repo to anyone who's interested, although the scope is a bit larger than what this repo needs.  Thoughts?

[1]: https://github.com/github/choosealicense.com/blob/8cac9c3d8e97e6ff16361d05fac0aa81f3978efb/spec/spec_helper.rb#L102-L123
[2]: https://spdx.org/licenses/
[3]: https://github.com/spdx/license-list-XML/pull/453
[4]: https://github.com/wking/fsf-api
[5]: https://github.com/spdx/tools/blob/4c9054942fd8ba1fb691de8950aeeca3fdf4addf/resources/licenses-full.json

**Comment by mlinksva** [comment]
I'd welcome such a PR.

I'd be nice if the API were at some unlikely to change URL, since GitHub Pages doesn't do HTTP redirects. Not a requirement.

**Comment by wking** [comment]
On Sat, Dec 30, 2017 at 12:23:37AM +0000, Mike Linksvayer wrote:
> I'd be nice if the API were at some unlikely to change URL, since
> GitHub Pages doesn't do HTTP redirects.

Even if I am able to transfer primary maintainership to someone more
official, I can commit to mirroring the canonical location in my
GitHub pages for at least the next year or so.  And I'm happy to
transfer to a more canonical location now if you have any suggestions.

If the FSF steps up and provides their own API though, it may or may
not be a drop-in replacement for the one I've worked up.  So the
commitment risk would be that we land a PR consuming my mock API, and
then the FSF provides an incompatible canonical API, and then we have
to adjust this repo to consume their API.  I'd be happy enough with
the FSF stepping up that I'd likely be able to handle that migration
as well (although there would still be a reviewer cost to land the
pivot).
