### ISSUE TITLE
Rephrase "Please consult a legal expert"?

### ISSUE THREAD

**Issue by henrik** [github/choosealicense.com#57]
As tweeted:

 "Please consult a legal expert before adopting a software license for your project" in the footer feels like a bit of a cop out.

A disclaimer is fine, but "demystifying" licenses only to say you must talk to a mystic is a little silly.

Perhaps the footer could instead say something more along the lines of the "About" page disclaimer (maybe linked to the disclaimer):

"If you have questions or issues, it’s always best to consult a professional."

**Comment by hoolio** [comment]
@henrik -- Point well taken. We'll get this changed.

**Comment by henrik** [comment]
Great, thanks!

**Comment by henrik** [comment]
Excellent!
