### ISSUE TITLE
CLA-link not working, cla.github.com doesn't exist anymore?

### ISSUE THREAD

**Issue by voxpelli** [github/choosealicense.com#576]
I went looking for your CLA that's linked to in eg. this project:

> You will be asked to sign the [GitHub Contributor License Agreement](https://cla.github.com/) for this project when you make your first pull request.

It was added in https://github.com/github/choosealicense.com/commit/c0fe6e3dededc7b52063f6f629229667381e3412#diff-6a3371457528722a734f3c51d9238c13, but when one navigates to the site at https://cla.github.com/ one only sees:

> 404
>
>There isn't a GitHub Pages site here.
>
> If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account.

**Comment by mlinksva** [comment]
Thanks for this report @voxpelli.  We removed the CLA requirement but missed a reference to it in CONTRIBUTING. Will be fixed with #577
