### ISSUE TITLE
Can't choose any EUPL license for my repository

### ISSUE THREAD

**Issue by Eagle3386** [github/choosealicense.com#578]
While I did recognize  GitHub and ChooseALicense.com both support EUPL-1.2 nowadays (even chose this particular one only because of the information provided by the latter), I seem unable to set any version of the EUPL as the license for my repository:

- It's not available within the `Add a license` drop-down when [setting up a new repo](https://github.com/new), neither bei entering "European", "EUPL" and the like.
- It's not available within the `Choose a license template` [button's list](https://github.com/USERNAME/REPO-NAME/community/license/new?branch=master) (nor can one search for it over there)
- Having a file named `LICENSE` or `LICENSE.md` within my repo's root folder neither solved this.

Please help me, so that I get my chosen license shown as the GitHub documentation suggests:
![GitHub documentation](https://help.github.com/assets/images/help/repository/repo-license-indicator.png)

**Comment by mlinksva** [comment]
It may not be available yet, see https://github.com/github/choosealicense.com/pull/523#issuecomment-355418428 for how you can check. However, you can add the license text to your repo in a file called `LICENSE`, regardless of whether github.com detects and displays an indicator. As Ben wrote to you over at https://github.com/benbalter/licensee/issues/288 you can [contact support](https://github.com/contact) for specific questions about your repo on github.com.
