### ISSUE TITLE
Question: permissive licence but with copyright notice—a contradiction?

### ISSUE THREAD

**Issue by buggymcbugfix** [github/choosealicense.com#585]
First of all apologies if this is the wrong place to post this. Feel free to close the issue and point me to a better place if you can. I am also happy to open a pull request with the answer (once I find one) if this is something that would help others.

I am wondering—I often see work under a permissive licence like the MITL but in conjunction with a copyright notice, e.g.
> (c) 2018 _The Authors_

Are these two incompatible? If not—which one wins over the other?

**Comment by benbalter** [comment]
@vimuel See https://ben.balter.com/2017/11/28/everything-an-open-source-maintainer-might-need-to-know-about-open-source-licensing/#copyright-versus-the-right-to-use.

**Comment by buggymcbugfix** [comment]
@benbalter Fantastic, that makes complete sense. Do people here feel it's worth adding a note of this to the website?

**Comment by mlinksva** [comment]
Not clear where such would be added to site so closing this with a reference to #238 as a reminder to possibly address it in a glossary or the like.
