### ISSUE TITLE
Licensing already published code

### ISSUE THREAD

**Issue by SicroAtGit** [github/choosealicense.com#594]
What should I do if a code has already been published without a license and now needs to be published with a license? I am the copyright holder.

Should the copyright notice look like this?
```
Copyright 2015, 2018 (added MIT license) Copyright-holder
```

Or like this?
```
Copyright 2015, 2018 Copyright-holder
```

Or like this?
```
Copyright 2015, 2018 Copyright-holder
*Since 2018, the code is MIT licensed
```
It would be nice if someone could explain it to me.

**Comment by benbalter** [comment]
@SicroAtGit we can't provide legal advice or speak to the particular's of your project, but https://ben.balter.com/2015/06/03/copyright-notices-for-websites-and-open-source-projects/ may be able to provide some general guidance on open source copyright notices.

**Comment by mlinksva** [comment]
FWIW if you're asking about the copyright line to include in the MIT text itself for your project's LICENSE file, I've never seen a note about when the license was first offered added in such a context. It is nice to note such where people really interested in the project's history can find it, eg in one or more of release notes for the first open source release, a blog post, or the README or other project documentation.

**Comment by SicroAtGit** [comment]
@benbalter: As far as I know, general information about the use of copyright notes is allowed. Your great blog article (thanks for that), to which your link refers, already informs about such general information.

@mlinksva: Okay, thanks. The information about when the licensing was added is usually not noted in the copyright line, but elsewhere (e.g. in the release notes).
