### ISSUE TITLE
Phrasing "adds a restriction restricting" on front page

### ISSUE THREAD

**Issue by bxt** [github/choosealicense.com#6]
I think the wording  "adds a restriction restricting" is ugly and adds more perceived complexity to GPL licenses. It is found in index.html at: "V3 is similar to V2, but adds a restriction restricting use in hardware that forbids software alterations.".

**Comment by haacked** [comment]
Mind submitting a pull request? You can edit the page in the browser! Just go to here and click edit. https://github.com/github/choosealicense.com/blob/gh-pages/index.html

Perhaps something like:

> but restricts use in hardware

Is simpler and more direct.

**Comment by haacked** [comment]
Ha! You beat me to it. Thanks!
