### ISSUE TITLE
multiple licence

### ISSUE THREAD

**Issue by Ayshine** [github/choosealicense.com#606]
Hi, 
My new repository will contain sketch notes and codes. So, sketch nodes need a non-software license and software license. I couldn't find a way to add both. Is there a chance I can do that? Or will there be an upgrade so we can do that?

**Comment by mlinksva** [comment]
See https://choosealicense.com/non-software/

It's easiest to use a single "software" (actually more broadly applicable) license for everything in a repo, and you might want to think about whether that could work for your particular case.

There are lots of different ways multiple licenses could apply to various bits in a repo. Just accurately note in the README what those licenses are and exactly where they can be found and what they apply to.

I don't think there's anything actionable for this project at this point, so closing, but feel free to discuss or point out something specific that choosealicense.com could do to better address this case.
