### ISSUE TITLE
Is "No-License" page accurate?

### ISSUE THREAD

**Issue by st-pasha** [github/choosealicense.com#620]
https://choosealicense.com/no-permission/

In particular, I'm worried about the following sentence in the first paragraph:
>  Once the work has other contributors (each a copyright holder), “nobody” starts including you.

It is my understanding that under the US law, copyright can either belong to a single party, or owned jointly by several authors ([17 U.S. Code § 201](https://www.law.cornell.edu/uscode/text/17/201)). If there is a repository with some initial body of code, and another person makes a contribution to that repository, then one of 2 things may happen: 
- Either the contribution is presumed a revision, and the copyright remains with the original author (for example, a copy-editor making minor modifications to the text of a book);
- Or the contribution is considered significant to qualify for the "joint authorship" doctrine, in which case both authors become joint copyright holders;
- The last case when each contribution is truly independent from the rest of the code, creating a collective work, is not really interesting.

However, even with the joint authorship, each author [retains the rights](http://copyright.universityofcalifornia.edu/ownership/joint-works.html) to the whole code body, including the rights to use, modify, publish, distribute, grant non-exclusive licenses, etc.

Or am I misunderstanding something?

**Comment by mlinksva** [comment]
Previously covered at https://github.com/github/choosealicense.com/issues/503#issuecomment-295531160
