### ISSUE TITLE
Do I need to copyright my code/app if I intend to sell it ? (I've already made it private)

### ISSUE THREAD

**Issue by mbraga24** [github/choosealicense.com#626]
If someone could help me out with the following, it'd be greatly appreciated.

So here is the story: 
for my final project at school I created a MVP web app based on an idea I had a time ago. The app is specifically targeting the company I work with, it's a customer service review app only to be used inside this company/store. So far I have shared my idea with a lady from the marketing team and a gentleman who is the  region director of the brand, they seemed to be really interested in the idea and started to ask me all sort of questions. They thanked me as if I was offering it to them for free and wanna see me again in their office next week so I can present them the MVP.

I have few questions:

1- From my end, I have pushed this application a month and a half ago, way before I speak to them (The day of this post was when I spoke to them). Based on that, do I need to add any copyright on my project on GitHub to guarantee I get compensated if they try to recreate the application using my ideal ? Can I even do that ?

2- My code is Private already, does that mean I have full ownership of my code and idea ?

3- As far as ideas go, my project is just a MVP but I had written on my README the main goal of the app, the technologies I used and future features I want to implement on my application. For example: I wanted to implement voice recognition, but because for now it's beyond my knowledge implementing something as such I only have it written on README as a future feature. I know I don't have ownership of the voice recognition technology, evidently, but combined with my idea, does that give me ownership of the combined concept as a whole ?

I know it's lengthy but I'm new in programming with no experience and I'm a little lost with what is possible when we have an idea. 

Thank you all for you help and patience.

**Comment by mlinksva** [comment]
@mrdbrg your questions are well beyond the scope of this project. You should discuss the particulars of your situation with your own lawyer. In general you might want to increase your familiarity with what copyright does and doesn't cover, what is needed to obtain it, and how it copyright might relate to other topics like patents, trade secrets, and agreements that you might have with a school or company. You could look up any of those topics in your favorite search engine or Wikipedia. One guide that at least mentions many of the pertinent issues is https://otl.stanford.edu/sites/default/files/otlcopyrightguide.pdf

**Comment by mbraga24** [comment]
Thank you for your answer @mlinksva. I was kind of expecting my questions to be too specific.
Thanks again!
