### ISSUE TITLE
MIT license doesn't match the one on SPDX

### ISSUE THREAD

**Issue by jabl** [github/choosealicense.com#634]
If one compares the licenses at https://choosealicense.com/licenses/mit/ and https://spdx.org/licenses/MIT one sees that they are not identical.

The difference is the optional phrase "(including the next paragraph)" in the second paragraph. Which, I guess, is optional, but it would be nice if github would recognize a license with this optional part as a MIT license.

**Comment by mlinksva** [comment]
choosealicense.com doesn't have any optional/alternate markup; even if we eventually ingest license texts from SPDX (#489) we probably wouldn't include optional text.  Licensee (the library used by GitHub for license detection) would need to be optional text aware in any case -- simply adding optional text here would likely cause it to not detect licenses without (as is far more common) the optional text.

Long way of saying, this is a licensee issue.

I suspect it would be low priority to fix as this particular optional text seems to be pretty uncommon in the wild -- https://github.com/search?q=%22%28including+the+next+paragraph%29%22+filename%3ALICENSE obtains 617 results for me, possibly all from the same Xorg source, and seem mostly to be buried in a subdirectory.
