### ISSUE TITLE
Using GPL is too vague, there are GPLs other than the GNU GPL

### ISSUE THREAD

**Issue by RalphCorderoy** [github/choosealicense.com#64]
The site refers to "GPL" but there are various GPLs, not just the GNU GPL.  GNU say to refer to it as "GNU GPL":  http://www.gnu.org/licenses/gpl-faq.html#WhatDoesGPLStandFor

BTW, it may be worth spelling out GPL once as many mistakenly think the G stands for GNU whereas it's General.  This is probably another reason they avoid what they think to be tautological:  GNU GPL.

**Comment by ghost** [comment]
Related to #63 

Personally I think the benefit on GPL title is marginal, because the risk of confusion is minimal, in the context of an open source license chooser, of popular licenses, versioned v2 and v3.
