### ISSUE TITLE
Add 0BSD License

### ISSUE THREAD

**Issue by ghost** [github/choosealicense.com#642]
https://github.com/spdx/license-list-XML/pull/768

<img width="953" alt="screen shot 2019-02-11 at 6 16 24 pm" src="https://user-images.githubusercontent.com/440298/52558164-86695700-2e2c-11e9-8981-75e4c5e4b914.png">

This seems to be missing from your list, which I was under the impression was pulled from SPDX license XML (it's already there).

Ref: #464

**Comment by mlinksva** [comment]
The catalog here is checked against the SPDX list (eg that a given license exists and we're using the same naming) but only includes a small subset of licenses in the SPDX list since we do additional work to describe the attributes of each license cataloged here. I welcome a PR to add any license here that meets all of our [criteria](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license). I'm not sure that 0BSD meets 3 yet but if you can come up with a query that shows it plausibly (it's hard to get exact results) does, great!

**Comment by jhabdas** [comment]
Thanks @mlinksva. Given GH isn't the only SCM depot out there would you possibly make an exception or adjustment to criteria 3 to add BitBucket, GitLab and Gitea?

**Comment by jhabdas** [comment]
Here's 431+ licenses using an alternate name. How can I tell the total number? 

https://github.com/search?q="Free+Public+License+1.0.0"+filename%3ALICENSE&type=Code

**Comment by jhabdas** [comment]
Here's another 135 https://github.com/search?q="Zero-Clause+BSD"+filename%3ALICENSE&type=Code

**Comment by jhabdas** [comment]
So without a possibility for an "exact search" I recon there's plausibility here and criteria 3 is met, especially considering I could also run searches on BitBucket, GitLab etc.

**Comment by jhabdas** [comment]
Here's 431+ licenses using an alternate name:

https://github.com/search?q="Free+Public+License+1.0.0"+filename%3ALICENSE&type=Code

And another 135 or so https://github.com/search?q="Zero-Clause+BSD"+filename%3ALICENSE&type=Code

Considering "exact search" doesn't turn up all the results does BlackDuck have something which might help? Or does it make more sense to also include GitLab, BitBucket et al. considering this website—and licensing in general—are bigger than GH alone?

Thanks for all you do.

**Comment by ghost** [comment]
Fair enough:

- Here's 431+ licenses using an alternate name: https://github.com/search?q="Free+Public+License+1.0.0"+filename%3ALICENSE&type=Code
- And another 135 or so https://github.com/search?q="Zero-Clause+BSD"+filename%3ALICENSE&type=Code
- 634 with "0BSD" https://github.com/search?q=%220BSD%22+filename%3ALICENSE&type=Code

Considering "exact search" doesn't turn up all the results does BlackDuck have something which might help? Or does it make more sense to also include GitLab, BitBucket et al. considering this website—and licensing in general—are bigger than GH alone?

Thanks for helping with the extra work to raise visibility of 0BSD on this global website resource.

**Comment by jhabdas** [comment]
And I learned [today on npm.community](https://npm.community/t/0bsd-license-should-be-a-valid-spdx-license-expression/5277/3?u=balibebas) 0BSD SPDX code [was recently added](https://github.com/npm/cli/commit/f63a0d6cf0b7db3dcc80e72e1383c3df723c8119) to NPM so lets join the party! :D

**Comment by ghost** [comment]
And I just learned [today on npm.community](https://npm.community/t/0bsd-license-should-be-a-valid-spdx-license-expression/5277/3?u=balibebas) 0BSD SPDX code [was recently added](https://github.com/npm/cli/commit/f63a0d6cf0b7db3dcc80e72e1383c3df723c8119) to NPM so we can expect 1000 no sweat. /cc @landley

**Comment by mlinksva** [comment]
Thanks for your research @jhabdas. Feel free to open a PR to add 0BSD if you'd like to take a stab at it.

**Comment by jhabdas** [comment]
@landley could you help me identify 2 noteable projects besides your own using 0BSD or the former license name in order to help me satisfy the [contributing guidelines](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license)?

**Comment by ghost** [comment]
@landley could you help me identify 2 noteable projects besides your own using 0BSD or the former license name in order to help me satisfy the [contributing guidelines](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license)? Don't think [mine](https://www.npmjs.com/package/toxic-swamp) counts yet. ;)

**Comment by waldyrious** [comment]
Ideally [this listing](https://libraries.io/search?licenses=0BSD&order=desc&sort=stars) from libraries.io would be helpful, but the results seem to be quite unreliable.

That said, I did find https://github.com/m-labs/smoltcp (around 700 stars, FWTW as a measure of notability) and https://github.com/nazar-pc/PickMeUp (~570 stars). The latter lacks an actual LICENSE file, though. There's only a reference to the [name of the license in package.json](https://github.com/nazar-pc/PickMeUp/blob/506c9f16f/package.json#L17), and [some links in the README](https://github.com/nazar-pc/PickMeUp#license). You might want to submit one as a PR, to ensure it can be legally considered as licensed under the 0BSD.

**Comment by ghost** [comment]
Thanks @waldyrious. Pull submitted. We'll see what the author says. As an aside I'm curious to know what is necessary to have 0BSD also start showing up in the GitHub UI:

<img width="196" alt="screen shot 2019-02-13 at 6 23 03 pm" src="https://user-images.githubusercontent.com/440298/52705578-30c4b400-2fbe-11e9-8c0a-859ae5cce035.png">

When I copy the exact license text and push a commit up it doesn't seem to take yet and I get the generic _View License_ message. Perhaps that's driven by an NPM or Ruby SPDX license list module somewhere?

**Comment by mlinksva** [comment]
To show up in the GitHub UI the license has to be added in this repo, then vendored in licensee (which GitHub uses for license detection), then a new version of licensee cut, then that new version of licensee deployed on GitHub, then finally a detection has to be triggered in a particular repo (e.g., license file added/edited, or manually via support), and license text in repo has to be a near exact match of what has been added to this repo, or licensee won't positively identify it, and you'll still see "View license". So making a PR to add 0BSD to this repo is the first step. 😄

**Comment by ghost** [comment]
Pull opened
