### ISSUE TITLE
What if I don't care about attribution?

### ISSUE THREAD

**Issue by nottrobin** [github/choosealicense.com#65]
Your most "simple and permissive" license is an Attribution license. Sometimes we literally just want to contribute our work to the public domain, and don't even care about it being attributed back to us. E.g.: http://unlicense.org/

Personally I'd like it if we could promote non-attribution license for those who don't care, because if you want to build up a custom project of 20 or 30 different open works, it's can be cumbersome to include attributions for all of them.

**Comment by haacked** [comment]
If you go to the "other licenses" page http://choosealicense.com/licenses/ you can see we do list Public Domain as an option.

We chose the UNLICENSE to represent public domain. http://choosealicense.com/licenses/public-domain/

**Comment by nottrobin** [comment]
I see. So it is there. It's a shame it's not more promoted, but if that's what you think is best, fair enough I guess.

**Comment by haacked** [comment]
Yeah, we wanted to try and distill the homepage to three representative and popular choices and not bog people down with billions of choices. However, the mere presence of UNLICENSE in the site has heavily promoted the cause. The authors of the license seem to be happy with what we've done so far. :smile:
