### ISSUE TITLE
Apache License 2 is not recognised

### ISSUE THREAD

**Issue by Jarcionek** [github/choosealicense.com#653]
Hi,

I have created a repository a while ago and I have added an Apache 2 license. I have done it the way it was described at http://www.apache.org/licenses/LICENSE-2.0, however GitHub is not recognising it and on the list of my repositories shows that this repository has license "Other":

https://github.com/Jarcionek/Map-To-Object-Converter/blob/master/LICENSE.txt
https://github.com/Jarcionek?tab=repositories (CTRL+F: "Map-To-Object-Converter")

I have initially raised it with GitHub Support, who told me that GitHub uses http://choosealicense.com/ and I should raise it with you.

Best wishes,
Jaroslaw

**Comment by mlinksva** [comment]
GitHub only recognizes the full license text in a LICENSE.* file. The text you've used is intended for source files. Note the word "this file"! 😄

**Comment by Jarcionek** [comment]
Oh, fair enough, silly me :)
