### ISSUE TITLE
Apply the inclusion for 996ICU License

### ISSUE THREAD

**Issue by xiaohuilam** [github/choosealicense.com#655]
Can we merge The 996 Prohibited License (Aka: 996ICU License) to Github choosealicense.com's list?

--

*reference resources:*
- [996.icu repository](https://github.com/996icu/996.ICU)

**Comment by Pzoom522** [comment]
Seconded!

**Comment by benbalter** [comment]
Please see https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license for instructions on requesting a license be added.

**Comment by mlinksva** [comment]
Feel free to open a PR when/if the requirements cited above are met.
