### ISSUE TITLE
GPL and disclose of changes

### ISSUE THREAD

**Issue by Lennie** [github/choosealicense.com#66]
_The GPL (V2 or V3) is a copyleft license that requires others who modify your code to disclose their changes if they redistribute it in source or binary form_

I'm not sure this explains very clearly what the GPL does.

Basically the GPL makes sure the user of the 'product' will also receive the source and/or modifications. It does not mean the changes need to be made publicly available, only be made available to the user.

So I propose to change the text slightly:
_The GPL (V2 or V3) is a copyleft license that requires others who modify your code to make the code and changes available to whomever they distribute it to_

Or something along those lines.

**Comment by haacked** [comment]
Hmm, mind submitting a pull request with the exact wording you think so we can iterate on it?
