### ISSUE TITLE
 Where does the difference conditions between AFL-3.0 and OSL 3.0 come from?

### ISSUE THREAD

**Issue by reversi-fun** [github/choosealicense.com#662]
AFL-3.0 and OSL-3.0 are almost same license terms, why are the conditions of use different?
The difference between AFL-2.1 and OSL-2.1 may not be propagated by mistake?

 * spdx-id: AFL-3.0,title: Academic Free License v3.0
 ```
c) to distribute or communicate copies of the Original Work and Derivative Works to the public, under any license of your choice that does not contradict the terms and conditions, including Licensor reserved rights and remedies, in this Academic Free License;
 ```
 * spdx-id: OSL-3.0,title: Open Software License 3.0
    * conditions:
      - disclose-source
      - network-use-disclose
      - same-license (it OK from term  "c)")
 ```
c) to distribute or communicate copies of the Original Work and Derivative Works to the public, with the proviso that copies of Original Work or  Derivative Works that You distribute or communicate shall be licensed under this Open Software License;
 ```

**Comment by mlinksva** [comment]
Hi @reversi-fun you're right, the only difference should be that AFL-3.0 does not have `same-license` and OSL-3.0 does. Both should have `disclose-source` and `network-use-disclose`.

If you'd like to submit a pull request with this correction please do. Otherwise I'll do so tomorrow.

**Comment by reversi-fun** [comment]
I am satisfied with the fact that I can tell you that my tools have detected this issues.
And I'm glad if it becomes the motivation of the following enhancement:
 * Generate json file compatible with "FSF License Metadata API" #663

I will not update(pull request) your's file.

**Comment by mlinksva** [comment]
My quick assessment 2 hours ago was wrong in any case! The difference in the texts is very small

```wdiff
  c) to distribute or communicate copies of the Original Work and Derivative
  Works to the public, [-under any license-] {+with the proviso that copies+} of [-your choice-] {+Original Work or+}
{+  Derivative Works+} that
     [-does not contradict the terms and conditions, including Licensor's-]
[-     reserved rights and remedies, in-] {+You distribute or communicate shall be licensed under+}
  this [-Academic Free-] {+Open Software+} License;
```

but the result is that one does not need to disclose source in the case of AFL-3.0 as such works can be distributed under a different license that does not require source disclosure. It's not particularly intuitive, but see the explanation of the author of both licenses at https://rosenlaw.com/OSL3.0-explained.htm (section on AFL-3.0).

I did notice a few small formatting inconsistencies between the two licenses that I'll fix, but the classification is correct within the bounds vocabulary we're using here.
