### ISSUE TITLE
Chinese translation

### ISSUE THREAD

**Issue by weakish** [github/choosealicense.com#67]
I've forked it and translated it to Chinese.

https://github.com/weakish/choosealicense.com/tree/gitcafe-pages

Well, not a very strict translation, e.g. I've mentioned AGPL in index.html in my translation.

The Chinese version of website:

http://choosealicense.gitcafe.com/

**Comment by benbalter** [comment]
We'd have to track as closely as possible to the community-consensus content, but would love to figure out the best way to integrate this with the site (#68) if you could submit your changes as a pull request?

**Comment by weakish** [comment]
@benbalter I've cleaned up the commit history and put it in a pull request #72

**Comment by haacked** [comment]
https://github.com/github/choosealicense.com/issues/112

**Comment by Danielsence** [comment]
- [ ]ñ
