### ISSUE TITLE
What if none of the licenses work, part 2

### ISSUE THREAD

**Issue by David263** [github/choosealicense.com#684]
Quite a few licenses are listed on this website, and it is clear that open software needs to have a proper license/copyright. Part 1 of "what if none of the licenses work" is to choose one anyway.

But Part 2 (this Issue) has to do with choosing a different license from all that have been suggested: should I create my own license or choose one that github doesn't list at all?

I'll be very specific in this Issue: I want a clause stating that people who modify software must annotate each set of changed lines with their name and date. Why? Because this provides accountability if something goes wrong and the software is not under github or other version control.

Here is my own version of my license: it is a small modification of the popular and loose MIT license:
---
License for this Open Software (MIT-based)

Copyright © 2019 Springtime Software

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, and to modify the Software only if each set of modified
lines are commented as to date and by whom, subject to the following conditions:

This entire license and copyright notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
---

The alternative is to use the Zlib license, which is almost as good, but is somewhat known:

---
License for this Open Software (Zlib):

Copyright © 2019 Springtime Software

This software is provided 'as-is', without any express or implied
warranty. In no event will the authors be held liable for any damages
arising from the use of this software.

Permission is granted to anyone to use this software for any purpose,
including commercial applications, and to alter it and redistribute it
freely, subject to the following restrictions:

1. The origin of this software must not be misrepresented; you must not
   claim that you wrote the original software. If you use this software
   in a product, an acknowledgment in the product documentation would be
   appreciated but is not required.
2. Altered source versions must be plainly marked as such, and must not be
   misrepresented as being the original software.
3. This notice may not be removed or altered from any source distribution.
---

What does github say about this question? Which of these two licenses should I use?

**Comment by mlinksva** [comment]
Don't make up your own license unless you're utterly convinced that whatever you wish to propose is a large improvement _and_ are willing to put in a _lot_ of work to get it reviewed and accepted by your lawyer and various OSS community license bodies.

Zlib is probably the briefest of licenses with some form of "state changes", see https://choosealicense.com/appendix/ ... so good choice.
