### ISSUE TITLE
  Can you explain the double licensed ?

### ISSUE THREAD

**Issue by YSZeng** [github/choosealicense.com#688]
Dual licensed under the MIT and GPLv2 licenses.
I don't understand how to comply with double license.

**Comment by mlinksva** [comment]
I don't see a good place to cover in this site, but figure out whether the dual license situation is that a project is offered under both, meaning you could pick one to comply with (`MIT OR GPL-2.0`) or it contains some material under each license in which case you need to comply with both (`MIT AND GPL-2.0`).
