### ISSUE TITLE
Alternatives to MIT

### ISSUE THREAD

**Issue by Lonami** [github/choosealicense.com#689]
The post [**Deprecation Notice: MIT and BSD** *it's time to retire thirty-year-old academic licenses*](https://writing.kemitchell.com/2019/03/09/Deprecation-Notice.html) ([WayBack Machine link](https://web.archive.org/web/20191017102718/https://writing.kemitchell.com/2019/03/09/Deprecation-Notice.html)) has a few good points as to why new software might want to avoid licenses like MIT or BSD, and provides an alternative. It might be a good idea to encourage alternatives to MIT or, at least, make note of them more prominently.

**Comment by mlinksva** [comment]
A first step for additional lax permissive licenses pertinent to this repo would be https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license

Feel fee to open individual issues or PRs for such licenses.
