### ISSUE TITLE
MIT License is not the most permissive

### ISSUE THREAD

**Issue by vinniefalco** [github/choosealicense.com#694]
The problem with the MIT License is the imprecise language about attribution appearing in compiled forms. In my opinion the MIT License should be removed from the front of https://choosealicense.com/ and replace with the Boost Software License, which has greater acceptance especially in the embedded community and is generally a superior permissive license than the MIT license.

Note that projects which use the MIT  License can include code that is Boost licensed, but not the other way around. That is to say that the Boost license subsumes all other permissive licenses, and therefore should be given priority.

Guiding users towards the MIT license instead of the Boost license causes projects to lose opportunities for distribution, simply due to many policies which forbid the MIT license but allow the Boost one.

**Comment by mlinksva** [comment]
> many policies which forbid the MIT license but allow the Boost one

I would love references to these!

**Comment by mloskot** [comment]
@mlinksva Will comparative analysis of BSD, MIT and others vs BSL that actually had motivated and driven the design of BSL do?

- BSL vs MIT: http://www.crystalclearsoftware.com/cgi-bin/boost_wiki/wiki.pl?Boost_License/MIT_License

    > - Must not require that the license appear with executables or other binary uses of the library. 
    >     Does not mention or distingush between source and binary

- BSL vs BSD: http://www.crystalclearsoftware.com/cgi-bin/boost_wiki/wiki.pl?Boost_License/BSD_License

    > - Must require that the license appear on all copies of the software source code. 
    >     Requires copyright notice to appear in both source and binary distributions / documentation.
    > - Must not require that the license appear with executables or other binary uses of the library. 
    >     Fails see above 

All BSL requirements listed at https://www.boost.org/development/requirements.html#License

More comparisons at http://www.crystalclearsoftware.com/cgi-bin/boost_wiki/wiki.pl?Boost_License

**Comment by mlinksva** [comment]
I'm well aware of how they compare and contrast. I am specifically interested in "many policies which forbid the MIT license but allow the Boost one" of which I imagine exist but don't have knowledge of.

**Comment by glenfe** [comment]
@mlinksva I sent an e-mail to you (BCC'd @vinniefalco).  Let me know if you're looking for additional information and I'll see what more I can share about the issue.

**Comment by mlinksva** [comment]
@glenfe I'd love public documentation, but still very interesting, thanks for sharing.

The relationship of the github.com/new license drop-down and this repo is indirect. I can't make any product promises, and if any were to happen it wouldn't be immediate. However, three followups:

1. Is there a C++ community licensing policy that is public and could be linked to along with others on https://choosealicense.com/community/ ?
2. The zlib license is the other somewhat common permissive license that doesn't require binary attribution. I'm curious about whether in the experience of people watching this issue it gets similar policy treatment and
3. whether we might increase the precision of the `include-copyright` attribute of BSL-1.0 and Zlib analogously to how `--file` and `--library` make `same-license` more precise for MPL-2.0 and LGPL-* respectively; see https://github.com/github/choosealicense.com#conditions

**Comment by mlinksva** [comment]
> 3\. whether we might increase the precision of the `include-copyright` attribute of BSL-1.0 and Zlib analogously to how `--file` and `--library` make `same-license` more precise for MPL-2.0 and LGPL-* respectively; see https://github.com/github/choosealicense.com#conditions

See https://github.com/github/choosealicense.com/pull/698

**Comment by trangngo1801** [comment]
#698
