### ISSUE TITLE
Artistic License 2.0 does not require Disclose Source

### ISSUE THREAD

**Issue by dan2097** [github/choosealicense.com#73]
Assuming you do:
 ensure that installation of your Modified Version does not prevent the user
installing or running the Standard Version. In addition, the Modified Version
must bear a name that is different from the name of the Standard Version.

then the Artistic License 2.0 does not require Disclose Source

sources:
http://choosealicense.com/licenses/artistic/
http://osdir.com/ml/licenses.open-source.general/2007-03/msg00055.html

**Comment by afeld** [comment]
Curious that [TLDRlegal](http://www.tldrlegal.com/l/ARTISTIC) also designates the license as Disclose Source.  I'm far from an expert on this topic, but is there some language in the license itself that makes it ambiguous?

**Comment by haacked** [comment]
It's a little confusing. Here's what section 4 a) says:

> Distribution of Modified Versions of the Package as Source
> (4) You may Distribute your Modified Version as Source (either gratis or for a
> Distributor Fee, and with or without a Compiled form of the Modified Version)
> provided that you clearly document how it differs from the Standard Version,
> including, but not limited to, documenting any non-standard features,
> executables, or modules, and provided that you do at least ONE of the following:
> 
> (a) make the Modified Version available to the Copyright Holder of the Standard
> Version, under the Original License, so that the Copyright Holder may include
> your modifications in the Standard Version.

Then 6 comes along and says:

> (6) You may Distribute a Modified Version in Compiled form without the Source,
> provided that you comply with Section 4 with respect to the Source of the
> Modified Version.

I think the fact is there are some cases where you kind of are required to distribute with source and others where you are not.

I haven't taken the time to map this out. @hoolio or @benbalter, I think a lawyerly eye here would really help.
