### ISSUE TITLE
Support Business Source License (BSL)?

### ISSUE THREAD

**Issue by Leedehai** [github/choosealicense.com#734]
Hi, I'm wondering if you'd consider the Business Source License.

It is used by [MariaDB](https://mariadb.com/bsl11/), etc.
A brief blog [here](https://blog.adamretter.org.uk/business-source-license-adoption/).

The core feature of BSL, loosely speaking, is that it allows users to "use" the software freely for non-commercial use, and that the user has to **pay for commercial use**. 

It allows developers and companies (like MariaDB) to contribute to source-available software while guarantee that they are compensated reasonably by commercial users. For example, big companies won't get to rip the benefits while the software contributors live on handouts. This protection is in effect for a limited time (see below).

> Because it requires paying for commercial use, BSL does not conform to [OSI's definition](https://opensource.org/osd) of "open source".

Other interesting features include:
- The license has a **Change Date** (say, 4 years after release). The license converts to a strictly open-source license (**Change License**, usually GPL) after the said Change Date. Since that date, the licensed work is governed by the Change License, meaning commercial users no longer need to pay.
- The license allows the copyright holder to specify **Additional Use Grant**.

**Comment by mlinksva** [comment]
Interesting license but doesn't meet our [criteria](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license).

It may eventually be added to the SPDX license list, see https://github.com/spdx/license-list-XML/issues/995

Even if it did meet our criteria for adding, the license's templated frontmatter means instances of it wouldn't be detected by licensee which vendors this repository (and is used by GitHub), usually one of the main drivers of requests to add licenses here.

Closing this for now but feel free to add relevant info.

**Comment by nschonni** [comment]
BSL is Boost Software License in SPDX https://spdx.org/licenses/BSL-1.0.html, although there is a pending PR to get it added https://github.com/spdx/license-list-XML/issues/995
