### ISSUE TITLE
Add the Hippocratic License

### ISSUE THREAD

**Issue by Quantumplation** [github/choosealicense.com#740]
Not sure if it's been brought up before, but I'd love to see the details of this license added to choosealicense.com:

https://firstdonoharm.dev/version/2/1/license.html

**Comment by mlinksva** [comment]
It doesn't meet our current [criteria](https://github.com/github/choosealicense.com/blob/2467d15902778467310e720c18794fbf4ddefedb/CONTRIBUTING.md#adding-a-license) for adding a license. Thanks for the suggestion!
