### ISSUE TITLE
The term "software" is used for cc-by-sa-4.0

### ISSUE THREAD

**Issue by niyumard** [github/choosealicense.com#743]
The explanations for Permissions, Conditions and Limitations when the mouse hovers the items under each section use the word "software" whereas material should be used, here: https://choosealicense.com/licenses/cc-by-sa-4.0/

**Comment by mlinksva** [comment]
CC 4.0 licenses happen to use the term material, but arguably it's a better term for all licenses, as not only software might be licensed. Though the focus of this site is OSS, the last word being software...I don't feel very strongly. Conceivably we could replace "software" with "licensed material" throughout https://github.com/github/choosealicense.com/blob/gh-pages/_data/rules.yml

Welcome others' thoughts.

**Comment by waldyrious** [comment]
> The focus of this site is OSS, the last word being software

IMO by including non-software licenses like the CC ones, it ceases being reasonable to use default terminology that's software-related. Changing "software" to "material" or "licensed material" in `rules.yml` seems appropriate and doesn't sound like it harms readability/clarity.
