### ISSUE TITLE
Add "MIT No Attribution" (pending requirements)

### ISSUE THREAD

**Issue by yawnoc** [github/choosealicense.com#754]
"MIT No Attribution" is what it says on the tin: the MIT license minus the attribution condition. I think it is a good license to use instead of WTFPL (lacks a no-warranty clause), the Unlicense ([probable legal issues in Germany](https://softwareengineering.stackexchange.com/a/147120 "What is wrong with the Unlicense?")), and CC0 (not designed for software and [does not waive patents](https://opensource.stackexchange.com/a/1393 "How could using code released under CC0 infringe on the author's patents?")).

It does not yet meet all of the requirements on CONTRIBUTING.md however:

1. SPDX identifier: **YES**, [MIT-0](https://spdx.org/licenses/MIT-0.html)
2. Approved lists of licenses: **YES**
   * OSI: ~~[submissions](https://opensource.org/approval) must be made by someone with "License Steward" standing. Who counts as a "License Steward"?~~
     ~~Roman Mamedov, who [formulated MIT-0](https://romanrm.net/mit-zero) back in 2010, tells me that it has [already been submitted](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2020-May/004856.html) and the next board Board meeting is [scheduled for mid August](https://lists.opensource.org/pipermail/license-review_lists.opensource.org/2020-June/004889.html)~~
     Approved as of 14 Aug 2020.
   * FSF: I have made a submission myself.
3. Sufficient usage in public repos: **NOT YET**
   Currently there are in the order of 500 code results for the search <https://github.com/search?q=filename%3ALICENSE+%22mit+no+attribution%22>
4. Notable projects: **Probably not enough**
   At the minimum there is [AWS](https://github.com/aws/mit-0).

**Comment by mlinksva** [comment]
99% agreed (dubious about the Unlicense parenthetical) but anyway MIT-0 be a good addition when it meets the criteria. Feel free to open a pull request if you'd like to ready the addition.

**Comment by mlinksva** [comment]
Approved http://lists.opensource.org/pipermail/license-review_lists.opensource.org/2020-August/004917.html and already up at https://opensource.org/licenses/MIT-0

For notable projects, it'd be fine to include one from AWS, but preferably not the repo for the license itself. 😄 

I got 344 projects just now for the query above. Will be interesting to see if that grows significantly post-approval, as it seems like a pretty attractive license to use for its use case.

**Comment by yawnoc** [comment]
I'm a pessimist, so I doubt there will be quick growth without a promotion to drive the uptake. I estimate at least 2 years to reach the threshold; I hope I am proven wrong.

Some MIT-0 repositories with at least 20 stars (at the time of writing):

| Repo | Stars | Forks | Link |
| --- | --- | --- | --- |
| [miniaudio](https://github.com/mackron/miniaudio) | 1k | 76 | [LICENSE](https://github.com/mackron/miniaudio/blob/master/LICENSE)\* |
| [Godot Sonic Physics](https://github.com/marmitoTH/Godot-Sonic-Physics) | 75 | 9 | [LICENSE.txt](https://github.com/marmitoTH/Godot-Sonic-Physics/blob/master/LICENSE.txt) |
| [SOIL2](https://github.com/SpartanJ/SOIL2) | 51 | 12 | [LICENSE](https://github.com/SpartanJ/SOIL2/blob/master/LICENSE) |
| [Alexa skill](https://github.com/alexa/skill-sample-nodejs-salesforce) | 25 | 44 | [LICENSE](https://github.com/alexa/skill-sample-nodejs-salesforce/blob/master/LICENSE) |
| [Atom plugin](https://github.com/amejia1/atom-xterm) | 20 | 2 | [LICENSE](https://github.com/amejia1/atom-xterm/blob/master/LICENSE) |

\* Dual license in the same file.
