### ISSUE TITLE
License text in cc-by-4.0.txt contains disclaimer from website creativecommons.org

### ISSUE THREAD

**Issue by tloimer** [github/choosealicense.com#764]
The license text in _licenses/cc-by-4.0.txt is surrounded by text that does not form part of the license. The text beginning with `Attribution 4.0 International` until the second line with equal signs, `==========...`, and at the end of the file, from the last line consisting entirely of equal signs until the end of the text, should be deleted.

In my opinion, the text that should be deleted is a disclaimer on the website of creativecommons.org, telling anybody who uses this license that creativecommons.org is not liable for any difficulties. At the end of the third paragraph, it is is even written out,
 > The following considerations are for informational purposes only, are not exhaustive, and **do not form part of our licenses**.

If my opinion is correct: since people use the entire text, probably it is possible to add the correct text separately, but under the same name?

**Comment by mlinksva** [comment]
We try to stick closely to the texts that are widely used. Many licenses include bits (mostly trailing) that are not part of the license, and we don't cut those out. https://creativecommons.org/licenses/by/4.0/legalcode.txt includes the ones you point out.
