### ISSUE TITLE
Add Linux Foundation

### ISSUE THREAD

**Issue by Brian-Seattle** [github/choosealicense.com#773]
https://www.linuxfoundation.org/resources/open-source-guides/

**Comment by mlinksva** [comment]
I'm not sure what you're proposing. Please read our [CONTRIBUTING](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md) and README files for background on what choosealicense.com is and how to contribute.

**Comment by Brian-Seattle** [comment]
I'm proposing including the Linux Foundation which is either the largest or
one of the largest open source repositories in the world, in terms of
companies and market capitalization based on open source licenses.

Plus Apache, which has an even simpler model than MIT.
https://www.apache.org/licenses/LICENSE-2.0

**Comment by mlinksva** [comment]
This repo only catalogs licenses, not organizations. There's actually another project inspired by this one for the latter, see https://github.com/ShaneCurcuru/chooseafoundation

I'm not sure how Apache-2.0 could be characterized as simpler than MIT, but in any case it's already cataloged here, see https://choosealicense.com/licenses/apache-2.0/
