### ISSUE TITLE
Missing versions of GPL, like v2

### ISSUE THREAD

**Issue by reisraff** [github/choosealicense.com#783]
Missing various versions of licenses in the https://choosealicense.com/licenses/ page

**Comment by waldyrious** [comment]
That's intentional — see [CONTRIBUTING.md § Adding a license](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license) and [about.md § Not comprehensive](https://github.com/github/choosealicense.com/blob/gh-pages/about.md#not-comprehensive) for the rationale.

**Comment by reisraff** [comment]
Ok get it, would be awesome though, to let the https://choosealicense.com/appendix/ more visible.
