### ISSUE TITLE
Using your license files in another project

### ISSUE THREAD

**Issue by fizzyade** [github/choosealicense.com#792]
Hi,

I'm currently working on a GPLv3 application for macOS which allows users to create DMG files easily and generate DMG files from the command line as part of an automated build process. (https://github.com/fizzyade/dmgee)

I've used your site many times in the past to download licenses and I love the rendering of the metadata you inject as it's clear and easy for people to understand.

Given the content is licensed under "Creative Commons Attribution 3.0 Unported license," I assume that you'd be fine with me bundling your license files inside my software?  I would obviously provide attribution and a link back which I do with all my projects including services and propriety tools that I use during development?

**Comment by mlinksva** [comment]
Yes. However, note that the license texts themselves are each under their own copyright. Everything else in this repo is indeed under CC-BY-3.0.
