### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by wylie39** [github/choosealicense.com#804]
The current version of choosealicense.com does not support dark mode. 
Any thoughts on adding that functionality. I am willing to step up and make a PR.

**Comment by mlinksva** [comment]
I'd be OK with a dark mode PR, but would probably defer to someone who knows more about design (just about anyone) than me.

**Comment by Pukimaa** [comment]
Ok because it is an easy fix I will make a PR

**Comment by Pukimaa** [comment]
Made a simple Dark Mode PR. I dont wanted to do it too complicated so I just used a `@media` to check if the User has activated Dark Mode. You could also possibly add a Dark Mode Button too. (should be simple)

**Comment by MichaelAgarkov** [comment]
Dark mode was added, and it works for me. As I understood it turns itself on if your default system theme is dark

**Comment by Pukimaa** [comment]
> 
> 
> Dark mode was added, and it works for me. As I understood it turns itself on if your default system theme is dark

Yes it does

**Comment by pomnt** [comment]
> The current version of choosealicense.com does not support dark mode. Any thoughts on adding that functionality. I am willing to step up and make a PR.

**Comment by mlinksva** [comment]
Fixed by #833
