### ISSUE TITLE
Extract licenses dataset as a submodule

### ISSUE THREAD

**Issue by KOLANICH** [github/choosealicense.com#807]
Hi.

Extracting the licenses dataset with minimal amount of other files will make it more convenient to be used in other projects. Here is the repo https://github.com/KOLANICH/GitHub_licenses_dataset where I have stripped everything unneeded. (All merges are lost and the history is lianearized since it seems like `--prune-empty` doesn't work on nonlinear histories, so I just exported everything into a seq of patches and then `am`ed them). Feel free to move it into your org and use as a submodule. But please keep in mind, it is undesireable to place there any source code and resources, it should be only a dataset, as lightweight as possible.

I'd also think that it may make sense to craft a JSONSchema for the YAML in the files.

**Comment by mlinksva** [comment]
Thanks @KOLANICH I appreciate that keeping the dataset completely separate would be elegant, but I don't think it can be made to work for this repo given that it needs to drive a website which is published with Jekyll, which is not terribly flexible on data/content file structure (not a knock on Jekyll, it's tuned to purpose).

I'll also eventually be restructuring the data a bit to better support translation of the site.

**Comment by KOLANICH** [comment]
>I don't think it can be made to work for this repo given that it needs to drive a website which is published with Jekyll, which is not terribly flexible on data/content file structure (not a knock on Jekyll, it's tuned to purpose).

I don't understand what you mean under that.

If you mean that directory layout cannot be changed, but if Jekyll tolerates symlinks, the easy solution is that submodule is created in an another directory (i.e. `dataset`), and then `_licenses` can be a symlink to `dataset/licenses` and `_data` can be symlinked to `dataset/schemas`.
