### ISSUE TITLE
What about internationalization?

### ISSUE THREAD

**Issue by whilein** [github/choosealicense.com#808]
Could you add the ability to change the language, please?

**Comment by nschonni** [comment]
Duplicate of https://github.com/github/choosealicense.com/issues/68, but the title might be better if it was renamed there

**Comment by mlinksva** [comment]
Closing as duplicate of #68 which does remain open because I intend to get to it eventually.

**Comment by nschonni** [comment]
@mlinksva it might be good to update the title up #68 to something like "Internationalization / i18n / multilingual site" just as a catch all of things that people would likely search for if they try looking before opening an issue
