### ISSUE TITLE
Please add the original Artistic License and the GPLv1 as used by Perl and most of the Perl Community

### ISSUE THREAD

**Issue by xtaran** [github/choosealicense.com#809]
I wanted to add a pull request for adding the Perl communities most used license combination known as "the same license as Perl itself" (i.e. Artistic License or GNU GPL version 1 or later) to https://choosealicense.com/community/, but noticed that only the Artistic License 2.0 is part of https://choosealicense.com/appendix/, neither the Artistic License 1.0 nor the Artistic License 1.0 as used by Perl (https://spdx.org/licenses/Artistic-1.0-Perl.html).

Granted, the latter doesn't make it easier, but it would be nice if the Artistic License 1.0 as used by Perl (https://spdx.org/licenses/Artistic-1.0-Perl.html) could be added so that one could refer to it on https://choosealicense.com/community/.

Actually, I just noticed that the GPLv1 isn't listed either. So to actually the GPLv1 should probably added, too. :-/

Or is it ok to also refer directly to SPDX on https://choosealicense.com/community/?

**Comment by mlinksva** [comment]
I don't think Artistic 1.0 is a good fit for the communities page as it isn't recommended by anyone, as far as I know. The links on the communities page point to both a recommendation/documentation of standard practice for a community, as well as the relevant license.

Feel free to make PRs to add Artistic-1.0 or GPL-1.0 if they meet our [criteria](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license), though I'd consider adding them to be ultra low priority as nobody should be choosing them for new projects, and shouldn't have been doing so for a very long time (almost 30 years in the case of GPL-1.0).
