### ISSUE TITLE
Improve landing page of choosealicense.com by listing the appendix somewhere more visible

### ISSUE THREAD

**Issue by Andre601** [github/choosealicense.com#830]
I mentioned this in #825 before but want to make this issue now.

The current main page (landing page) of choosealicense.com is heavily in favour of common Open source licenses.
While this might not be a big deal on first look does it essentially prevent other, lesser-known yet still valid, licenses from ever being discovered.
This case of playing favours is really bad, especially since there being a "More licenses are available" yet this linked page only lists some (again more popular) licenses and not all available ones, which is even more insulting considering the page name being "licenses", indicating that it *should* display all licenses available.

Choosealicense.com should have a goal of displaying all licenses to a user on some page while being easy to discover and/or access.
While the first part is covered by the [appendix] page is the second part not, due to the appendix page not being accessible in an easy way. There is no mention of it anywhere on the landing page and other pages also don't seem to really mention it. This is a huge downside and goes completely against what choosealicense.com should in my honest opinion represent: A place to easily find the license most matching to your project.

So please consider improving the landing page further by actively promoting the appendix page somewhere other than a (actually smaller) text mentioning it in /licenses, or make the licenses page actually list ALL licenses and not just a selected few

**Comment by 1hi1ok** [comment]
0x8578Eb576e126f67913a8bC0622e0A22EBa0989A

**Comment by mlinksva** [comment]
The page name is not `all-licenses`. 😄 I realize you'd like the site to have a different UI. Thanks for the feedback, but I'm not willing to make such a change right now.
