### ISSUE TITLE
Fix the license text in the BSD 4-Clause License

### ISSUE THREAD

**Issue by MichaelAgarkov** [github/choosealicense.com#839]
In the 3rd clause it says:
```
3. All advertising materials mentioning features or use of this software must
   display the following acknowledgement:
     This product includes software developed by [project].
```
Instead of the project name, it should say the name of the creator, so it should say [name] or [fullname] instead of [project].

**Comment by MichaelAgarkov** [comment]
I created a [pull request](https://github.com/github/choosealicense.com/pull/842)

**Comment by mlinksva** [comment]
Hi @MichaelAgarkov apologies for not getting to this sooner. I think either works, it's really up to the licensor to stipulate the acknowledgement. I'm agnostic about what the default should be. If anyone else wants to speak up for why it should be changed to `[fullname]` happy to consider merging #842.

**Comment by waldyrious** [comment]
IMO "project" implies a group, and "fullname" implies an individual. Either possibility is valid for the attribution, depending on the case, but the former sounds more likely to apply to open source projects, which typically (or hopefully) receive contributions from multiple people. For this reason, I'd favor "project" if we had to pick between the two. That said, if there's a more generic term we could use, it might indeed be worth changing the placeholder to it.

**Comment by MichaelAgarkov** [comment]
Yeah, I agree. It's fine then, thank you for explaining.
