### ISSUE TITLE
License text is too light on Linux

### ISSUE THREAD

**Issue by anshin** [github/choosealicense.com#85]
![2013-09-08-1378651547](https://f.cloud.github.com/assets/1342599/1103241/8fb14974-1895-11e3-9edb-22a7a40fd651.png)

It's not impossible to read, but it's fairly unpleasant. I might suggest embedding a fixed-width font.

**Comment by benbalter** [comment]
@cobyism any thoughts here?

/cc #37, #49

**Comment by tekkub** [comment]
It looks like this is the font stack being used for license text:

```
font-family: Consolas, Monaco, Courier, monospace;
```

Linux has a long history of rendering Courier like :poop:.  On github.com we're using this for the code browser, `<pre>` blocks inside readmes and comments:

```
font-family: Consolas, "Liberation Mono", Courier, monospace;
```

It looks like Liberation Mono has the same metrics as Courier New, and probably has a pretty good install base on linux.  It seems codestyle.org is down (gone?) so I can't confirm install percentages.  It looks like this is a free font too, so we could provide it as a `@font-face`.

**Comment by haacked** [comment]
thumbs up to "Liberation Mono". Anyone want to submit a PR with that?

**Comment by anshin** [comment]
@tekkub codestyle.org is returning a [410](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#410) error. I had no idea it existed, so I'm pretty bummed about that.

I'm in favor of Liberation, and it is open according to the [homepage](https://fedorahosted.org/liberation-fonts/).

**Comment by haacked** [comment]
@anshin would you like to submit a PR with Liberation?

**Comment by anshin** [comment]
I would. I'll have to do some research, and I'll try to submit a PR by tomorrow afternoon.

**Comment by cobyism** [comment]
Yes, there could be improvements to be made here in font rendering, but really I see this issue boiling down to contrast. I still reckon actually giving the license text a separate, lighter background (thus making the text appear darker and more well-defined) like I suggested in #49 is what is needed here:

![](https://f.cloud.github.com/assets/296432/807137/ff6753d4-ee48-11e2-9097-01d0ae43272a.png)

**Comment by haacked** [comment]
@jasonlong any thoughts?

@cobyism I thought skeuomorphism is dead and flat designs are all the rage! :trollface: 

Personally, if it makes it more readable, I'm all for it. If there's a way to do it so @jasonlong is happy with it, that also gets my vote. :smile:

**Comment by anshin** [comment]
I agree with @cobyism, though I still think Liberation Mono should be used – if only because it reduces the chance of a misc. font served by the OS. I'm going to wait for a response from @jasonlong before I act.

**Comment by jasonlong** [comment]
Sorry for the slow response. I'm getting set to move this week and will be online sporadically.

I'm still not sure I'd like to go full #fff on the background, but maybe a super-light beige – something close to white?

**Comment by cobyism** [comment]
> I'm still not sure I'd like to go full #fff on the background

@jasonlong Yeah, I just typed `#fff` when i originally did that as a quick mockup because it was the first thing that came to mind to illustrate the point—if we end up doing that, I completely agree that it should be something in line with the hues the rest of the site uses :+1:

**Comment by haacked** [comment]
@anshin This was fixed by https://github.com/github/choosealicense.com/issues/93. I'm going to close it now. Comment here if it's still a problem. Thanks for reporting it!
