### ISSUE TITLE
Adding hardware licenses to Non-Software Licenses

### ISSUE THREAD

**Issue by nytpu** [github/choosealicense.com#853]
Adding an open hardware license section to the Non-Software licenses page is very beneficial, especially since there seems to be a lot of outdated and fragmented information about them on google.

It looks like bigger open hardware companies like Adafruit and Sparkfun use the CC BY-SA for most of their stuff, but I think the [CERN OHL v2](https://ohwr.org/project/cernohl/wikis/home) family of licenses should also be included as they cover aspects more common with hardware like patents and such as well as just copyright.

The CERN OHL v2 is a *family* of licenses, with a permissive version (MIT-like), weakly reciprocal version (MPL/LGPL-like), and a strongly reciprocal version (GPL-like). The set of licenses mostly fits the [“Adding a License” critera](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license), each has an SPDX identifier: [CERN-OHL-P-2.0](https://spdx.org/licenses/CERN-OHL-P-2.0.html), [CERN-OHL-W-2.0](https://spdx.org/licenses/CERN-OHL-W-2.0.html), [CERN-OHL-S-2.0](https://spdx.org/licenses/CERN-OHL-S-2.0.html); and each is approved by the OSI: <https://opensource.org/CERN-OHL-P>, <https://opensource.org/CERN-OHL-W>, <https://opensource.org/CERN-OHL-S>. However, while all three licenses have [1,561 projects on github](https://github.com/search?q=CERN+Open+Hardware+License+Version+2+filename%3ALICENSE&type=Code) plus *at least* [380 projects off of github](https://ohwr.org/explore/projects?page=19&sort=latest_activity_desc) (19 pages x 20 entries per page), each individual license has less than 1,000 projects, technically not meeting the criteria. I personally believe it merits inclusion—it's certainly not an obscure license, and the main goal of the inclusion criteria seems to be to weed out non-notable licenses—but I'd like to have explicit approval before adding it.

I'll make a pull request adding the CERN OHL and the hardware section to the non-software page, but I wanted to get a go-ahead that it's okay to add the CERN OHL first. Even if the CERN OHL isn't okay to be added I'll make a pull request to add the CC BY-SA to a hardware section.

**Comment by mlinksva** [comment]
> while all three licenses have [1,561 projects on github](https://github.com/search?q=CERN+Open+Hardware+License+Version+2+filename%3ALICENSE&type=Code) plus *at least* [380 projects off of github](https://ohwr.org/explore/projects?page=19&sort=latest_activity_desc) (19 pages x 20 entries per page),

Those searches are overly inclusive, they obviously include a lot of non-CERN-OHL-* materials. Here are searches probably unique to each license, for github.com anyway:

* https://github.com/search?q=%22this+CERN-OHL-P%22+filename%3ALICENSE&type=Code (162 results)
* https://github.com/search?q=%22this+CERN-OHL-W%22+filename%3ALICENSE&type=Code (77)
* https://github.com/search?q=%22this+CERN-OHL-S%22+filename%3ALICENSE&type=Code (216)

> each individual license has less than 1,000 projects, technically not meeting the criteria

This is the fuzziest criteria. I'd welcome a PR that adds all 3 (I think it'd make sense to do as a a group to ensure consistency), which includes finding 3 solid examples for each. I don't promise to merge immediately but if you're willing to be patient, it'd be useful. Thanks for opening this.

**Comment by ychmun** [comment]
> Adding an open hardware license section to the Non-Software licenses page is very beneficial, especially since there seems to be a lot of outdated and fragmented information about them on google.
> 
> 
> 
> It looks like bigger open hardware companies like Adafruit and Sparkfun use the CC BY-SA for most of their stuff, but I think the [CERN OHL v2](https://ohwr.org/project/cernohl/wikis/home) family of licenses should also be included as they cover aspects more common with hardware like patents and such as well as just copyright.
> 
> 
> 
> The CERN OHL v2 is a *family* of licenses, with a permissive version (MIT-like), weakly reciprocal version (MPL/LGPL-like), and a strongly reciprocal version (GPL-like). The set of licenses mostly fits the [“Adding a License” critera](https://github.com/github/choosealicense.com/blob/gh-pages/CONTRIBUTING.md#adding-a-license), each has an SPDX identifier: [CERN-OHL-P-2.0](https://spdx.org/licenses/CERN-OHL-P-2.0.html), [CERN-OHL-W-2.0](https://spdx.org/licenses/CERN-OHL-W-2.0.html), [CERN-OHL-S-2.0](https://spdx.org/licenses/CERN-OHL-S-2.0.html); and each is approved by the OSI: <https://opensource.org/CERN-OHL-P>, <https://opensource.org/CERN-OHL-W>, <https://opensource.org/CERN-OHL-S>. However, while all three licenses have [1,561 projects on github](https://github.com/search?q=CERN+Open+Hardware+License+Version+2+filename%3ALICENSE&type=Code) plus *at least* [380 projects off of github](https://ohwr.org/explore/projects?page=19&sort=latest_activity_desc) (19 pages x 20 entries per page), each individual license has less than 1,000 projects, technically not meeting the criteria. I personally believe it merits inclusion—it's certainly not an obscure license, and the main goal of the inclusion criteria seems to be to weed out non-notable licenses—but I'd like to have explicit approval before adding it.
> 
> 
> 
> I'll make a pull request adding the CERN OHL and the hardware section to the non-software page, but I wanted to get a go-ahead that it's okay to add the CERN OHL first. Even if the CERN OHL isn't okay to be added I'll make a pull request to add the CC BY-SA to a hardware section.
