### ISSUE TITLE
Add Artistic 2.0

### ISSUE THREAD

**Issue by xenoterracide** [github/choosealicense.com#863]
Title says it all? I'd like to see Artistic 2.0 added, one benefit of this license is that it says explicitly that you may not change the text of the license.

**Comment by mlinksva** [comment]
It's been cataloged here since the beginning of this site/repo, or very nearly so https://choosealicense.com/licenses/artistic-2.0/

**Comment by xenoterracide** [comment]
I don't see it here https://choosealicense.com/licenses/, which is why I created this, so perhaps that can be fixed? because I couldn't find it.

**Comment by nschonni** [comment]
It's on the [appendix](https://choosealicense.com/appendix/) linked to at the top of that page
