### ISSUE TITLE
AGPL does have patent grant

### ISSUE THREAD

**Issue by dantman** [github/choosealicense.com#87]
The [licenses page](http://choosealicense.com/licenses/) lists "Patent grant" under GPLv2, LGPL*, and GPLv3.

However it doesn't list "Patent grant" under AGPL/Affero GPL. But looking at the licence text it looks like the AGPL does in fact include a patent grant like the other GPL licences.

**Comment by haacked** [comment]
Sounds like an oversight. Would you care to submit a pull request with the fix?

**Comment by benbalter** [comment]
Fixed via https://github.com/github/choosealicense.com/pull/197.
