### ISSUE TITLE
Extending the instructions for applying Apache 2.0 license

### ISSUE THREAD

**Issue by char0n** [github/choosealicense.com#871]
Hello,

First of all, thank you for the project! I've been wondering if you'd be interested in PR which extends the instructions for application of Apache 2.0 license. I went through a research and I've written an article which clarifies couple of things around Apache 2.0 license. The PR would contain the information from the article.

https://vladimirgorej.com/blog/how-to-apply-apache2-license-to-your-open-source-software-project/

Have a great day!

**Comment by mlinksva** [comment]
Depends on what you have in mind. If you have a _concise_ patch for the `how:` or `note:` fields I'm happy to consider it, though no promises.

Thanks for pointing out https://infra.apache.org/licensing-howto.html and the end of your post. Might be worth considering linking that.

**Comment by char0n** [comment]
Hi @mlinksva,

> Depends on what you have in mind.

Well linking the article would be best. It describes the common patterns of Apache 2.0 miss-application a provides a guideline how to apply the Apache 2.0 license properly

 > If you have a concise patch for the how: or note: fields I'm happy to consider it, though no promises.

At least adding https://infra.apache.org/licensing-howto.html, to `how` field would be great. Not many people are aware of this document and a lot of wrong assumptions and made because of this. I can issue a PR if agreed.

**Comment by mlinksva** [comment]
@char0n OK such a PR would be welcome.

**Comment by char0n** [comment]
@mlinksva PR has been issued https://github.com/github/choosealicense.com/pull/905

**Comment by mlinksva** [comment]
https://github.com/github/choosealicense.com/pull/905#issuecomment-986088515
