### ISSUE TITLE
Use relative units for fonts (rem, em)

### ISSUE THREAD

**Issue by temalcode** [github/choosealicense.com#904]
Hello,

I see that this website uses pixel values on "application.scss" file. I suggest to convert pixel values used for fonts and spacing to relative fonts like "rem'" or "em". This will lead to accessibility of the site and rank higher on Google.

Thank you

**Comment by mlinksva** [comment]
I'm not very familiar but guess this is documented/recommended in places like https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=144#resize-text ?

I'd welcome a pull request that implements this best practice.
