### ISSUE TITLE
Please add GPL v2

### ISSUE THREAD

**Issue by Mart-Bogdan** [github/choosealicense.com#908]
Why there are no GPLv2 on this site?

It's still a widely used license, for example by Linux Kernel and Telegram.

**Comment by nschonni** [comment]
Duplicate of https://github.com/github/choosealicense.com/issues/783

**Comment by Mart-Bogdan** [comment]
Oh I see now. it is present on this URL https://choosealicense.com/licenses/gpl-2.0/

it's just not on /licenses/

That's good. thanks for your effort.
