### ISSUE TITLE
spdx_id mismatching

### ISSUE THREAD

**Issue by arcogabbo** [github/choosealicense.com#909]
Visiting https://spdx.org/licenses/ i saw a mismatch between github REST API identifiers and SPDX ones.
For example GPLv3 has "GPL-3.0-only" as identifier on SPDX but fetching url `https://api.github.com/licenses/gpl-3.0-only` gives error 404. Also the url `https://api.github.com/licenses/gpl-3.0` gives a spdx_id field of `GPL-3.0` instead of `GPL-3.0-only`.

**Comment by mlinksva** [comment]
GPL-3.0 could be -only or -or-later, in both cases, GPL-3.0 is still accurate as the material may be used under that license. The texts aren't any different.

**Comment by arcogabbo** [comment]
But in the spdx licenses list page i linked you, the spdx_id that github uses for gpl is deprecated (see bottom of the page). I'm writing a software that uses spdx identifiers and seeing github using some deprecated spdx identifiers is quite annoying. I hope this can be fixed.
