### ISSUE TITLE
Switching GNU GPLv3 to GNU AGPLv3 on the main page

### ISSUE THREAD

**Issue by ghost** [github/choosealicense.com#997]
Currently the license mentioned under the "I care about sharing improvements" situation is the GNU GPLv3. While this may seem like the right choice for most who fit this situation, some people who use this license [regret doing so and would have used the GNU AGPLv3 instead if they knew about it](https://github.com/dani-garcia/vaultwarden/discussions/1681#discussioncomment-715320) and due to it being difficult to relicense such popular software, can cause major issues. As you see, recommending the GNU AGPLv3 instead of the GNU GPLv3 can have huge benefits for users making software that are commonly interacted with over a network, while having little to no impact on developers that don't.

If there is any huge downside for open source developers that care about sharing improvements doing this, please let me know 🙂.

**Comment by osfanbuff63** [comment]
Personally, I think the best way to take care of this is to use "I care about sharing improvements? Use the GNU GPL v3 or the AGPLv3!", with the differences outlined.

**Comment by mlinksva** [comment]
By the same token, "simple and permissive" should recommend Unlicense/0BSD/MIT-0 rather than MIT. But, the the options on the home page are also cognizant of existing practice (and that's why the first/left option is the first) and these licenses (unconditional and network copyleft) are still relatively marginal. Happy to revisit at some point in the future.

**Comment by ghost** [comment]
Many people when they click on the licenses from the homepage, just read the summany with the coloured dots at the top of the page, especially with licenses with lots of text, such as the GPLv3. What this means is that when people look at the coloured dots, they can see the conditions, permissions and limitations that act upon that license, but because it does not display what conditions, permissions and limitations are **not** applied to that license, they may not make a well informed choice of what license they would like to choode, as theh may not have thought of something that they later want their license to do (e.g. treating network use as distribution).


This also works in reverse. For example, if someone were to click on the MIT license after seeing it as simple and permissive on the homepage, but they do not want the copyright notice condition, they can see that it applies to the MIT license and then go on to choose a different license.


So that it why I think the MIT license shouldnt be replaced with something like the unlicense, while the GPLv3 should be replaced by the AGPLv3. But if you still don't think so, I have a good alternative: displaying the conditions, permissions and limitations that **don't** apply to each license. What this means is that if someone clicks on the GPLv3 after seeing it as good for sharing modifications, they can see that treating network use as distribution is not one of the conditions of the license, and they then realise that is something they want, which allows the developer to make an informed decision about which license to choose.
